<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RasmHost>grasshopper;platform</RasmHost>
    </PropertyGroup>
    <ItemGroup Label="Architecture Rule Tooling">
        <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" PrivateAssets="all" />
        <PackageReference Include="Verify.DiffPlex" PrivateAssets="all" />
        <PackageReference Include="Verify.XunitV3" PrivateAssets="all" />
    </ItemGroup>
    <ItemGroup Label="Project References">
        <ProjectReference Include="../_benchmarks/Rasm.Benchmarks.csproj" />
        <ProjectReference Include="../_scenariokit/Rasm.ScenarioKit.csproj" />
    </ItemGroup>
</Project>
