<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Rhino object state, attributes, materials, lights, history, and custom objects with grips as IO effects over RhinoCommon</Description>
    </PropertyGroup>

    <ItemGroup Label="Core Dependencies">
        <PackageReference Include="LanguageExt.Core" />
        <PackageReference Include="Riok.Mapperly" PrivateAssets="all" />
        <PackageReference Include="Thinktecture.Runtime.Extensions" />
    </ItemGroup>

    <ItemGroup Label="Workspace Packages">
        <ProjectReference Include="../Rasm.Rhino.Commands/Rasm.Rhino.Commands.csproj" />
        <ProjectReference Include="../Rasm.Rhino.Document/Rasm.Rhino.Document.csproj" />
    </ItemGroup>
</Project>
