export const getUserById = (id: string) => id;
export * from './interior.ts';
const parse = (raw: string) => { throw new Error(raw); };
const out: Array<string> = [];
out.push('x');
const head = (xs: ReadonlyArray<string>) => { if (xs.length === 0) { return null; } return xs[0]; };
const _fold = (rows: number) => rows;
export const fold = _fold;
export const live = Effect.runSync(open());
export const DocumentId = Schema.String.pipe(Schema.brand('DocumentId'));
const seen = new Map<string, number>();
const bare = new Map();
const one = new Map([['a', 1]]);
const at = Date.now();
const stamp = new Date();
const parsedDate = new Date('2026-01-01');
const dice = Math.random();
const timer = setTimeout(() => {}, 100);
const zero = setTimeout(fn);
