export const meta = {
  name: 'implement',
  description: 'Realize every open IDEAS/TASKLOG card under a target into deep design-page code FENCES, end-to-end. A nested scout maps the topology, cards, ripples and blockers, pulls every ripple-reached out-of-scope folder into scope to closure (realizing ONLY the ripple-counterpart cards there, nothing else from that folder), and runs a serialized live PROBE that resolves tool-gated BLOCKED cards via assay api / Forge band / Rhino WIP before planning so blocked cards never poison the plan. One planner per sub-domain emits the worklist; conditional package-prep admits new packages and authors their .api catalogs before realize. Each in-scope folder is then realized as ONE implement -> critique -> redteam cycle (per folder, not per page) with every fix made in place and cross-file residuals logged; the residuals reconcile in a bounded loop; one agent per folder closes the cards out. A per-language doctrine table fires the right cs/py/ts bar. args = a target path (e.g. "libs/python/geometry"), an array of targets, or empty/"ALL" for all of libs.',
  phases: [
    { title: 'Map', detail: 'nested scout (probe + closure on): per-sub-domain file/page/.api + card/ripple/blocker map, ripple-closure pull-in (ripple cards only), serial live-tool probe of tool-gated BLOCKED cards' },
    { title: 'Plan', detail: 'one planner per sub-domain: read-only structured work plan (each card -> approach/pages/ripple/admit)' },
    { title: 'Collate', detail: 'pure JS: merge plans by slug, build per-folder in-scope card sets (target = all open cards, pulled-in = ripple cards only), collect admissions' },
    { title: 'Package-prep', detail: 'conditional, serialized per env: admit package -> README -> .csproj -> install -> author .api catalog' },
    { title: 'Realize', detail: 'per in-scope folder, pooled at CAP: implement -> critique -> redteam (all WRITE-capable, each fixing in place and logging cross-file residuals)' },
    { title: 'Reconcile', detail: 'bounded loop: cross-file residuals union-find clustered, fix(max) -> verify(xhigh), repeat until dry or the round cap' },
    { title: 'Closeout', detail: 'one agent per folder: verify each card vs charter, move to [2]-[CLOSED] and collapse; no remediation writes' },
  ],
}

// --- [TYPES] -- structured-output schemas (body consts; scout carries its own SUBMAP) -----
const WORKPLAN = { type: 'object', additionalProperties: false, required: ['subdomain', 'cards'], properties: { subdomain: { type: 'string' }, folder: { type: 'string' }, lang: { type: 'string' }, cards: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['slug', 'kind', 'pages', 'approach'], properties: { slug: { type: 'string' }, kind: { type: 'string', enum: ['idea', 'task'] }, status: { type: 'string' }, atomic: { type: 'boolean' }, thesis: { type: 'string' }, pages: { type: 'array', items: { type: 'string' } }, approach: { type: 'string' }, packages: { type: 'array', items: { type: 'string' } }, ripple: { type: 'array', items: { type: 'string' } }, admit: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['package', 'manifest'], properties: { package: { type: 'string' }, manifest: { type: 'string' }, folder: { type: 'string' }, reason: { type: 'string' } } } } } } } } }
const FIXLOG = { type: 'object', additionalProperties: false, required: ['file', 'verdict', 'summary'], properties: { file: { type: 'string' }, verdict: { type: 'string', enum: ['rebuilt', 'refined', 'clean'] }, collapsed: { type: 'string' }, residual_high: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['files', 'claim'], properties: { files: { type: 'array', items: { type: 'string' } }, claim: { type: 'string' } } } }, summary: { type: 'string' } } }
const RECONCILE_FIX = { type: 'object', additionalProperties: false, required: ['files', 'verdict', 'summary'], properties: { files: { type: 'array', items: { type: 'string' } }, verdict: { type: 'string', enum: ['fixed', 'clean'] }, summary: { type: 'string' } } }
const RECONCILE_VERIFY = { type: 'object', additionalProperties: false, required: ['overall', 'claims'], properties: { overall: { type: 'boolean' }, claims: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['claim', 'status'], properties: { claim: { type: 'string' }, status: { type: 'string', enum: ['fixed', 'invalid', 'open'] }, evidence: { type: 'string' } } } } } }
const PKGPREP = { type: 'object', additionalProperties: false, required: ['package', 'verdict'], properties: { package: { type: 'string' }, verdict: { type: 'string', enum: ['admitted', 'exists', 'skipped'] }, manifest: { type: 'string' }, api_catalog: { type: 'string' }, summary: { type: 'string' } } }
const CLOSEOUT_FOLDER = { type: 'object', additionalProperties: false, required: ['folder', 'cards'], properties: { folder: { type: 'string' }, cards: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['slug', 'disposition'], properties: { slug: { type: 'string' }, disposition: { type: 'string', enum: ['complete', 'dropped', 'open'] }, strength: { type: 'string', enum: ['strong', 'weak', 'partial'] } } } } } }

// --- [HARNESS] -- steady bounded worker pool (<=cap concurrent, staggered start) ----------
const STAGGER_MS = 1500
const pool = async (items, cap, worker) => {
  const out = new Array(items.length)
  let next = 0
  const run = async (slot) => {
    if (slot) await new Promise((res) => setTimeout(res, slot * STAGGER_MS))
    while (next < items.length) { const i = next++; out[i] = await worker(items[i], i) }
  }
  await Promise.all(Array.from({ length: Math.min(cap, items.length) }, (_, slot) => run(slot)))
  return out
}
const CAP = 12 // one concurrency ceiling for every heavy pooled phase (Plan, Package-prep, Realize, Reconcile, Closeout); phases run sequentially so there is no second cap to balance, and the runtime independently clamps to min(16, cores-2), so 12 is the deliberate effective throttle (the serial probe now lives in scout)
const MAX_RECONCILE_ROUNDS = 3

// --- [INPUT] -- args = a target path | [targets] | { target } ; empty/"ALL" = all of libs ---
const TARGETS = Array.isArray(args) ? args.map((t) => String(t).trim()).filter(Boolean) : typeof args === 'string' ? (args.trim() && args.trim() !== 'ALL' ? [args.trim()] : ['libs']) : (args && args.target) ? [String(args.target).trim()] : ['libs']
const langOf = (p) => { const s = p || ''; return s.includes('libs/typescript') ? 'typescript' : s.includes('libs/csharp') ? 'csharp' : 'python' }
// the Geometry effort keeps design pages under `libs/csharp/Rasm/Geometry/.planning/**` but its cards + README + .api live at the `libs/csharp/Rasm/` ROOT; route every card/README read+write there, never to the Geometry sub-folder
const cardOwner = (folder) => folder === 'libs/csharp/Rasm/Geometry' ? 'libs/csharp/Rasm' : folder

// --- [MODELS] -- per-language doctrine table; python lifted verbatim from rebuild-python, --
// --- [MODELS] -- csharp/typescript from their rebuild-* + the same critique/redteam premise -
const LANG = {
  python: {
    root: 'libs/python',
    law: [
      'Rasm monorepo, libs/python planning corpus (markdown specs of intended Python module designs). CLAUDE.md manifest law governs. DENSITY BAR: docs/stacks/python/ (README/language/shapes/surfaces-and-dispatch/rails-and-effects/algorithms/type-system/boundaries/runtime/system-apis) — author Python as dense, polymorphic, and rich as that bar. Cite ONLY members confirmed in the .api catalogs — and MINE BOTH TIERS fully: the shared/universal branch catalogs `libs/python/.api/*.md` AND the folder-specific `libs/python/<folder>/.api/*.md`. Maximize the shared/universal catalogs wherever relevant, never only the folder set.',
      'Realizing a card is a FUNDAMENTAL GROUND-UP build of the planning-stage DESIGN PAGE fences it touches, not a polish pass. Stop anchoring to naive/surface/junior/old-style Python.',
    ].join('\n'),
    ultra: [
      'OPERATIVE DOCTRINE: docs/stacks/python/ is the route-owned law — READ `README.md` (the 16 laws + the 12-signal COLLAPSE_SCAN), `shapes.md` (OWNER_CHOOSER + the lifecycle), `surfaces-and-dispatch.md` (dispatch forms + ASPECTS), and `rails-and-effects.md` (rail/effect law) before building, and hold every fence to them as fact. docs/stacks/csharp/ is the density/ambition FLOOR — match its richness, never import C#-shaped idioms.',
      'LIFECYCLE SPINE (BOUNDARY_ADMISSION): every fence flows `Raw -> Payload -> Canonical owner -> Rail -> Projection -> Egress`. Raw material is admitted EXACTLY ONCE into an evidence-carrying owner (Pydantic/`TypedDict` payload at ingress); interior code never re-validates, never sees `None`-as-failure, sentinels, or provider shapes; egress projects outward (`msgspec.Struct` wire) from the canonical owner. Parameterize BOTH ingress AND egress so the same owner sources and sinks across many providers/apps without touching its interior.',
      'SHAPE LAW: one concept owns exactly ONE type (SHAPE_BUDGET) — variants are cases in one closed family, never sibling types; one rich polymorphic surface over many shallow (DEEP_SURFACES); the owner is shaped for the family it will ABSORB (ANTICIPATORY_COLLAPSE) so the next case/dimension/modality lands as ONE declaration with every consumer untouched or broken loudly at type-check. Choose each owner by the OWNER_CHOOSER discriminants — admission (trusted/untrusted), identity regime (value/tag/key/reference), variant arity (one/closed-family/open), payload timing (def-time/runtime), openness (closed/semi/open) -> the right owner among `TypedDict`, Pydantic, `msgspec.Struct`, frozen dataclass, rich class, `StrEnum`/`Literal`, `sentinel`, `Option`/`Result`, `frozendict`/`Map`/`tuple`, `Protocol`. A misplaced shape traces to one mis-answered discriminant.',
      'ASPECT-FIRST (DEFINITION_TIME_ASPECTS): every CROSS-CUTTING capability — retry, telemetry/spans, validation, contracts, memoization, registration, receipts, fault rails — is a SIGNATURE- and RAIL-PRESERVING decorator (inline `**P` + `functools.wraps`) that materializes policy, STACKS in deterministic order (bottom-up at definition, top-down at call), and NEVER raises into domain flow (a failing aspect returns the rail `Error`). Two-to-four wrappers that always co-occur collapse into ONE parameterized aspect factory. Code reads as STACKED DECORATORS over a thin pure core, never inline-repeated concerns or sibling helper functions; the domain transform itself stays a pure function/fold.',
      'DERIVATION + ARITY: cases sharing generative structure are DERIVED — one primary `frozendict` correspondence declared, every secondary map derived from it (DERIVED_LOGIC), or a fold/comprehension — never enumerated arms. Configuration enters as ONE behavior-carrying value (vocabulary member, tagged variant, frozen policy table), never flag sets the body re-derives (POLICY_VALUES). ONE entrypoint owns every modality (singular/plural/batch/stream), discriminating on the INPUT SHAPE (`T | Iterable[T]` normalized once at the head), never a name suffix or a `mode`/`batch` knob (MODAL_ARITY); a `timeout`/`retry`/`deadline` is an aspect or an `anyio` scope, never a signature param (KNOB_TEST).',
      'RAILS (rails-and-effects): the narrowest carrier that states the outcome, chosen ONCE at admission — `Option[T]` non-failing absence, `Result[T, E]` typed fallibility, `effect.result` do-notation for sequential `bind`, `Block`/`Map` immutable traversal, an `anyio` task group as the failure boundary (NEVER `asyncio.gather`), `stamina.retry` as the decorator (never a sleep-loop). The fault type `E` is a CLOSED vocabulary — `Literal` set, `StrEnum`, or `@tagged_union` family — NEVER a bare `str` for a multi-cause domain. Accumulate-vs-abort is a correctness decision fixed at the boundary: `map2`/accumulating-fold for independent operands (a `bind` chain over independents reports only the first failure), `bind` short-circuit for dependent steps. Cancellation is not failure; resource cleanup is `AsyncExitStack` + a shielded scope.',
      'STACK .api CAPABILITY (load-bearing): FIRST inventory the COMPLETE catalog set available to this page — BOTH the shared/universal branch catalogs at `libs/python/.api/*.md` (anyio, expression, msgspec, pydantic, pydantic-settings, beartype, structlog, stamina, numpy, psutil, opentelemetry-*, protobuf, grpcio) AND every folder-specific catalog at `libs/python/<folder>/.api/*.md` — then mine them for the full ADVANCED surface of each package (combinators, hooks, native pipelines, discriminators, async mirrors) and how packages STACK. List BOTH `.api/` tier DIRECTORIES in full and DIFF that complete inventory against what the page already cites: every admitted catalog whose domain the page admits but does NOT yet use is an ADOPTION TARGET — adopt it to depth here, or when it belongs on a sibling page surface it as a residual; a relevant admitted catalog left unadopted is a DEFECT, not an omission. There is NO fixed library count: compose EVERY relevant admitted library into single dense operations woven as ONE rail, and ALWAYS layer the shared/universal rails (expression `Result`/`Option`, msgspec/pydantic discriminated models, beartype validation, stamina retry, structlog + opentelemetry spans, anyio structured concurrency) ON TOP OF the folder-specific domain packages — e.g. `msgspec dec_hook` -> pydantic discriminated union -> stamina `retry_context` -> opentelemetry span around the domain op — NOT flat one-shot per-library uses. Maximize the shared/universal catalogs wherever relevant, never only the folder set. Use the DEEPEST primitive each package itself reaches for (LIBRARY_DEPTH) — flat code below the operator depth the admitted packages reach is surface sprawl in time; reject surface-level single-feature subsets and any thin rename wrapper.',
      'PRESERVE all capability (densify, never delete functionality). Where a fence is already dense, deepen; where it is flat/naive, build ground-up. Never regress correctness or boundary law.',
    ].join('\n'),
    patlaw: [
      'PY-VERSION LAW: target Python 3.15 on the full modern band (3.11/3.12/3.13/3.14/3.15) — advanced patterns ONLY, zero legacy idioms, IDENTICAL conventions across every folder and package.',
      'NEVER write `from __future__ import annotations`. NEVER use legacy typing: use PEP 585 builtin generics (`list[T]`, `dict[K, V]`, `tuple[...]`, `set[T]`) NOT `typing.List/Dict/Tuple/Set`; PEP 604 unions (`X | None`, `A | B`) NOT `Optional`/`Union`; PEP 695 type parameters (`class C[T]:`, `def f[T](...)`, `type Alias[T] = ...`) NOT `TypeVar` + `Generic`. Use `Self`, `override`, `TypeIs`/`TypeGuard`, `assert_never`, `ReadOnly`, `TypedDict` + `NotRequired`/`Required`, `LiteralString`, `enum.StrEnum`/`IntEnum`, and `@dataclass(slots=True, frozen=True)` or `msgspec.Struct`/pydantic models where each best fits.',
      'PAYLOADS — NEWEST FORM: ingress payloads are static `TypedDict` contracts with `closed=True` or `extra_items=T` and per-key `Required[]`/`NotRequired[]`/`ReadOnly[T]`, admitted through a module-level `TypeAdapter`, with `Unpack[TypedDict]` at root keyword entrypoints (never forwarded through interiors); extension bands fold into `frozendict`/tuple evidence at materialization, and `msgspec.Struct(frozen=True)` owns wire/egress. NO `dict[str, Any]` bags, homogeneous `**kwargs`, or `Mapping[str, object]` payloads.',
      'FROZENDICT (py3.15 builtin): `from builtins import frozendict` is the owner for immutable map rows, dispatch/policy TABLES (one primary `frozendict[K, tuple[...]]`, secondary maps derived from it), payload `extra_items` extension bands, and immutable evidence — REJECT `MappingProxyType`, a module-level mutable `dict` used as a table, tuple-pair pseudo-maps, and mutate-then-freeze. Prefer total `match`/structural pattern matching over if-chains, walrus where it tightens, `assert_never` on closed unions, and PEP 750 t-strings / PEP 749 deferred annotations where relevant. Keep every choice CONSISTENT across folders so the corpus reads as one ultra-advanced codebase.',
    ].join('\n'),
    boundaries: 'BOUNDARY LAW: keep every package/folder owner strictly in its lane; internal code uses canonical names and shapes with mapping only at the edge; do not trample a sibling owner while densifying; respect the dependency direction of the workspace strata.',
    prose: [
      'PROSE QUALITY — apply docs/standards/style-guide.md. The page is a design SPEC: high-signal prose ONLY. Lead each section with the controlling rule/contract; one idea per paragraph; close on the consequence or boundary. Cut noise: no provenance, process narration, freshness disclaimers, report framing, or empty hedges (may/might/probably/generally/where possible). Trim walls of explanation to the load-bearing contract, and prefer a table, a typed signature block, or a tight bullet wherever it carries the design better than a paragraph.',
      'BACKTICK ALL CODE: wrap every symbol, type, field, function, operator, package ID, path, command, flag, and literal value in backticks. Name the exact member/type/rail in backticks instead of paraphrasing behavior. Trimming prose MUST NOT reduce technical density or remove design content.',
    ].join('\n'),
    comments: 'COMMENT HYGIENE: code fences are agent-facing — comment for the next agent, never as a tutorial. KEEP the canonical section-divider headers (language-comment marker + space + `---` + bracketed `[UPPERCASE_LABEL]` + dash-fill). Beyond dividers, comment ONLY where intent is not already obvious from names, types, and signatures: default to ZERO comments on self-evident code; at most 1 line where a comment genuinely earns its place; 1-2 lines only for a truly subtle invariant, contract, or boundary. NO restating the code, no narration, no task/process/session/history/proof/review comments, no docstring bloat. Densify names and types so comments are rarely needed; cut every low-value comment.',
    collapseVocab: 'a closed `@tagged_union`/discriminated-Pydantic family, a `frozendict` dispatch-or-policy table (primary correspondence + derived maps), a fold/comprehension algebra, a signature+rail-preserving aspect factory, and value objects with behavior',
    implementMandate: [
      'DESIGN-CORPUS SURFACE: you work ONLY on the `.planning/` design pages and the transcription-complete code FENCES inside them, plus the per-folder `.api/` catalogs (both tiers), central manifests, and toolchain. To REALIZE a card is to AUTHOR or DEEPEN a code FENCE (a markdown fenced block that IS the work product) inside the owning design page to full doctrine — NEVER to create or land a `.py` source file. A fence is transcription-complete: real declarations, members, cases, fields, signatures, and bodies in exact `.api`-verified spellings an implementer copies verbatim.',
      'WRITE-FULLY MANDATE: every fix you identify you MUST make NOW via Edit/Write directly in the file — the structured fix-log you return is a REPORT of edits ALREADY MADE, never a to-do list, a ledger, or a would/should-fix hedge; leave nothing behind except genuine cross-FILE items (report those in residual_high). If after real investigation a fence is already correct, return verdict=clean — never invent edits to look busy.',
    ].join('\n'),
    tokens: {
      getFamily: '`get`/`get_many`/`get_by_id`', table: 'a `frozendict` table or fold algebra', collapse: 'one closed `@tagged_union`/discriminated-Pydantic family', constTable: 'one `frozendict`/`StrEnum`', aspectFactory: 'one parameterized aspect factory',
      owners: '`TypedDict`/Pydantic/`msgspec.Struct`/frozen dataclass/rich class/`StrEnum`/`Literal`/`sentinel`/`Option`/`Result`/`frozendict`/`Map`/`tuple`/`Protocol`', nullFail: '`None`-as-failure', receipt: '',
      flags: '`strict: bool`/`mode`/`batch` flag', knobScope: 'an aspect or `anyio` scope', aspectForm: 'a SIGNATURE- and RAIL-PRESERVING stacked decorator (inline `**P` + `functools.wraps`)', unit: 'functions',
      rails: 'the narrowest carrier that states the outcome — `Option[T]` non-failing absence, `Result[T, E]` typed fallibility, `effect.result` do-notation, an `anyio` task group as the failure boundary (NEVER `asyncio.gather`), `stamina.retry` as the decorator (never a sleep-loop)', faultVocab: '`Literal` set / `StrEnum` / `@tagged_union` family', looseFault: 'a bare `str` fault', accumulate: '`map2`/accumulating-fold for independents, `bind` short-circuit for dependents', dispatch: '`match`', foldForm: 'fold/comprehension',
      check6: 'PAYLOADS/FROZENDICT/PEP — payloads are `closed=`/`extra_items=` `TypedDict` via a module-level `TypeAdapter` with `Unpack[TypedDict]` at root entrypoints; `frozendict` (builtin) owns tables/evidence (no `MappingProxyType`/dict-table/tuple-pairs); PEP 585/604/695 only, no `from __future__ import annotations`, no legacy typing; total `match` + `assert_never`.',
      doctrine: 'docs/stacks/python/ pages', compileWord: 'type-check', boundaryExtra: '', memberVerify: 'verify the member exists in the `.api` catalog', coldDims: 'payload/`frozendict`/PEP conformance, both-tier `.api` maximization, py3.15-modern typing',
    },
  },
  csharp: {
    root: 'libs/csharp',
    law: [
      'Rasm monorepo, libs/csharp planning corpus (markdown specs of intended C# package designs). CLAUDE.md manifest + WORKSPACE_LAW strata govern (KERNEL -> AEC-DOMAIN -> APP-PLATFORM -> HOST-BOUNDARY -> APP; depend strictly upward; a host-neutral owner only where a non-Rhino runtime consumes the contract). C# PLANNING-HOMING: under `libs/csharp/Rasm` the active planning effort is `Rasm/Geometry` — its design pages live at `libs/csharp/Rasm/Geometry/.planning/**` while its governing `ARCHITECTURE.md`/`IDEAS.md`/`TASKLOG.md`/`README.md` and `.api/` catalogs live at the `libs/csharp/Rasm/` package ROOT (one level UP from `Geometry/`); read those Rasm-root docs + `.api/` as the governing context and shared capability tier for the Geometry pages, and never trample the mature siblings `Analysis`/`Domain`/`Vectors` (not planning targets).',
      'MANDATORY STANDARDS COMPLIANCE: every fence MUST meet docs/stacks/csharp/ (README, language, shapes, surfaces-and-dispatch, rails-and-effects, boundaries, algorithms, system-apis) AND the specialized docs/stacks/csharp/domain/ shard(s) relevant to the page concern (compute, concurrency, data-interchange, diagnostics, durability, interaction, persistence, postgres, resilience, runtime, transport, validation, visuals). READ the relevant shard(s) and conform exactly — this is a hard gate, not advisory. Cite only host/NuGet members confirmed via `uv run python -m tools.assay api`; back bridge claims with EvidenceCertificate + reviewed ReferenceEvidence.',
      'Realizing a card is a FUNDAMENTAL GROUND-UP build of the planning-stage DESIGN PAGE fences it touches, not a polish pass. Even where current C# quality is "good", push to the objectively strongest form the standards admit.',
    ].join('\n'),
    ultra: [
      'ULTRA-ADVANCED MANDATE: COLLAPSE >=3 parallel types / sibling factory methods / repeated switch arms / single-call private helpers into ONE polymorphic owner IN THE SAME FILE via `[Union]` discriminated unions, `SmartEnum<T>` with delegate behavior, readonly-struct/record `[ValueObject]`s, source-generated case families, fold algebra, and data tables — never extract a new file to reduce LOC, never delete capability. AOP: cross-cutting concerns (retry, telemetry, validation, caching, receipts, fault rails) as decorators/aspects.',
      'STACK CAPABILITY: FIRST mine the package `.api/*.md` catalogs (the curated, integration-shaped capability surface at `libs/csharp/<Package>/.api/`; for the `Rasm/Geometry` effort they live at `libs/csharp/Rasm/.api/`) AND the universal Thinktecture / LanguageExt rails — C# has NO central `.api/` tier, so the universals are Thinktecture/LanguageExt plus full docs/stacks/csharp doctrine. There is NO fixed package count: compose EVERY relevant host API + admitted NuGet package + catalog member into single dense owners woven as ONE rail (source-generated owners, fold algebra, data tables), ALWAYS layering the universal Thinktecture/LanguageExt rails onto the domain packages, NOT flat one-shot per-API uses. Capture host/platform surfaces into focused local owners; verify members with `uv run python -m tools.assay api` (host DLLs, NuGet). Maximize the catalogs + universal rails wherever relevant. Use the MOST powerful members; reject surface-level subsets.',
      'PRESERVE all capability (densify, never delete functionality). Where a fence is already dense, deepen; where it is flat/naive, build ground-up. Never regress correctness or boundary/strata law.',
    ].join('\n'),
    patlaw: [
      'C# PATTERN LAW: model the domain precisely — NEVER weak/unbounded/erased types where the language can express the domain; NEVER exception control flow in domain logic (use typed error rails / Result / ROP and the route recovery patterns); NEVER imperative branching where a bounded vocabulary, dispatch table, generated switch, match, or fold owns the variation; NEVER mutable accumulation for domain transforms (use immutable folds, projections, collection combinators). Total switch with exhaustiveness; typed algorithm receipts (NEVER a generic IReceipt/ledger) when fields carry route/status/sampling/solver/spectral/mesh/extraction/benchmark/host evidence.',
      'Latest stable C#/.NET to the metal: primary constructors, collection expressions, `params` collections, list/relational/logical pattern matching, required members, file-scoped types, nullable reference types enforced, generic math / static abstract members where they fit. Treat analyzer diagnostics as architecture pressure (fix true positives, refine false positives, no ceremony suppressions). Apply the docs/stacks/csharp file-organization and section-order law (`[Union]`/`[SmartEnum]`/`[ValueObject]` and generated case families stay inside the declaring owner block).',
      'Keep conventions IDENTICAL across every package; place each package on its canonical stratum and depend strictly upward. One canonical semantic name per bounded concept; arity/filter/provider/modality live in request shape, case, or policy row, not parallel `Get`/`GetMany`/`GetBy<Key>`/`List`/`Search` names.',
    ].join('\n'),
    boundaries: 'BOUNDARY LAW: keep every package owner strictly in its lane and on its stratum; geometry/mesh/IFC meet at the wire with one owner per runtime; internal code uses canonical names and shapes with mapping only at the edge; do not trample a sibling owner while densifying; never introduce a downward dependency or leak a host type into a host-neutral owner.',
    prose: [
      'PROSE QUALITY — apply docs/standards/style-guide.md. The page is a design SPEC: high-signal prose ONLY. Lead each section with the controlling rule/contract; one idea per paragraph; close on the consequence or boundary. Cut noise: no provenance, process narration, freshness disclaimers, report framing, or empty hedges (may/might/probably/generally/where possible). Trim walls of explanation to the load-bearing contract, and prefer a table, a typed signature block, or a tight bullet wherever it carries the design better than a paragraph.',
      'BACKTICK ALL CODE: wrap every symbol, type, field, method, operator, package ID, path, command, flag, and literal value in backticks. Name the exact member/type/rail in backticks instead of paraphrasing behavior. Trimming prose MUST NOT reduce technical density or remove design content.',
    ].join('\n'),
    comments: 'COMMENT HYGIENE: code fences are agent-facing — comment for the next agent, never as a tutorial. KEEP the canonical section-divider headers (language-comment marker + space + `---` + bracketed `[UPPERCASE_LABEL]` + dash-fill). Beyond dividers, comment ONLY where intent is not already obvious from names, types, and signatures: default to ZERO comments on self-evident code; at most 1 line where a comment genuinely earns its place; 1-2 lines only for a truly subtle invariant, contract, or boundary. NO restating the code, no narration, no task/process/session/history/proof/review comments, no XML-doc bloat. Densify names and types so comments are rarely needed; cut every low-value comment.',
    collapseVocab: 'a `[Union]` discriminated union, a `SmartEnum<T>` with delegate behavior, a readonly-struct/record `[ValueObject]`, a source-generated case family, a fold algebra, and a data table — all IN THE SAME FILE, layering the universal Thinktecture/LanguageExt rails',
    implementMandate: [
      'DESIGN-CORPUS SURFACE: you work ONLY on the `.planning/` design pages and the transcription-complete code FENCES inside them, plus the per-package `.api/` catalogs, central manifests, and toolchain. To REALIZE a card is to AUTHOR or DEEPEN a code FENCE (a markdown fenced block that IS the work product) inside the owning design page to full doctrine — NEVER to create or land a `.cs` source file. A fence is transcription-complete: real declarations, members, cases, fields, signatures, and bodies in exact `assay`-verified spellings an implementer copies verbatim.',
      'WRITE-FULLY MANDATE: every fix you identify you MUST make NOW via Edit/Write directly in the file — the structured fix-log you return is a REPORT of edits ALREADY MADE, never a to-do list, a ledger, or a would/should-fix hedge; leave nothing behind except genuine cross-FILE items (report those in residual_high). If after real investigation a fence is already correct, return verdict=clean — never invent edits to look busy.',
    ].join('\n'),
    tokens: {
      getFamily: '`Get`/`GetMany`/`GetBy<Key>`/`List`/`Search`', table: 'a data table or `Fold` algebra', collapse: 'one `[Union]` / `SmartEnum<T>` (delegate behavior) / `[ValueObject]`/`[ComplexValueObject]` / source-generated case family — IN THE SAME FILE', constTable: 'one `[SmartEnum]` vocabulary or frozen set', aspectFactory: 'one parameterized aspect',
      owners: '`[ValueObject<TKey>]` / `[ComplexValueObject]` / `[SmartEnum<TKey>]` / `[SmartEnum]` keyless / `[Union]` / `[Union<T1,...>]` ad-hoc / record / readonly record struct / frozen set / frozen table / a language enum at the seam ONLY', nullFail: 'nullable-as-failure or a struct `default` ghost', receipt: ' A typed algorithm receipt (NEVER a generic `IReceipt`/ledger) when fields carry route/status/sampling/solver/spectral/mesh/extraction/benchmark/host evidence.',
      flags: '`bool`/`mode`/`strict` flag', knobScope: 'a definition-time aspect or a `CancellationToken`/`Schedule` scope', aspectForm: 'a definition-time source-generated aspect (attribute-directed) or a composition-time effect transformer (`Schedule`-driven retry, named catch, bracket)', unit: 'methods',
      rails: 'LanguageExt `Fin<T>` / `Validation<Error,T>` / `Option<T>`, the narrowest carrier chosen once at the admission boundary with generated `Validate` lifting into the rail', faultVocab: '`Expected`-derived `[Union]` fault family', looseFault: 'a bare exception/`Error`', accumulate: 'applicative `Validation` accumulation for independents, `Bind` short-circuit for dependents', dispatch: 'generated `Switch`', foldForm: 'fold/LINQ/collection combinators',
      check6: 'STRATA/MEMBERS/MODERN — strata correctness (depend strictly upward; no host-type leak into a host-neutral owner; geometry/mesh/IFC meet at the wire, one owner per runtime); cite only host/NuGet members confirmed in the package `.api/` catalog (`assay api`-verified, no phantom member); latest modern C# (primary ctors, collection expressions, list/relational patterns, required members, file-scoped types, generic math); docs/stacks/csharp + the relevant domain/ shard conformance; both the package `.api/` catalogs AND the universal Thinktecture/LanguageExt rails maximized, not a surface-level subset.',
      doctrine: 'docs/stacks/csharp standards + the relevant domain/ shard', compileWord: 'compile time', boundaryExtra: 'a downward dependency, a host-type leak into a host-neutral owner, ', memberVerify: 'verify the member exists via `assay api`', coldDims: 'strata correctness, modern-C# typing, docs/stacks/csharp + domain-shard conformance, `.api` + Thinktecture/LanguageExt maximization',
    },
  },
  typescript: {
    root: 'libs/typescript',
    law: [
      'Rasm monorepo, libs/typescript planning corpus (markdown specs of intended TypeScript module designs). The current TypeScript code quality is POOR; realizing a card is a TRUE modernization to ultra-advanced TS, not a polish pass — discard naive idioms wholesale. CLAUDE.md manifest law governs. DENSITY BAR + STANDARD: docs/stacks/typescript/ (README, language, shapes, surfaces-and-dispatch, rails-and-effects, boundaries, system-apis) and the coding-ts standard. Cite only real members of admitted packages — MINE BOTH catalog tiers: the shared/universal `libs/typescript/.api/*.md` (effect, effect-platform, effect-opentelemetry, effect-atom, react, react-dom, clsx) AND the area-specific `libs/typescript/<area>/.api/*.md`, cross-checked against the published types in node_modules. Maximize the shared/universal Effect/Schema/React rails wherever relevant, never only the area set.',
      'Realizing a card is a FUNDAMENTAL GROUND-UP build of the planning-stage DESIGN PAGE fences it touches. Stop anchoring to naive/surface/junior JavaScript-in-TypeScript.',
    ].join('\n'),
    ultra: [
      'ULTRA-ADVANCED MANDATE: COLLAPSE >=3 parallel interfaces/types/classes modelling one concept into ONE polymorphic surface (tagged discriminated union + exhaustive match), never parallel names. AOP: cross-cutting concerns (retry, telemetry, validation, caching, receipts, fault rails) as Effect combinators/layers/decorators, not repeated inline. UNIFIED rails + UNIFIED pipelines + feature-arms-as-cases (never loose separate). Parameterize inputs AND outputs with generics at depth; no stringy/weak typing.',
      'STACK CAPABILITY: FIRST inventory the COMPLETE catalog set — BOTH the shared/universal `libs/typescript/.api/*.md` AND the area-specific `libs/typescript/<area>/.api/*.md` — then compose the admitted libraries into single dense rails. There is NO fixed library count: weave EVERY relevant library, ALWAYS layering the shared/universal Effect ecosystem (`Effect`/`Layer`/`Context`/`Schema`/`Stream`) end-to-end ON TOP OF the area-specific packages, NOT naive `Promise`/`try`-`catch` glue. Maximize the shared/universal rails, never only the area set. Use the MOST powerful combinators; reject surface-level single-feature uses.',
      'PRESERVE all intended capability (densify, never delete functionality). Where a fence is already strong, deepen; where it is flat/naive, build ground-up. Never regress correctness or boundary law.',
    ].join('\n'),
    patlaw: [
      'TS PATTERN LAW (ultra-advanced ONLY; do not preserve the naive idioms of the existing code): ZERO `any`, zero implicit `any`, zero unsafe `as`, zero non-null `!`; model with branded/nominal types, exact discriminated unions with EXHAUSTIVE handling (`assertNever` on the default), `readonly`/`as const`, template-literal types, conditional/mapped types, and the `satisfies` operator. NO runtime `enum` — use `const` unions or `Schema`/Effect.',
      'Domain logic runs on typed-error rails — `Effect`/`Either`/`Option`, NEVER `throw` in domain code; boundaries validate through `Schema` (parse, never trust input). `import type`/`export type` are explicit; side-effect/value imports preserve runtime order. Per the docs/stacks/typescript file-organization overlay: `Effect.Service` owners are SERVICES, `Layer`/runtime wiring is COMPOSITION, runtime schemas/classes are MODELS, and catalog/registry rows stay after the owners they reference.',
      'Keep conventions IDENTICAL across every area so the corpus reads as one ultra-advanced codebase. One canonical semantic name per bounded concept; discriminate on input shape rather than proliferating `get`/`getMany`/`getById` names.',
    ].join('\n'),
    boundaries: 'BOUNDARY LAW: keep every area owner strictly in its lane; internal code uses canonical names and shapes with mapping (and `Schema` validation) only at the edge; do not trample a sibling owner while densifying; respect the dependency direction of the workspace.',
    prose: [
      'PROSE QUALITY — apply docs/standards/style-guide.md. The page is a design SPEC: high-signal prose ONLY. Lead each section with the controlling rule/contract; one idea per paragraph; close on the consequence or boundary. Cut noise: no provenance, process narration, freshness disclaimers, report framing, or empty hedges (may/might/probably/generally/where possible). Trim walls of explanation to the load-bearing contract, and prefer a table, a typed signature block, or a tight bullet wherever it carries the design better than a paragraph.',
      'BACKTICK ALL CODE: wrap every symbol, type, field, function, operator, package ID, path, command, flag, and literal value in backticks. Name the exact member/type/rail in backticks instead of paraphrasing behavior. Trimming prose MUST NOT reduce technical density or remove design content.',
    ].join('\n'),
    comments: 'COMMENT HYGIENE: code fences are agent-facing — comment for the next agent, never as a tutorial. KEEP the canonical section-divider headers (language-comment marker + space + `---` + bracketed `[UPPERCASE_LABEL]` + dash-fill). Beyond dividers, comment ONLY where intent is not already obvious from names, types, and signatures: default to ZERO comments on self-evident code; at most 1 line where a comment genuinely earns its place; 1-2 lines only for a truly subtle invariant, contract, or boundary. NO restating the code, no narration, no task/process/session/history/proof/review comments, no TSDoc bloat. Densify names and types so comments are rarely needed; cut every low-value comment.',
    collapseVocab: 'a tagged discriminated union + exhaustive `match`/`assertNever`, a `Schema` boundary class, an `Effect.Service` owner, an Effect combinator/`Layer` aspect, branded/nominal types, and a data-table dispatch',
    implementMandate: [
      'DESIGN-CORPUS SURFACE: you work ONLY on the `.planning/` design pages and the transcription-complete code FENCES inside them, plus the `.api/` catalogs (both tiers), central manifests, and toolchain. To REALIZE a card is to AUTHOR or DEEPEN a code FENCE (a markdown fenced block that IS the work product) inside the owning design page to full doctrine — NEVER to create or land a `.ts`/`.tsx` source file. A fence is transcription-complete: real declarations, members, cases, fields, signatures, and bodies in exact node_modules-verified spellings an implementer copies verbatim.',
      'WRITE-FULLY MANDATE: every fix you identify you MUST make NOW via Edit/Write directly in the file — the structured fix-log you return is a REPORT of edits ALREADY MADE, never a to-do list, a ledger, or a would/should-fix hedge; leave nothing behind except genuine cross-FILE items (report those in residual_high). If after real investigation a fence is already correct, return verdict=clean — never invent edits to look busy.',
    ].join('\n'),
    tokens: {
      getFamily: '`get`/`getMany`/`getById`', table: 'a data table or fold', collapse: 'one tagged discriminated union + exhaustive `match`/`assertNever`', constTable: 'one `const` union or `Schema`', aspectFactory: 'one parameterized `Layer`/combinator',
      owners: 'a branded/nominal type / `Schema` class / discriminated union / `Effect.Service` / `readonly`+`as const` record (NO runtime `enum`)', nullFail: '`null`-as-failure or a runtime `enum`', receipt: '',
      flags: '`boolean`/`mode` flag', knobScope: 'an Effect combinator/`Layer`', aspectForm: 'an Effect combinator/`Layer`/decorator', unit: 'functions',
      rails: 'typed-error rails `Effect`/`Either`/`Option` (NEVER `throw` in domain code), the narrowest carrier chosen once, with `Schema` parsing at the boundary (never trust input)', faultVocab: 'discriminated-union fault channel', looseFault: '`unknown`/`Error`', accumulate: 'accumulating `Validation`/`Effect.all` for independents, `flatMap` for dependents', dispatch: 'discriminated-union `match` (`assertNever` on the default)', foldForm: 'fold/`ReadonlyArray` combinators',
      check6: 'TYPE_LAW/MEMBERS — ZERO `any`/implicit-any/unsafe `as`/non-null `!`; branded types where primitives overload; `import type`/`export type` explicit; `satisfies` for literal checks; NO runtime `enum`; cite only members real in node_modules (no phantom); BOTH the shared `libs/typescript/.api/` Effect/Schema/Layer/Stream rails AND the area `.api/` maximized; coding-ts + docs/stacks/typescript file-organization conformance.',
      doctrine: 'docs/stacks/typescript standards + coding-ts', compileWord: 'type-check', boundaryExtra: 'an unvalidated `Schema` boundary, ', memberVerify: 'verify the member exists in node_modules', coldDims: 'Schema-boundary + zero-any/throw/enum typing, both-tier `.api` maximization, coding-ts + file-organization conformance',
    },
  },
}
const pickLang = (x) => LANG[x] || LANG[langOf(x)]
const DOC = (L) => [L.law, '', L.ultra, '', L.patlaw, '', L.boundaries, '', L.prose, '', L.comments].join('\n')
const NO_LIVE_ASSAY = 'MEMBER VERIFICATION = THE `.api` CATALOG: cite members from the per-folder/per-tier `.api` catalog (already `assay`-generated and current) — do NOT run a live `assay api`/bridge call or launch Rhino during realize/review/reconcile (the assay bridge + Rhino host are per-machine SINGLETONS and you run CONCURRENTLY; live tool work is the serialized Probe/Package-prep job). If a member you need is genuinely absent from the catalog, record it as a residual_high (a Package-prep/Probe follow-up) rather than decompiling live.'
const DOCW = (L) => [DOC(L), '', L.implementMandate, '', NO_LIVE_ASSAY].join('\n')
// --- the rebuild-python critique/redteam SPEC, parameterized: the ~85% scaffold is shared, the ~15% language idioms ride `L.tokens` ---
const critiqueTemplate = (t) => [
  'You are an ULTRA-HARSH, UNAGREEABLE auditor: assume a violation exists in every fence until you prove otherwise, and "good enough" is rejected. Run these MECHANICAL checklists line-by-line and REPAIR every hit in place (a fix, never a ledger note):',
  '(1) COLLAPSE_SCAN — apply the move for any signal (3+ instances makes it mandatory): sibling prefix/suffix names -> one modality-polymorphic entrypoint; the same return rail differing only by arity -> input-shape discrimination; a ' + t.getFamily + ' family -> one input-keyed entrypoint; functions differing only by a literal -> parameterize the literal as policy; a bool parameter selecting two bodies -> one derived body or policy value; a function calling exactly one other -> delete the hop; a class/owner exposing one public method -> a free operation or fold-on-owner; parallel dispatch arms repeating structure -> ' + t.table + '; 3+ parallel types / sibling factories / near-duplicate shapes for one concept -> ' + t.collapse + '; 3+ sibling constants for one concept -> ' + t.constTable + '; a wrapper renaming a package API -> use the package surface directly; the same 2-4 wrappers/decorators recurring -> ' + t.aspectFactory + '.',
  '(2) OWNER_CHOOSER — for EVERY shape re-derive the owner from the 5 discriminants (admission, identity regime, variant arity, payload timing, openness); if it is not the discriminant-correct owner (' + t.owners + '), replace it. Kill every parallel DTO, one-field wrapper, field-rename shape, tag-only shape, and ' + t.nullFail + '.' + t.receipt,
  '(3) KNOB_TEST — delete each parameter: if the value already encodes what it carried, it was a knob — collapse a ' + t.flags + ' into a policy value or input-shape discriminant, and move every `timeout`/`retry`/`deadline` out of the signature into ' + t.knobScope + '.',
  '(4) ASPECTS — every cross-cutting concern (retry/telemetry/validation/contracts/memo/registration/receipts/fault rails) MUST be ' + t.aspectForm + ' that never raises into domain flow; 2-4 co-occurring wrappers collapse into one aspect; deterministic stacking order verified. Inline-repeated concerns and sibling helper ' + t.unit + ' are defects.',
  '(5) RAILS — ' + t.rails + ', the narrowest carrier chosen once; the fault type is a CLOSED ' + t.faultVocab + ' (' + t.looseFault + ' for a multi-cause domain is a defect); accumulate-vs-abort disposition correct (' + t.accumulate + '); total ' + t.dispatch + ' with exhaustiveness; NO exception control flow in domain logic, NO mutable accumulation (' + t.foldForm + ').',
  '(6) ' + t.check6,
].join('\n')
const redteamTemplate = (t) => [
  'You are the LAST and MOST AGGRESSIVE pass: assume the author and critique missed things and that the chosen design is not the strongest until proven, with the burden of proof on the design, never on you. Open BOTH `.api` tiers, the sibling pages, and the operative ' + t.doctrine + '. Attack from every direction and REPAIR every defect in place — no soft-pedalling, no could/should, a fix never a ledger.',
  'PRIMARY LENS — fundamental design, multi-faceted / multi-dimensional / multi-directional: (A) COUNTERFACTUAL on the core choice — is the owner, the algebra, and the dispatch form categorically the strongest the doctrine admits, or does a denser owner (' + t.collapse + '), ' + t.table + ', or a DEEPER admitted-package primitive collapse the whole fence? If a fundamentally stronger design exists, rebuild to it — never defend the incumbent. (B) ANTICIPATORY_COLLAPSE — compute the DIFF OF THE NEXT FEATURE: when the next case/dimension/knob/modality/provider arrives, does it land as ONE declaration with every consumer untouched (or broken loudly at ' + t.compileWord + ')? If it would touch multiple sites, reshape so the growth axis is a case, row, policy value, or carrier swap. (C) LONG-TAIL + MULTI-DIMENSIONAL — attack every input/output/edge/failure mode (empty, singular, plural, stream, malformed, concurrent, cancelled, partial-failure, version-skew); is the accumulate-vs-abort disposition correct for the REAL boundary; are BOTH ingress AND egress parameterized so this owner sources and sinks across hundreds of apps without interior edits? (D) BOUNDARY-INTEGRITY — a concern owned twice in a runtime, ' + t.boundaryExtra + 'a folder mixing concerns, a concern scattered across folders, or any coupling to a sibling owner\'s INTERIOR (vs its wire/seam) is a defect: fix it, or record it as a cross-file residual. (E) SURFACE-SPRAWL-IN-TIME — an admitted package whose `.api` exposes capability the fence re-derives by hand, flat code below the operator depth the packages reach, a phantom member, or a thin wrapper: collapse to package depth and ' + t.memberVerify + '.',
  'ALSO — FULL COLD ADVERSARIAL RE-REVIEW (run this every time, NOT only when an architectural restructure is warranted): re-attack every conformance dimension with fresh hostile eyes, trusting nothing the prior passes claimed — the COLLAPSE_SCAN signals, OWNER_CHOOSER correctness per shape, the KNOB_TEST per param, the ASPECT taxonomy, rail + closed-fault-vocabulary discipline, ' + t.coldDims + ', and prose/comment hygiene — and fix every defect. Even absent a structural rebuild, the fence must end objectively denser, more correct, and more powerful than the critique left it; if the strongest form is genuinely already present, prove it by finding nothing — never invent churn.',
].join('\n')

// --- [OPERATIONS] -- prompt builders (the live BLOCKED-card probe now lives in scout) ------
const planPrompt = (sd) => { const L = pickLang(sd.lang); return [DOC(L), '', 'TASK: PLAN (READ-ONLY — produce a work plan, edit NOTHING) the realization of sub-domain `' + sd.subdomain + '` (folder `' + sd.folder + '`, lang `' + sd.lang + '`). Read the sub-domain design pages, its owning IDEAS/TASKLOG cards (mapped below), BOTH-tier `.api` catalogs, and the ripple-linked pages/cards in the named sibling packages. For EVERY card emit a decision-complete realize-plan entry: {slug, kind, status, atomic, thesis, pages[] (exact design pages whose FENCES it realizes/deepens), approach (the concrete fence-level design at FULL doctrine in the ' + sd.lang + ' collapse vocabulary — ' + L.collapseVocab + '), packages[] (already-admitted packages it composes), ripple[] (each `<lang>:<pkg> [SLUG]` link this realization triggers, verbatim), admit[] (NEW packages this card needs admitted: {package, manifest, folder, reason}; empty if none)}. A card carrying a `probeFact` was just unblocked — fold that fact into its approach. Decision-complete: zero research deferred to realization. SUBMAP:\n' + JSON.stringify(sd, null, 1)].join('\n') }
// the realize unit is one FOLDER carrying its in-scope card set (target folder = all open cards; pulled-in folder = ripple-counterpart cards only) — one implement -> critique -> redteam cycle owns every page that set touches
const rippleScopeLine = (pulledIn, folder) => pulledIn ? 'PULLED-IN folder (reached only by a ripple from the target scope): realize ONLY the ripple-counterpart card(s) listed below and align their wire/companion SEAM to the already-in-scope origin — touch NO other card and NO other page in this folder, and never couple to the sibling owner\'s INTERIOR (align to its seam/wire only).' : 'TARGET folder: realize every card in its card set to full doctrine.'
const implementFolderPrompt = (folder, cards, pulledIn) => { const L = pickLang(folder); const lang = langOf(folder); const pages = [...new Set(cards.flatMap((c) => c.pages || []))]; return [DOCW(L), '', 'TASK: REALIZE folder `' + folder + '` (lang `' + lang + '`) into deep design-page FENCES at the FULL ' + lang + ' doctrine. ' + rippleScopeLine(pulledIn, folder) + ' You EXCLUSIVELY OWN these pages this pass — ' + JSON.stringify(pages) + ' — no other agent touches them, so make every cross-fence fix HERE. For EACH card: read its charter, its target pages, the ripple-linked pages, and BOTH-tier `.api`, then AUTHOR/DEEPEN the fences to transcription-complete depth via ' + L.collapseVocab + ' — unified rails, stacked aspects, both ingress AND egress parameterized, every admitted package mined to depth and cited ONLY by `.api`-verified member. When a ripple changes a seam, UPDATE the owning `[2]-[SEAMS]`/ARCHITECTURE seam entry (this folder\'s card-owning docs live at `' + cardOwner(folder) + '`). Any card carrying a `probeFact` holds VERIFIED tool evidence — encode that exact signature/member/band/behavior verbatim. Fix-in-place and FIX every reconcile you spot across these owned pages; defer ONLY a genuine item spanning a page OUTSIDE this folder as residual_high {files, claim}. CARDS:\n' + JSON.stringify(cards.map((c) => ({ slug: c.slug, kind: c.kind, atomic: c.atomic, thesis: c.thesis, pages: c.pages, approach: c.approach, ripple: c.ripple, probeFact: c.probeFact })), null, 1) + '\nReturn ONE FIXLOG for the folder (set `file` to `' + folder + '`).'].join('\n') }
const critiqueFolderPrompt = (folder, pages, pulledIn) => { const L = pickLang(folder); return [DOCW(L), '', 'TASK: DOCTRINAL-CONFORMANCE AUDIT + FIX IN PLACE of the realized fences in folder `' + folder + '`, across these pages — ' + JSON.stringify(pages) + (pulledIn ? ' (PULLED-IN folder: audit ONLY these ripple-touched pages; change nothing else in the folder)' : '') + '. Apply each move across ALL listed pages. ' + critiqueTemplate(L.tokens) + '\nAlso enforce both-tier `.api` maximization and prose + comment hygiene. EDIT every page to fix every hit; OVERRIDE any earlier residual you can now resolve here so the reconcile log cannot balloon. Return ONE fix-log (set `file` to `' + folder + '`) + residual_high {files, claim} for genuine cross-FILE items only.'].join('\n') }
const redteamFolderPrompt = (folder, pages, pulledIn) => { const L = pickLang(folder); return [DOCW(L), '', 'TASK: ADVERSARIAL ARCHITECT RED-TEAM + FIX IN PLACE of the realized fences in folder `' + folder + '`, across these pages — ' + JSON.stringify(pages) + (pulledIn ? ' (PULLED-IN folder: red-team ONLY these ripple-touched pages; change nothing else in the folder)' : '') + '. ' + redteamTemplate(L.tokens) + '\nHold the highest bar of any stage; repair every defect in place across ALL listed pages; OVERRIDE earlier findings you resolve. Return ONE fix-log (set `file` to `' + folder + '`) + residual_high {files, claim} for genuine cross-FILE items only.'].join('\n') }
const reconcileFixPrompt = (cl) => { const L = pickLang((cl[0] && cl[0].files && cl[0].files[0]) || 'libs/python'); return [DOCW(L), '', 'TASK: RECONCILE these cross-FILE residuals deferred by the realize + review passes. NO severity — treat EVERY residual as must-address. Read EVERY listed file. For each: if it is a real cross-file defect, FIX it in place (unify the shared type/seam/rail, repair the strata/boundary issue), preserving all capability and regressing no file; if a residual is FACTUALLY INCORRECT or not a real defect, leave it and say why in the summary — never silently skip a real one to avoid work. Residuals:\n' + JSON.stringify(cl, null, 1)].join('\n') }
const reconcileVerifyPrompt = (cl, fix) => { const L = pickLang((cl[0] && cl[0].files && cl[0].files[0]) || 'libs/python'); return [DOC(L), '', 'TASK: ADVERSARIAL VERIFY, one verdict per claim. Read the named files from disk and classify each residual: "fixed" (real defect, now genuinely resolved), "invalid" (the claim is factually wrong / not a real defect — cite why), or "open" (real defect still NOT resolved). Default to "open" on any doubt for a real-looking defect; mark "invalid" ONLY when you can show the claim is wrong. Claims:\n' + JSON.stringify(cl, null, 1) + '\nFiles the fixer touched: ' + JSON.stringify((fix && fix.files) || [])].join('\n') }
const pkgPrepPrompt = (a) => { const L = pickLang(a.lang || a.folder || a.manifest || 'libs/python'); return [DOC(L), '', 'TASK: ADMIT package `' + a.package + '`' + (a.slug ? ' (for card `' + a.slug + '`' + (a.reason ? '; ' + a.reason : '') + ')' : '') + '. Serialized per manifest — you own `' + (a.manifest || '') + '` this step. (1) add `' + a.package + '` at its newest stable version to the owning CENTRAL manifest `' + (a.manifest || '') + '` (Directory.Packages.props / pyproject.toml / pnpm-workspace.yaml; NEVER a per-folder manifest); (2) register it in the owning folder `README` `[2]-[DOMAIN_PACKAGES]`/`[3]-[SUBSTRATE_PACKAGES]`; (3) csharp ONLY: add the matching `<PackageReference>` to the package `.csproj`; PYTHON ONLY: decide the band FIRST — pure-Python wheel -> `.venv` via `uv`; a scientific/native package (Arrow/GDAL/PROJ stack) -> `forge-scientific-sync` (bare) and reflect under the sci-env python; a scipy/numba-hard or `; python_version<\'3.15\'` companion package -> carry the `<3.15` marker and reflect on the cp312 `forge-companion-env` — the band sets the pyproject marker and the install/reflect path (a wrong band forces a doomed source-build); (4) install so `tools/assay` can mine it; (5) author `' + (a.folder || '') + '/.api/' + a.package + '.md` via `uv run python -m tools.assay api` (read tools/assay/README.md FIRST), formatted per docs/standards/{information-structure,formatting,style-guide}.md, citing ONLY assay-verified members. If it already exists fully, return verdict=exists. Return PKGPREP.'].join('\n') }
const closeoutFolderPrompt = (folder, cs, pulledIn) => { const L = pickLang(folder); const owner = cardOwner(folder); return [DOC(L), '', 'TASK: CLOSE OUT the realized cards in folder `' + folder + '`' + (pulledIn ? ' (PULLED-IN folder: judge and close ONLY the ripple cards listed below; never touch the folder\'s other open cards)' : '') + '. You are the TERMINAL GATE and you GRADE YOUR OWN VERDICT, so judge with the burden of proof ON THE CARD: default EVERY card to strength=weak / disposition=open, and only upgrade a card to STRONG + complete when you can CITE, for that card, the SPECIFIC charter requirements its realized fences demonstrably meet — name the fences and the exact members/cases/rails that satisfy each requirement. A card you cannot so justify STAYS OPEN. Read this folder\'s cards at `' + owner + '/IDEAS.md` + `' + owner + '/TASKLOG.md` and the realized design pages. A justified STRONG+complete card -> MOVE it to the `[2]-[CLOSED]` section and COLLAPSE it to `[COMPLETE]` (disposition complete), preserving its `Ripple:` link and mirror slug; a now-moot card -> `[DROPPED]` (disposition dropped). A weak/partial/unjustified card -> LEAVE it OPEN in place (disposition open), do NOT move or mark it complete. NEVER close a weak or merely-plausible fence as complete, and never remediate or re-author here. Finalize any `[2]-[SEAMS]`/ARCHITECTURE seam edit the realization already implies. CARDS:\n' + JSON.stringify(cs.map((c) => ({ slug: c.slug, kind: c.kind, thesis: c.thesis, pages: c.pages })), null, 1) + '\nReturn CLOSEOUT_FOLDER {folder, cards:[{slug, disposition, strength}]}.'].join('\n') }

// --- [OPERATIONS] -- clustering (union-find): reconcile residuals grouped by shared file ---
const clusterByFiles = (items) => {
  const parent = new Map(); const find = (f) => { let p = f; while (parent.get(p) !== p) p = parent.get(p); return p }; const add = (f) => { if (!parent.has(f)) parent.set(f, f) }
  for (const it of items) { (it.files || []).forEach(add); for (let i = 1; i < (it.files || []).length; i++) parent.set(find(it.files[i]), find(it.files[0])) }
  const by = new Map()
  for (const it of items) { const root = (it.files && it.files.length) ? find(it.files[0]) : '__none__'; (by.get(root) || by.set(root, []).get(root)).push(it) }
  return [...by.values()]
}

// --- [COMPOSITION] -----------------------------------------------------------------------
phase('Map')
// scout (probe + closure ON) owns topology + card/ripple mapping, the ripple-closure pull-in (pulled-in folders carry ONLY their ripple-counterpart cards), and the serial live-tool probe of tool-gated BLOCKED cards
const subdomains = []
const legitimate = []       // tool-gated blockers the serial probe could not resolve
const scoutOutOfScope = []  // ripple targets with no realizable folder (language-level / central / unknown pkg)
// ONE unified scout call over ALL targets: shared map+closure+probe, so a folder reached from two targets is mapped once and a target folder is never mis-pulled
const m = await workflow('scout', { scope: TARGETS, probe: true, closure: true })
if (m && Array.isArray(m.subdomains)) for (const sd of m.subdomains) if (sd) subdomains.push(sd)
if (m && Array.isArray(m.legitimate)) legitimate.push(...m.legitimate)
if (m && Array.isArray(m.ripple_out_of_scope)) scoutOutOfScope.push(...m.ripple_out_of_scope)
const targetFolders = new Set(subdomains.filter((s) => s.inScope !== false).map((s) => s.folder))
const pulledInFolders = new Set(subdomains.filter((s) => s.inScope === false).map((s) => s.folder).filter((f) => !targetFolders.has(f)))
log('Map: ' + subdomains.length + ' sub-domain map(s) across ' + TARGETS.length + ' target(s); ' + pulledInFolders.size + ' folder(s) pulled in by ripple closure')
const EMPTY = (extra) => ({ scope: TARGETS.join('+'), languages: [...new Set(subdomains.map((s) => s.lang).filter(Boolean))], folders: [...new Set(subdomains.filter((s) => s.inScope !== false).map((s) => s.folder).filter(Boolean))], pulled_in: [...pulledInFolders], admitted: [], implemented: [], realize_failed: [], closed: [], weak: [], blocked_unresolved: [], ripple_out_of_scope: scoutOutOfScope, hard_residual: [], dropped: [], ...(extra || {}) })
if (!subdomains.length) return EMPTY()

// a BLOCKED card is actionable iff scout left it a verified `fact` (catalog-resolved inline, or probe-unblocked); every other BLOCKED card is reported and dropped
const blockKey = (folder, slug) => (folder || '') + '|' + slug
const seenBlocked = new Set()
const blocked_unresolved = []
for (const sd of subdomains) for (const c of (sd.cards || [])) {
  if ((c.status || '').toUpperCase() !== 'BLOCKED' || c.fact) continue
  const k = blockKey(sd.folder, c.slug); if (seenBlocked.has(k)) continue; seenBlocked.add(k)
  const lg = legitimate.find((b) => blockKey(b.folder, b.slug) === k)
  blocked_unresolved.push({ slug: c.slug, folder: sd.folder, reason: lg ? lg.reason : c.blockerKind === 'task' ? 'gated on other work that must land first' : (c.blocker || 'unresolved blocker') })
}
const actionableSubs = subdomains.map((sd) => ({ ...sd, cards: (sd.cards || []).filter((c) => (c.status || '').toUpperCase() !== 'BLOCKED' || !!c.fact).map((c) => c.fact ? { ...c, probeFact: c.fact } : c) })).filter((sd) => (sd.cards || []).length)
if (!actionableSubs.length) return EMPTY({ blocked_unresolved })

phase('Plan')
const planRaw = await pool(actionableSubs, CAP, (sd) => agent(planPrompt(sd), { label: 'plan:' + sd.folder + '/' + sd.subdomain, phase: 'Plan', schema: WORKPLAN, effort: 'max', stallMs: 300000 }))
const plans = planRaw.map((p, i) => p ? { ...p, folder: actionableSubs[i].folder, lang: actionableSubs[i].lang, subdomain: actionableSubs[i].subdomain } : null).filter(Boolean)
log('Plan: ' + plans.length + '/' + actionableSubs.length + ' sub-domain plan(s)')

phase('Collate')
// probeFact lookup (the verified fact a once-blocked card carries) keyed by folder|slug, threaded onto the plan card
const factByKey = new Map(); for (const sd of actionableSubs) for (const c of (sd.cards || [])) if (c.probeFact) factByKey.set(blockKey(sd.folder, c.slug), c.probeFact)
// merge plan entries by (folder, slug) — a card planned in >1 sub-domain of ONE folder unions its pages/ripple/packages/admit; slugs are NOT globally unique (a ripple mirror reuses the slug), so the FOLDER is part of the identity
const byKey = new Map()
for (const p of plans) for (const c of (p.cards || [])) {
  if (!c.slug) continue
  const key = blockKey(p.folder, c.slug)
  const prev = byKey.get(key)
  if (!prev) { byKey.set(key, { ...c, folder: p.folder, lang: p.lang, probeFact: factByKey.get(key) }); continue }
  byKey.set(key, { ...prev, pages: [...new Set([...(prev.pages || []), ...(c.pages || [])])], ripple: [...new Set([...(prev.ripple || []), ...(c.ripple || [])])], packages: [...new Set([...(prev.packages || []), ...(c.packages || [])])], admit: [...(prev.admit || []), ...(c.admit || [])], approach: [prev.approach, c.approach].filter(Boolean).join('\n'), probeFact: prev.probeFact || factByKey.get(key) })
}
const cards = [...byKey.values()]
const byFolder = new Map(); for (const c of cards) { (byFolder.get(c.folder) || byFolder.set(c.folder, []).get(c.folder)).push(c) }
const folders = [...byFolder.keys()]
const admissions = cards.flatMap((c) => (c.admit || []).map((a) => ({ ...a, slug: c.slug, lang: c.lang, folder: a.folder || c.folder })))
log('Collate: ' + cards.length + ' card(s) across ' + folders.length + ' folder(s) (' + folders.filter((f) => pulledInFolders.has(f)).length + ' pulled-in); ' + admissions.length + ' admission(s)')

let admitted = []
if (admissions.length) {
  phase('Package-prep')
  // serialize by RUNTIME/ENV, not manifest: every python admission shares one `.venv` + Forge env and must not install concurrently; cs/ts use different toolchains so the ENV groups run in parallel
  const byEnv = new Map(); for (const a of admissions) { const k = a.lang || langOf(a.folder || a.manifest || ''); (byEnv.get(k) || byEnv.set(k, []).get(k)).push(a) }
  const res = (await pool([...byEnv.values()], CAP, async (grp) => { const out = []; for (const a of grp) { const r = await agent(pkgPrepPrompt(a), { label: 'pkg:' + a.package, phase: 'Package-prep', schema: PKGPREP, effort: 'high', stallMs: 300000 }); if (r) out.push(r) } return out })).filter(Boolean).flat()
  admitted = res.filter((r) => r.verdict === 'admitted' || r.verdict === 'exists').map((r) => r.package)
  log('Package-prep: ' + admitted.length + '/' + admissions.length + ' package(s) ready')
}

// --- [REALIZE] -- per folder: implement -> critique -> redteam, all WRITE-capable, pooled at CAP ---
const shortFolder = (f) => f.split('/').slice(-2).join('/')
const realizeFolder = async (folder, cs) => {
  const pulledIn = pulledInFolders.has(folder)
  const pages = [...new Set(cs.flatMap((c) => c.pages || []))]
  const tag = 'Realize:' + shortFolder(folder)
  const impl = await agent(implementFolderPrompt(folder, cs, pulledIn), { label: 'impl:' + shortFolder(folder), phase: tag, schema: FIXLOG, effort: 'max', stallMs: 300000 })
  if (!impl) return null // a dead folder implement must not be reviewed, closed out, or counted as implemented
  const crit = await agent(critiqueFolderPrompt(folder, pages, pulledIn), { label: 'crit:' + shortFolder(folder), phase: tag, schema: FIXLOG, effort: 'xhigh', stallMs: 300000 })
  const redteam = crit ? await agent(redteamFolderPrompt(folder, pages, pulledIn), { label: 'rt:' + shortFolder(folder), phase: tag, schema: FIXLOG, effort: 'max', stallMs: 300000 }) : null
  return { folder, pulledIn, pages, slugs: cs.map((c) => c.slug), logs: [impl, crit, redteam].filter(Boolean) }
}
let folderResults = []
if (folders.length) {
  phase('Realize')
  folderResults = (await pool(folders, CAP, (f) => realizeFolder(f, byFolder.get(f)))).filter(Boolean)
  log('Realize: ' + folderResults.length + '/' + folders.length + ' folder(s) realized (implement -> critique -> redteam)')
}

// gate downstream on cards whose folder implement ACTUALLY returned a log
const realizedKeys = new Set(folderResults.flatMap((r) => r.slugs.map((s) => blockKey(r.folder, s))))
const implementedCards = cards.filter((c) => realizedKeys.has(blockKey(c.folder, c.slug)))
const realize_failed = cards.filter((c) => !realizedKeys.has(blockKey(c.folder, c.slug))).map((c) => c.slug)

// --- [RECONCILE] -- bounded loop: cluster -> fix -> verify, repeat until dry or the cap ----
const normRes = (x, page) => typeof x === 'string' ? { files: [page], claim: x } : { files: (x.files && x.files.length) ? x.files : [page], claim: x.claim }
const seedRes = []
const pushRes = (lg, page) => { if (lg && lg.residual_high) for (const x of lg.residual_high) seedRes.push(normRes(x, page)) }
for (const r of folderResults) for (const lg of r.logs) pushRes(lg, (r.pages && r.pages[0]) || r.folder)
let pending = [...new Map(seedRes.filter((r) => r.claim && (r.files || []).some((f) => f)).map((r) => [r.files.slice().sort().join(',') + '|' + r.claim, r])).values()]
const dropped = []
if (pending.length) phase('Reconcile')
let round = 0
while (pending.length && round < MAX_RECONCILE_ROUNDS) {
  round++
  const clusters = clusterByFiles(pending)
  const out = (await pipeline(
    clusters,
    (cl) => agent(reconcileFixPrompt(cl), { label: 'recon-fix:r' + round, phase: 'Reconcile', schema: RECONCILE_FIX, effort: 'max', stallMs: 300000 }),
    (fix, cl, i) => fix ? agent(reconcileVerifyPrompt(cl, fix), { label: 'recon-verify:r' + round + ':' + i, phase: 'Reconcile', schema: RECONCILE_VERIFY, effort: 'xhigh', stallMs: 300000 }).then((v) => ({ cluster: cl, verify: v })) : null,
  )).filter(Boolean)
  const next = []
  for (const o of out) { const files = [...new Set(o.cluster.flatMap((x) => x.files || []))]; for (const c of ((o.verify && o.verify.claims) || [])) { if (c.status === 'open') next.push({ files, claim: c.claim }); else if (c.status === 'invalid') dropped.push({ files, claim: c.claim, evidence: c.evidence || '' }) } }
  const nextUniq = [...new Map(next.map((r) => [r.files.slice().sort().join(',') + '|' + r.claim, r])).values()]
  // progress = at least one PRIOR claim is no longer open (the claim text is the stable identity the verifier echoes back); break on a fixpoint, never merely on equal count
  const priorClaims = new Set(pending.map((r) => r.claim))
  const stillOpenPrior = new Set(nextUniq.map((r) => r.claim).filter((cl) => priorClaims.has(cl)))
  log('Reconcile round ' + round + ': ' + clusters.length + ' cluster(s) -> ' + nextUniq.length + ' open (' + stillOpenPrior.size + '/' + priorClaims.size + ' prior unresolved)')
  if (stillOpenPrior.size >= priorClaims.size) { pending = nextUniq; break }
  pending = nextUniq
}
const hard_residual = pending

let closeouts = []
if (implementedCards.length) {
  phase('Closeout')
  const coByFolder = new Map(); for (const c of implementedCards) { (coByFolder.get(c.folder) || coByFolder.set(c.folder, []).get(c.folder)).push(c) }
  closeouts = (await pool([...coByFolder.entries()], CAP, ([folder, cs]) => agent(closeoutFolderPrompt(folder, cs, pulledInFolders.has(folder)), { label: 'closeout:' + shortFolder(folder), phase: 'Closeout', schema: CLOSEOUT_FOLDER, effort: 'xhigh', stallMs: 300000 }))).filter(Boolean)
  log('Closeout: ' + closeouts.reduce((n, f) => n + ((f.cards || []).length), 0) + ' card(s) across ' + closeouts.length + ' folder(s)')
}

return {
  scope: TARGETS.join('+'),
  languages: [...new Set(subdomains.map((s) => s.lang).filter(Boolean))],
  folders: [...new Set(subdomains.filter((s) => s.inScope !== false).map((s) => s.folder).filter(Boolean))],
  pulled_in: [...pulledInFolders],
  admitted,
  implemented: implementedCards.map((c) => c.slug),
  realize_failed,
  closed: closeouts.flatMap((f) => (f.cards || []).filter((c) => c.disposition === 'complete' || c.disposition === 'dropped').map((c) => ({ slug: c.slug, disposition: c.disposition }))),
  weak: closeouts.flatMap((f) => (f.cards || []).filter((c) => c.disposition === 'open' || c.strength === 'weak' || c.strength === 'partial').map((c) => c.slug)),
  blocked_unresolved,
  ripple_out_of_scope: scoutOutOfScope,
  hard_residual,
  dropped,
}
