export const meta = {
  name: 'rebuild-python',
  description: 'Ground-up rebuild of libs/python design pages to world-class py3.15 (ADT collapse, AOP, unified rails, full both-tier .api-stacking) AND justified IN-PLACE capability extension: a per-folder Survey first maps the shared owners (cross-file unification) and the per-page capability gaps (the cases/rows/fields/operations a domain-complete owner must carry but the page omits, sourced from the admitted package surface, the real domain concept, or a consumer contract), then each page is rebuilt+critiqued+redteamed to collapse, stack both .api tiers, AND close those gaps by growing the existing owner in place. Structural collapse and capability completeness are orthogonal: a fully-collapsed page can still be capability-sparse. args = optional folder scope (e.g. "geometry"); empty/"ALL" = all of libs/python.',
  phases: [
    { title: 'Discover', detail: 'list every design page under the target (recursive .planning specs)' },
    { title: 'Survey', detail: 'per folder: read ALL its pages + ARCHITECTURE/README + both .api tiers + docs/stacks/python -> map shared owners (cross-file unification) + per-page JUSTIFIED capability gaps to extend in place; assess capability COVERAGE vs the domain (not byte-count)' },
    { title: 'Rebuild', detail: 'per page (survey-informed): rebuild(max) -> critique(xhigh, 6-checklist + capability-completeness) -> adversarial redteam(max, counterfactual + cold re-review + justified-extension), pooled at CAP=14' },
  ],
}

const DISCOVERY_SCHEMA = { type: 'object', additionalProperties: false, required: ['pages'], properties: { pages: { type: 'array', items: { type: 'string' } } } }
const SURVEY_SCHEMA = { type: 'object', additionalProperties: false, required: ['folder', 'pages'], properties: {
  folder: { type: 'string' },
  shared_owners: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['owner', 'home_page', 'spans'], properties: { owner: { type: 'string' }, home_page: { type: 'string' }, spans: { type: 'array', items: { type: 'string' } }, note: { type: 'string' } } } },
  pages: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['page', 'coverage', 'gaps'], properties: { page: { type: 'string' }, coverage: { type: 'string', enum: ['sparse', 'partial', 'complete'] }, size: { type: 'string', enum: ['small', 'medium', 'large'] }, gaps: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['capability', 'source', 'lands_as'], properties: { capability: { type: 'string' }, source: { type: 'string', enum: ['package', 'domain', 'consumer'] }, cite: { type: 'string' }, lands_as: { type: 'string' } } } } } } },
} }
const FIXLOG_SCHEMA = { type: 'object', additionalProperties: false, required: ['file', 'verdict', 'summary'], properties: { file: { type: 'string' }, verdict: { type: 'string', enum: ['rebuilt', 'refined', 'clean'] }, collapsed: { type: 'string' }, extended: { type: 'string' }, residual_high: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['files', 'claim'], properties: { files: { type: 'array', items: { type: 'string' } }, claim: { type: 'string' } } } }, summary: { type: 'string' } } }

// --- [HARNESS] -- bounded worker pool: steady <=cap concurrent, no burst ----------------
const STAGGER_MS = 1500
const pool = async (items, cap, worker) => {
  const out = new Array(items.length)
  let next = 0
  const run = async (slot) => {
    if (slot) await new Promise((res) => setTimeout(res, slot * STAGGER_MS))
    while (next < items.length) { const i = next++; out[i] = await worker(items[i], i) }
  }
  await Promise.all(Array.from({ length: Math.min(cap, items.length) }, (_, slot) => run(slot)))
  return out
}
const CAP = 8

// --- [INPUT] -- args = optional scope under the language root (folder name or sub-path; empty/"ALL" = whole root) ---
const input = typeof args === 'string' ? (() => { try { return JSON.parse(args) } catch { return args } })() : args
const ROOT = 'libs/python'
const SHARED_API = 'libs/python/.api'
const rawScope = (typeof input === 'string') ? input.trim() : (input && typeof input === 'object' && input.target) ? String(input.target).trim() : ''
const SCOPE = (!rawScope || rawScope === 'ALL') ? '' : rawScope
const SWEEP = !SCOPE ? ROOT : (SCOPE === ROOT || SCOPE.indexOf(ROOT + '/') === 0) ? SCOPE : ROOT + '/' + SCOPE
const folderOf = (p) => { const head = p.split('/.planning/')[0].split('/'); return head[head.length - 1] || 'root' }
const folderPathOf = (p) => p.split('/.planning/')[0]
const subOf = (p) => p.split('/.planning/').pop()

const LAW = [
  'Rasm monorepo, libs/python planning corpus (markdown specs of intended Python module designs). CLAUDE.md manifest law governs. DENSITY BAR: docs/stacks/python/ (README/language/shapes/surfaces-and-dispatch/rails-and-effects/algorithms/type-system/boundaries/runtime/system-apis) — author Python as dense, polymorphic, and rich as that bar. Cite ONLY members confirmed in the .api catalogs — and MINE BOTH TIERS fully: the shared/universal branch catalogs `libs/python/.api/*.md` AND the folder-specific `libs/python/<folder>/.api/*.md`. Maximize the shared/universal catalogs wherever relevant, never only the folder set.',
  'This is a FUNDAMENTAL GROUND-UP REBUILD of a planning-stage DESIGN PAGE, not a polish pass. Stop anchoring to naive/surface/junior/old-style Python. Improve the page objectively: collapse surfaces/types, deepen bleeding-edge spellings, maximize admitted-library capability, AND close the concept capability gaps.',
  'WRITE-FULLY MANDATE: every fix you identify you MUST make NOW via Edit/Write directly in the file — the structured fix-log you return is a REPORT of edits ALREADY MADE, never a to-do list, a ledger, or a would/should-fix hedge; leave nothing behind except genuine cross-FILE items (report those in residual_high). If after real investigation the file is already correct, return verdict=clean — never invent edits to look busy.',
].join('\n')
const ULTRA = [
  'OPERATIVE DOCTRINE: docs/stacks/python/ is the route-owned law — READ `README.md` (the 16 laws + the 12-signal COLLAPSE_SCAN), `shapes.md` (OWNER_CHOOSER + the lifecycle), `surfaces-and-dispatch.md` (dispatch forms + ASPECTS), and `rails-and-effects.md` (rail/effect law) before rebuilding, and hold every fence to them as fact. docs/stacks/csharp/ is the density/ambition FLOOR — match its richness, never import C#-shaped idioms.',
  'LIFECYCLE SPINE (BOUNDARY_ADMISSION): every fence flows `Raw -> Payload -> Canonical owner -> Rail -> Projection -> Egress`. Raw material is admitted EXACTLY ONCE into an evidence-carrying owner (Pydantic/`TypedDict` payload at ingress); interior code never re-validates, never sees `None`-as-failure, sentinels, or provider shapes; egress projects outward (`msgspec.Struct` wire) from the canonical owner. Parameterize BOTH ingress AND egress so the same owner sources and sinks across many providers/apps without touching its interior.',
  'SHAPE LAW: one concept owns exactly ONE type (SHAPE_BUDGET) — variants are cases in one closed family, never sibling types; one rich polymorphic surface over many shallow (DEEP_SURFACES); the owner is shaped for the family it will ABSORB (ANTICIPATORY_COLLAPSE) so the next case/dimension/modality lands as ONE declaration with every consumer untouched or broken loudly at type-check. Choose each owner by the OWNER_CHOOSER discriminants — admission (trusted/untrusted), identity regime (value/tag/key/reference), variant arity (one/closed-family/open), payload timing (def-time/runtime), openness (closed/semi/open) -> the right owner among `TypedDict`, Pydantic, `msgspec.Struct`, frozen dataclass, rich class, `StrEnum`/`Literal`, `sentinel`, `Option`/`Result`, `frozendict`/`Map`/`tuple`, `Protocol`. A misplaced shape traces to one mis-answered discriminant.',
  'ASPECT-FIRST (DEFINITION_TIME_ASPECTS): every CROSS-CUTTING capability — retry, telemetry/spans, validation, contracts, memoization, registration, receipts, fault rails — is a SIGNATURE- and RAIL-PRESERVING decorator (inline `**P` + `functools.wraps`) that materializes policy, STACKS in deterministic order (bottom-up at definition, top-down at call), and NEVER raises into domain flow (a failing aspect returns the rail `Error`). Two-to-four wrappers that always co-occur collapse into ONE parameterized aspect factory. Code reads as STACKED DECORATORS over a thin pure core, never inline-repeated concerns or sibling helper functions; the domain transform itself stays a pure function/fold.',
  'DERIVATION + ARITY: cases sharing generative structure are DERIVED — one primary `frozendict` correspondence declared, every secondary map derived from it (DERIVED_LOGIC), or a fold/comprehension — never enumerated arms. Configuration enters as ONE behavior-carrying value (vocabulary member, tagged variant, frozen policy table), never flag sets the body re-derives (POLICY_VALUES). ONE entrypoint owns every modality (singular/plural/batch/stream), discriminating on the INPUT SHAPE (`T | Iterable[T]` normalized once at the head), never a name suffix or a `mode`/`batch` knob (MODAL_ARITY); a `timeout`/`retry`/`deadline` is an aspect or an `anyio` scope, never a signature param (KNOB_TEST).',
  'RAILS (rails-and-effects): the narrowest carrier that states the outcome, chosen ONCE at admission — `Option[T]` non-failing absence, `Result[T, E]` typed fallibility, `effect.result` do-notation for sequential `bind`, `Block`/`Map` immutable traversal, an `anyio` task group as the failure boundary (NEVER `asyncio.gather`), `stamina.retry` as the decorator (never a sleep-loop). The fault type `E` is a CLOSED vocabulary — `Literal` set, `StrEnum`, or `@tagged_union` family — NEVER a bare `str` for a multi-cause domain. Accumulate-vs-abort is a correctness decision fixed at the boundary: `map2`/accumulating-fold for independent operands (a `bind` chain over independents reports only the first failure), `bind` short-circuit for dependent steps. Cancellation is not failure; resource cleanup is `AsyncExitStack` + a shielded scope.',
  'STACK .api CAPABILITY (load-bearing): FIRST inventory the COMPLETE catalog set available to this page — BOTH the shared/universal branch catalogs at `libs/python/.api/*.md` (anyio, expression, msgspec, pydantic, pydantic-settings, beartype, structlog, stamina, numpy, psutil, opentelemetry-*, protobuf, grpcio) AND every folder-specific catalog at `libs/python/<folder>/.api/*.md` — then mine them for the full ADVANCED surface of each package (combinators, hooks, native pipelines, discriminators, async mirrors) and how packages STACK. List BOTH `.api/` tier DIRECTORIES in full and DIFF that complete inventory against what the page already cites: every admitted catalog whose domain the page admits but does NOT yet use is an ADOPTION TARGET — adopt it to depth here, or when it belongs on a sibling page surface it as a residual; a relevant admitted catalog left unadopted is a DEFECT, not an omission. There is NO fixed library count: compose EVERY relevant admitted library into single dense operations woven as ONE rail, and ALWAYS layer the shared/universal rails (expression `Result`/`Option`, msgspec/pydantic discriminated models, beartype validation, stamina retry, structlog + opentelemetry spans, anyio structured concurrency) ON TOP OF the folder-specific domain packages — e.g. `msgspec dec_hook` -> pydantic discriminated union -> stamina `retry_context` -> opentelemetry span around the domain op — NOT flat one-shot per-library uses. Maximize the shared/universal catalogs wherever relevant, never only the folder set. Use the DEEPEST primitive each package itself reaches for (LIBRARY_DEPTH) — flat code below the operator depth the admitted packages reach is surface sprawl in time; reject surface-level single-feature subsets and any thin rename wrapper.',
  'PRESERVE all capability (densify, never delete functionality). Where a page is already dense, refine; where it is flat/naive, rebuild ground-up. Never regress correctness or boundary law.',
].join('\n')
const EXTEND = [
  'CAPABILITY EXTENSION (justified, in-place, never flat spam) — structural collapse and both-tier `.api`-stacking are NECESSARY but NOT SUFFICIENT. A page can be fully collapsed into one closed family/ADT and STILL be capability-thin: modeling a NAIVE, LIMITED slice of its domain concept — a flat id/member set where the concept owns geometry, metrics, attributes, topology, and operations; a 2-variant `@tagged_union` where the domain has twenty; a `TypedDict`/`Struct` with the obvious 3 keys where the concept carries fifteen. Structural completeness and CAPABILITY completeness are ORTHOGONAL. A FULL rebuild ALSO closes the capability gap so the page OWNS ITS DOMAIN CONCEPT COMPLETELY. Per COMPOSED_IMPLEMENTATION + the doctrine growth law (capability grows sublinearly; growth lands as cases/rows/policy-values INSIDE existing owners, never new surfaces beside them), every real missing concern lands as a CASE in the existing closed `@tagged_union`/`Literal`/`StrEnum` family, a ROW or richer data on the existing `frozendict` table, a FIELD on the existing `msgspec.Struct`/Pydantic model/frozen dataclass/`TypedDict`, an OPERATION on the existing surface, or a POLICY_VALUE on the existing vocabulary — reshaping the owner as if it had always carried it; NEVER a parallel type, a new file, a sibling shape, or flat appended code.',
  'GAP SOURCES (every extension MUST cite exactly one — justified, never speculative): (a) PACKAGE — a member the admitted package surface exposes that the concept ADMITS but the page IGNORES is a missing case in the owner law (BOTH tiers: the shared `libs/python/.api/` rails — numpy, pydantic, msgspec, anyio, expression, beartype, stamina, structlog, opentelemetry — AND the folder domain packages; stacking that full surface IS new functionality woven into the owner, not a denser spelling of the same call; verify the member exists). (b) DOMAIN — an attribute, metric, sub-kind, relationship, state, or operation the REAL concept demands but the page omits (a mesh owns its topology/normals/UV/attributes and validate/repair/query operations, not a vertex array alone; a data schema owns constraints/indexes/partitions/coverage, not naive columns; a geometry owner owns the full predicate/transform/measure family the domain needs). (c) CONSUMER — a contract a sibling or downstream owner will require that has no composed spelling here yet (a need with no spelling marks a missing case: the law extends first, the feature lands second).',
  'COVERAGE OVER SIZE: byte-count is a WEAK proxy — capability COVERAGE against the full domain + both-tier package surface is the real measure. A SMALL page modeling a rich concept is almost always under-built (give it the DEEPEST sweep), AND a LARGE, well-collapsed page can still be capability-SPARSE (an owner that indexes membership but models none of the concept geometry, metrics, attributes, topology, or analytics). Assess each owner against its domain independently of size and EXTEND every owner the concept under-realizes IN PLACE — integrated and unified into the one owner at full operator depth, every new field/case/operation composing the existing rails — never a new flat surface beside it.',
  'JUSTIFIED, NOT RANDOM: if after a real domain + package + consumer sweep the concept is genuinely complete, prove it by adding nothing — never invent capability to look busy or pad with flat fields. Every added case/row/field/operation is load-bearing, cites a package member / domain attribute / consumer contract, and composes the existing rails; preserve ALL existing capability — extension only deepens, never regresses.',
].join('\n')
const PATLAW = [
  'PY-VERSION LAW: target Python 3.15 on the full modern band (3.11/3.12/3.13/3.14/3.15) — advanced patterns ONLY, zero legacy idioms, IDENTICAL conventions across every folder and package.',
  'NEVER write `from __future__ import annotations`. NEVER use legacy typing: use PEP 585 builtin generics (`list[T]`, `dict[K, V]`, `tuple[...]`, `set[T]`) NOT `typing.List/Dict/Tuple/Set`; PEP 604 unions (`X | None`, `A | B`) NOT `Optional`/`Union`; PEP 695 type parameters (`class C[T]:`, `def f[T](...)`, `type Alias[T] = ...`) NOT `TypeVar` + `Generic`. Use `Self`, `override`, `TypeIs`/`TypeGuard`, `assert_never`, `ReadOnly`, `TypedDict` + `NotRequired`/`Required`, `LiteralString`, `enum.StrEnum`/`IntEnum`, and `@dataclass(slots=True, frozen=True)` or `msgspec.Struct`/pydantic models where each best fits.',
  'PAYLOADS — NEWEST FORM: ingress payloads are static `TypedDict` contracts with `closed=True` or `extra_items=T` and per-key `Required[]`/`NotRequired[]`/`ReadOnly[T]`, admitted through a module-level `TypeAdapter`, with `Unpack[TypedDict]` at root keyword entrypoints (never forwarded through interiors); extension bands fold into `frozendict`/tuple evidence at materialization, and `msgspec.Struct(frozen=True)` owns wire/egress. NO `dict[str, Any]` bags, homogeneous `**kwargs`, or `Mapping[str, object]` payloads.',
  'FROZENDICT (py3.15 builtin): `from builtins import frozendict` is the owner for immutable map rows, dispatch/policy TABLES (one primary `frozendict[K, tuple[...]]`, secondary maps derived from it), payload `extra_items` extension bands, and immutable evidence — REJECT `MappingProxyType`, a module-level mutable `dict` used as a table, tuple-pair pseudo-maps, and mutate-then-freeze. Prefer total `match`/structural pattern matching over if-chains, walrus where it tightens, `assert_never` on closed unions, and PEP 750 t-strings / PEP 749 deferred annotations where relevant. Keep every choice CONSISTENT across folders so the corpus reads as one ultra-advanced codebase.',
].join('\n')
const BOUNDARIES = 'BOUNDARY LAW: keep every package/folder owner strictly in its lane; internal code uses canonical names and shapes with mapping only at the edge; do not trample a sibling owner while densifying; respect the dependency direction of the workspace strata.'
const PROSE = [
  'PROSE QUALITY — apply docs/standards/style-guide.md. The page is a design SPEC: high-signal prose ONLY. Lead each section with the controlling rule/contract; one idea per paragraph; close on the consequence or boundary. Cut noise: no provenance, process narration, freshness disclaimers, report framing, or empty hedges (may/might/probably/generally/where possible). Trim walls of explanation to the load-bearing contract, and prefer a table, a typed signature block, or a tight bullet wherever it carries the design better than a paragraph.',
  'BACKTICK ALL CODE: wrap every symbol, type, field, function, operator, package ID, path, command, flag, and literal value in backticks. Name the exact member/type/rail in backticks instead of paraphrasing behavior. Trimming prose MUST NOT reduce technical density or remove design content.',
].join('\n')
const COMMENTS = 'COMMENT HYGIENE: code fences are agent-facing — comment for the next agent, never as a tutorial. KEEP the canonical section-divider headers (language-comment marker + space + `---` + bracketed `[UPPERCASE_LABEL]` + dash-fill). Beyond dividers, comment ONLY where intent is not already obvious from names, types, and signatures: default to ZERO comments on self-evident code; at most 1 line where a comment genuinely earns its place; 1-2 lines only for a truly subtle invariant, contract, or boundary. NO restating the code, no narration, no task/process/session/history/proof/review comments, no docstring bloat. Densify names and types so comments are rarely needed; cut every low-value comment.'

// --- [OPERATIONS] -- prompt builders: survey (folder map), author (rebuild), critique, redteam ----
const svyBlock = (svy) => (svy && ((svy.gaps && svy.gaps.length) || (svy.shared_owners && svy.shared_owners.length))) ? '\nSURVEY MAP for this page (capability COVERAGE = `' + (svy.coverage || 'unknown') + '`, size = `' + (svy.size || 'unknown') + '`; compose the shared owners as ONE body, and CLOSE these justified capability gaps by extending the owner IN PLACE — a case/row/field/operation on the EXISTING owner, never a parallel surface or a new file; `sparse` coverage means an under-built concept that earns the deepest domain + package sweep regardless of page size):\n' + JSON.stringify({ shared_owners: svy.shared_owners || [], gaps: svy.gaps || [] }, null, 1) : ''

const surveyPrompt = (folderPath, pages) => [LAW, '', ULTRA, '', EXTEND, '', PATLAW, '', BOUNDARIES, '',
  'TASK: CAPABILITY SURVEY of the folder `' + folderPath + '` (its design pages: ' + JSON.stringify(pages) + '). Read EVERY page in the folder, its `ARCHITECTURE.md` + `README.md`, BOTH .api tiers (the shared `' + SHARED_API + '/*.md` AND the folder `' + folderPath + '/.api/*.md`), and the operative docs/stacks/python/ pages. Produce a folder-level map that makes the per-page rebuild both UNIFIED and JUSTIFIED-EXTENDED, NOT random — this is a READ-ONLY map, edit nothing:',
  '(1) shared_owners — the shared logic/capabilities that span >1 page and their canonical home, so each per-file rebuild COMPOSES the ONE owner (COMPOSED_IMPLEMENTATION) instead of re-deriving it: name the owner, its home page, and the pages that must compose it.',
  '(2) pages — for EACH page: a capability COVERAGE rating (`sparse`/`partial`/`complete` = how completely the page realizes its domain concept against the FULL domain + both-tier admitted-package surface, INDEPENDENT of byte-count — a large well-collapsed page can be `sparse` if it models a thin slice of a rich concept, e.g. a mesh owner carrying a vertex array but none of the concept topology/normals/UV/attributes/operations), a `size` note (`small`/`medium`/`large`), and the JUSTIFIED capability gaps — the cases/rows/fields/operations/policy-values the concept owner MUST carry but the page omits, EACH with its `source` (`package` = a member the admitted surface exposes that the concept admits but the page ignores / `domain` = an attribute, metric, sub-kind, relationship, or operation the real concept demands / `consumer` = a contract a sibling or downstream owner will require), a `cite` (the exact package member, domain concern, or consumer page), and `lands_as` (the case/row/field/operation on which EXISTING owner it extends — never a parallel surface). Hunt HARDEST on `sparse`-coverage owners and small files; if a concept is genuinely complete, list no gap for it. Return the structured survey.'].join('\n')

const authorPrompt = (page, svy) => [LAW, '', ULTRA, '', EXTEND, '', PATLAW, '', BOUNDARIES, '', PROSE, '', COMMENTS, '', 'TASK: ground-up REBUILD of ' + page + ' to the doctrine AND to domain-complete capability. Read the page, its sibling pages (cross-page unification), the operative docs/stacks/python/ pages, and BOTH .api tiers (mine the full advanced surface, ADD any shared/universal rail the page under-uses, STACK them). Construct in LIFECYCLE order: admit raw ONCE into a typed `TypedDict`/Pydantic payload -> materialize into the canonical owner chosen by the OWNER_CHOOSER discriminants -> weave every cross-cutting concern (retry/telemetry/validation/contracts/memo/receipts) as a STACKED signature+rail-preserving aspect over a thin pure core -> compose the domain transform through ONE unified rail -> project + egress, with BOTH ingress and egress parameterized. Collapse parallel shapes into one closed family/ADT; drive cases with a derived `frozendict` table or fold; one polymorphic entrypoint per modality (`T | Iterable[T]` normalized once). BEYOND structural collapse + both-tier `.api` maximization, CLOSE THE CONCEPT CAPABILITY GAPS so the page OWNS ITS DOMAIN CONCEPT COMPLETELY: extend the EXISTING owner in place with the missing cases/rows/fields/operations/policy-values (the survey gaps below plus any further justified gap you find), each grown per ANTICIPATORY_COLLAPSE + COMPOSED_IMPLEMENTATION and citing a package member / domain attribute / consumer contract — never a parallel surface, a new file, or flat spam; a `sparse`-coverage owner gets the deepest domain + package sweep. py3.15-modern only (PEP 585/604/695, `frozendict` builtin, newest payload forms). Write high-signal prose with all code backticked. Fix-in-place (read-then-extend, preserve capability).' + svyBlock(svy) + '\nReport what you collapsed (count before->after) in `collapsed` and what capability you extended (each addition + its cited source) in `extended`. Return the fix-log + residual_high — each a {files: [every repo-relative path the cross-file fix spans], claim} object for any CROSS-FILE item you surface but cannot fix from this one file (NO severity; the reconcile phase fixes all of them).'].join('\n')
const critiquePrompt = (page, svy) => [LAW, '', ULTRA, '', EXTEND, '', PATLAW, '', BOUNDARIES, '', PROSE, '', COMMENTS, '',
  'TASK: DOCTRINAL-CONFORMANCE AUDIT + CAPABILITY-COMPLETENESS + FIX IN PLACE of ' + page + '. You are an ULTRA-HARSH, UNAGREEABLE auditor: assume a violation exists in every fence until you prove otherwise, and "good enough" is rejected. Run these MECHANICAL checklists line-by-line and REPAIR every hit in place (a fix, never a ledger note):',
  '(1) COLLAPSE_SCAN — apply the move for any of the 12 signals (3+ instances makes it mandatory): sibling prefix/suffix names -> one modality-polymorphic entrypoint; same return rail differing only by arity -> input-shape discrimination; a `get`/`get_many`/`get_by_id` family -> one input-keyed entrypoint; functions differing only by a literal -> parameterize the literal as policy; a bool parameter selecting two bodies -> one derived body or policy value; a function calling exactly one other -> delete the hop; a class exposing one public method -> module function or fold-on-owner; parallel dispatch arms repeating structure -> a `frozendict` table or fold algebra; several types sharing fields for one concept -> one closed family; 3+ sibling module constants for one concept -> one `frozendict`/`StrEnum`; a wrapper renaming a package API -> use the package surface directly; the same 2-4 wrappers recurring -> one parameterized aspect factory.',
  '(2) OWNER_CHOOSER — for EVERY shape re-derive the owner from the 5 discriminants (admission, identity regime, variant arity, payload timing, openness); if it is not the discriminant-correct owner (`TypedDict`/Pydantic/`msgspec.Struct`/frozen dataclass/rich class/`StrEnum`/`Literal`/`sentinel`/`Option`/`Result`/`frozendict`/`Map`/`tuple`/`Protocol`), replace it. Kill every parallel DTO, one-field wrapper, field-rename class, tag-only shape, and `None`-as-failure.',
  '(3) KNOB_TEST — delete each parameter: if the value already encodes what it carried, it was a knob — collapse a `strict: bool`/`mode`/`batch` flag into a policy value or input-shape discriminant, and move every `timeout`/`retry`/`deadline` out of the signature into an aspect or `anyio` scope.',
  '(4) ASPECTS — every cross-cutting concern (retry/telemetry/validation/contracts/memo/registration/receipts) MUST be a signature+rail-preserving STACKED decorator that never raises into domain flow; 2-4 co-occurring wrappers collapse into one aspect factory; deterministic stacking order verified. Inline-repeated concerns and sibling helper functions are defects.',
  '(5) RAILS — narrowest carrier chosen once; the fault type is a CLOSED `Literal`/`StrEnum`/`@tagged_union` (a bare `str` fault for a multi-cause domain is a defect); accumulate-vs-abort disposition correct (`map2`/fold for independents, `bind` for dependents); NO `asyncio`, NO hand-rolled retry loop, NO `None`-as-failure, NO exception control flow in domain logic.',
  '(6) PAYLOADS/FROZENDICT/PEP — payloads are `closed=`/`extra_items=` `TypedDict` via a module-level `TypeAdapter` with `Unpack[TypedDict]` at root entrypoints; `frozendict` (builtin) owns tables/evidence (no `MappingProxyType`/dict-table/tuple-pairs); PEP 585/604/695 only, no `from __future__ import annotations`, no legacy typing; total `match` + `assert_never`.',
  '(7) CAPABILITY-COMPLETENESS — structural collapse and capability completeness are ORTHOGONAL: a fully-collapsed owner can still model a NAIVE, LIMITED slice of its concept. Verify EVERY survey gap for this page is genuinely CLOSED by an IN-PLACE extension (a case/row/field/operation on the EXISTING owner, never a parallel surface or flat appended code); any unaddressed gap, any extension bolted on as flat spam rather than a unified owner case, OR any further capability the both-tier admitted-package surface / the real domain concept / a consumer contract admits that the owner still omits is a DEFECT — close it in place now, citing its source. Reject the inverse too: a speculative or padding field with no package/domain/consumer justification is deleted.' + svyBlock(svy),
  'Also enforce both-tier `.api` maximization (a thin folder-only subset ignoring the shared rails is a defect) and prose + comment hygiene. EDIT the page to fix every hit. Report what you extended in `extended`. Return the fix-log + residual_high — each a {files: [every repo-relative path the cross-file fix spans], claim} object for any CROSS-FILE item you cannot fix here (NO severity; the reconcile phase fixes all of them).'].join('\n')
const redteamPrompt = (page, svy) => [LAW, '', ULTRA, '', EXTEND, '', PATLAW, '', BOUNDARIES, '', PROSE, '', COMMENTS, '',
  'TASK: ADVERSARIAL ARCHITECT RED-TEAM + FIX IN PLACE of ' + page + '. You are the LAST and MOST AGGRESSIVE pass: assume the author and critique missed things and that the chosen design is not the strongest until proven, with the burden of proof on the design, never on you. Open BOTH .api tiers, the sibling pages, and the operative docs/stacks/python/ pages. Attack from every direction and REPAIR every defect in place — no soft-pedalling, no could/should, a fix never a ledger.',
  'PRIMARY LENS — fundamental design, multi-faceted / multi-dimensional / multi-directional: (A) COUNTERFACTUAL on the core choice — is the owner, the algebra, and the dispatch form categorically the strongest the doctrine admits, or does a denser owner, a fold/derived-table algebra, or a DEEPER admitted-package primitive collapse the whole fence? If a fundamentally stronger design exists, rebuild to it — never defend the incumbent. (B) ANTICIPATORY_COLLAPSE — compute the DIFF OF THE NEXT FEATURE: when the next case/dimension/knob/modality/provider arrives, does it land as ONE declaration with every consumer untouched (or broken loudly at type-check)? If it would touch multiple sites, reshape so the growth axis is a case, row, policy value, or carrier swap. (C) LONG-TAIL + MULTI-DIMENSIONAL — attack every input/output/edge/failure mode (empty, singular, plural, stream, malformed, concurrent, cancelled, partial-failure, version-skew); is the accumulate-vs-abort disposition correct for the REAL boundary; are BOTH ingress AND egress parameterized so this owner sources and sinks across hundreds of apps without interior edits? (D) BOUNDARY-INTEGRITY — a concern owned twice in a runtime, a folder mixing concerns, a concern scattered across folders, or any coupling to a sibling owner\'s INTERIOR (vs its wire/seam) is a defect: fix it, or record it as a cross-file residual. (E) SURFACE-SPRAWL-IN-TIME — an admitted package whose .api exposes capability the fence re-derives by hand, flat code below the operator depth the packages reach, a phantom .api member, or a thin wrapper: collapse to package depth and verify the member exists. (F) CAPABILITY-COMPLETENESS + JUSTIFIED EXTENSION — counterfactually attack the owner for DOMAIN-COMPLETENESS independently of how collapsed it is: does the both-tier admitted-package surface, the real-world concept, or a consumer contract admit a capability this owner still OMITS (a flat membership/id set where the concept owns geometry/metrics/attributes/topology/operations; a 2-variant union where the domain has twenty; the obvious 3 fields where the concept carries fifteen)? Name it with a cite and EXTEND THE OWNER IN PLACE (a case/row/field/operation, per ANTICIPATORY_COLLAPSE) — a structurally-perfect but capability-sparse owner is a DEFECT, not a finished page; the survey map below is the floor, not the ceiling. Conversely, REJECT any extension that is flat spam, speculative, or a parallel surface — collapse it into the owner or remove it.' + svyBlock(svy),
  'ALSO — FULL COLD ADVERSARIAL RE-REVIEW (run this every time, NOT only when an architectural restructure is warranted): re-attack every conformance dimension with fresh hostile eyes, trusting nothing the prior passes claimed — the COLLAPSE_SCAN signals, OWNER_CHOOSER correctness per shape, the KNOB_TEST per param, the ASPECT taxonomy, rail + closed-fault-vocabulary discipline, capability-completeness per owner, payload/`frozendict`/PEP conformance, both-tier `.api` maximization, py3.15-modern typing, and prose/comment hygiene — and fix every defect. Even absent a structural rebuild, the fence must end objectively denser, MORE CAPABLE, more correct, and more powerful than the critique left it; if the strongest form is genuinely already present, prove it by finding nothing — never invent churn.',
  'Hold the highest bar of any stage; reject "good enough"; every defect you raise you REPAIR. Report what you extended in `extended`. Return the fix-log + residual_high — each item a {files: [every repo-relative path the cross-file fix spans], claim} object for a CROSS-FILE item you cannot fix from one file (NO severity — every finding counts equally and the reconcile phase addresses all; every single-file fix you make yourself).'].join('\n')

// --- [STAGES] ----------------------------------------------------------------------------
const STAGES = [
  { key: 'rebuild', build: authorPrompt, effort: 'max' },
  { key: 'crit', build: critiquePrompt, effort: 'xhigh' },
  { key: 'redteam', build: redteamPrompt, effort: 'max' },
]
const processPage = async (w, tag) => {
  const logs = {}
  for (const st of STAGES) {
    const r = await agent(st.build(w.page, w.svy), { label: st.key + ':' + folderOf(w.page) + ':' + subOf(w.page), phase: tag + folderOf(w.page), schema: FIXLOG_SCHEMA, effort: st.effort, stallMs: 300000 })
    if (r === null) break
    logs[st.key] = r
  }
  return { page: w.page, logs, ok: Object.keys(logs).length === STAGES.length }
}

// --- [COMPOSITION] -----------------------------------------------------------------------
phase('Discover')
const inv = await agent('List every design page under ' + SWEEP + ' — markdown specs at paths matching */.planning/**/*.md. Return each as a repo-relative path (e.g. ' + ROOT + '/<folder>/.planning/<sub>/<page>.md). Exclude IDEAS.md/TASKLOG.md/README.md/ARCHITECTURE.md. Use find; do not cd.', { label: 'discover', phase: 'Discover', schema: DISCOVERY_SCHEMA, model: 'sonnet', effort: 'low' })
const pages = ((inv && inv.pages) || []).filter(Boolean)
const total = pages.length
log('Discover under ' + SWEEP + ': ' + total + ' design pages; pooling at CAP=' + CAP)

// --- [SURVEY] -- per folder: shared owners (cross-file unification) + per-page justified capability gaps ---
phase('Survey')
const byFolder = new Map()
for (const p of pages) { const fp = folderPathOf(p); (byFolder.get(fp) || byFolder.set(fp, []).get(fp)).push(p) }
const folderPaths = [...byFolder.keys()]
const surveys = (await pool(folderPaths, CAP, (fp) => agent(surveyPrompt(fp, byFolder.get(fp)), { label: 'survey:' + (fp.split('/').pop() || fp), phase: 'Survey', schema: SURVEY_SCHEMA, effort: 'xhigh', stallMs: 300000 }))).filter(Boolean)
const surveyByPage = new Map()
for (const s of surveys) for (const pg of ((s && s.pages) || [])) surveyByPage.set(pg.page, { shared_owners: (s.shared_owners || []), coverage: pg.coverage, size: pg.size, gaps: (pg.gaps || []) })
const sparse = [...surveyByPage.values()].filter((v) => v.coverage === 'sparse').length
const gapTotal = [...surveyByPage.values()].reduce((n, v) => n + (v.gaps ? v.gaps.length : 0), 0)
log('Survey: ' + folderPaths.length + ' folders mapped; ' + sparse + ' sparse-coverage pages; ' + gapTotal + ' justified capability gaps to close in place')

phase('Rebuild')
const pending = pages.map((p) => ({ page: p, svy: surveyByPage.get(p) || null }))
const done = (await pool(pending, CAP, (w) => processPage(w, 'Rebuild-'))).filter(Boolean)

// --- [RECONCILE] -- consume the cross-FILE residuals the per-page pass deferred -----------
const RESIDUAL_FIX_SCHEMA = { type: 'object', additionalProperties: false, required: ['files', 'verdict', 'summary'], properties: { files: { type: 'array', items: { type: 'string' } }, verdict: { type: 'string', enum: ['fixed', 'clean'] }, summary: { type: 'string' } } }
const RECONCILE_VERIFY_SCHEMA = { type: 'object', additionalProperties: false, required: ['overall', 'claims'], properties: { overall: { type: 'boolean' }, claims: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['claim', 'status'], properties: { claim: { type: 'string' }, status: { type: 'string', enum: ['fixed', 'invalid', 'open'] }, evidence: { type: 'string' } } } } } }
const norm = (x, page) => typeof x === 'string' ? { files: [page], claim: x } : { files: x.files && x.files.length ? x.files : [page], claim: x.claim }
const allRes = []
for (const r of done) for (const st of ['rebuild', 'crit', 'redteam']) { const l = r.logs && r.logs[st]; if (l && l.residual_high) for (const x of l.residual_high) allRes.push(norm(x, r.page)) }
const uniq = [...new Map(allRes.map((r) => [r.files.slice().sort().join(',') + '|' + r.claim, r])).values()]
const clusters = (() => {
  const parent = new Map(); const find = (f) => { let p = f; while (parent.get(p) !== p) p = parent.get(p); return p }; const add = (f) => { if (!parent.has(f)) parent.set(f, f) }
  for (const r of uniq) { r.files.forEach(add); for (let i = 1; i < r.files.length; i++) parent.set(find(r.files[i]), find(r.files[0])) }
  const by = new Map()
  for (const r of uniq) { const root = r.files.length ? find(r.files[0]) : '__none__'; (by.get(root) || by.set(root, []).get(root)).push(r) }
  return [...by.values()]
})()
log('Rebuild: ' + done.length + '/' + total + ' pages; reconcile ' + uniq.length + ' residuals (crit+redteam, deduped) -> ' + clusters.length + ' clusters')
let reconciled = []
if (clusters.length) {
  phase('Reconcile')
  reconciled = (await pipeline(
    clusters,
    (cl) => agent([LAW, '', ULTRA, '', EXTEND, '', PATLAW, '', BOUNDARIES, '', 'TASK: RECONCILE these cross-FILE residuals the critique AND red-team passes deferred. There is NO severity — treat EVERY residual as must-address. Read EVERY listed file. For each: if it is a real cross-file defect, FIX it in place (unify the shared type/seam/rail, repair the strata/boundary issue, or extend the shared owner in place to close a capability gap that spans files), preserving all capability and regressing no file; if a residual is FACTUALLY INCORRECT or not a real defect, leave it and say why in the summary — never silently skip a real one to avoid work. Residuals:\n' + JSON.stringify(cl, null, 1)].join('\n'), { label: 'reconcile-fix', phase: 'Reconcile', schema: RESIDUAL_FIX_SCHEMA, effort: 'max', stallMs: 300000 }),
    (fix, cl, i) => fix ? agent([LAW, '', BOUNDARIES, '', 'TASK: ADVERSARIAL VERIFY, one verdict per claim. Read the named files from disk and classify each residual: status "fixed" (real defect, now genuinely resolved), "invalid" (the claim is factually wrong / not a real defect — cite why), or "open" (real defect still NOT resolved). Default to "open" on any doubt for a real-looking defect; mark "invalid" ONLY when you can show the claim is wrong. Claims:\n' + JSON.stringify(cl, null, 1) + '\nFiles the fixer touched: ' + JSON.stringify(fix.files)].join('\n'), { label: 'reconcile-verify:' + i, phase: 'Reconcile', schema: RECONCILE_VERIFY_SCHEMA, effort: 'xhigh', stallMs: 300000 }).then((v) => ({ cluster: cl, fix, verify: v })) : null,
  )).filter(Boolean)
}
const claimsAll = reconciled.flatMap((r) => (r.verify && r.verify.claims) || [])
const hard_residual = claimsAll.filter((c) => c.status === 'open').map((c) => c.claim)
const dropped = claimsAll.filter((c) => c.status === 'invalid').map((c) => c.claim)
log('Reconcile: ' + clusters.length + ' clusters; ' + hard_residual.length + ' open (hard residual), ' + dropped.length + ' dropped as invalid')
return { root: ROOT, scope: SCOPE || 'ALL', complete: done.filter((r) => r.ok).length, incomplete: done.filter((r) => !r.ok).length, total: total, sparse_pages: sparse, capability_gaps: gapTotal, clusters: clusters.length, hard_residual: hard_residual, dropped: dropped }
