<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup Label="Project References">
        <ProjectReference Include="../../../../../tools/rhino-bridge/Contract/Contract.csproj" />
        <ProjectReference Include="../../../../../tools/rhino-bridge/Supervisor/Supervisor.csproj" />
    </ItemGroup>
</Project>
