<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssayTestShell>true</AssayTestShell>
    </PropertyGroup>
    <ItemGroup Label="Project References">
        <ProjectReference Include="../../../../libs/dotnet/Rasm.AppHost/Rasm.AppHost.csproj" />
    </ItemGroup>
    <ItemGroup Label="Test Doubles">
        <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" PrivateAssets="all" />
        <PackageReference Include="NodaTime.Testing" PrivateAssets="all" />
        <PackageReference Include="Polly.Testing" PrivateAssets="all" />
    </ItemGroup>
</Project>
