"""Bring the inputs of the function-hooks plugin up to date after a Claude Code update, a server change, or a plugin edit.

The steps run in order, and the first that does not hold exits 1 with a message naming the fix: the configured MCP servers, the
Roslyn CodeLens analyzer policy, the declarations under .claude/types regenerated by a -p session with every server connected,
the Claude Code version that wrote them, the plugin typecheck and validation, the installed copy and its load under -p, and the
report of the inputs.
"""

# --- [IMPORTS] --------------------------------------------------------------------------

from collections import Counter
import os
from pathlib import Path
import re
import time

import anyio
from anyio.streams.buffered import BufferedByteReceiveStream
import cyclopts
from expression import Error, Ok, Result
import msgspec
import structlog

from eng.scripts.provision import (
    CommandFailed,
    exit_code,
    Failure as ProvisionFailure,
    message,
    PinMismatch,
    read_manifest,
    repository_root,
    run,
    run_each,
)

# --- [TYPES] ----------------------------------------------------------------------------


class ServerMissing(msgspec.Struct, frozen=True, gc=False):
    """Configured MCP server absent from the regenerated declarations."""

    server: str


class DeclarationsStale(msgspec.Struct, frozen=True, gc=False):
    """Declaration file older than the -p session that was to regenerate it."""

    path: Path


class VersionMismatch(msgspec.Struct, frozen=True, gc=False):
    """Declarations written by one Claude Code version while the binary on PATH reports another."""

    declared: str
    installed: str


class HookNotLoaded(msgspec.Struct, frozen=True, gc=False):
    """Debug file of the final -p session without the line saying the hooks module loaded."""

    path: Path


class PluginNotInstalled(msgspec.Struct, frozen=True, gc=False):
    """Plugin list after the install without a project-scope copy of the plugin."""

    plugin: str


class ServerPending(msgspec.Struct, frozen=True, gc=False):
    """Configured MCP servers the init event of the -p session reports in a status other than connected."""

    servers: tuple[str, ...]


class TrustPolicy(msgspec.Struct, frozen=True, gc=False):
    """Roslyn CodeLens trust file absent or holding an analyzerPolicy other than all, the value found or None when it did not read."""

    path: Path
    found: str | None


type Failure = (
    ProvisionFailure | ServerMissing | DeclarationsStale | VersionMismatch | HookNotLoaded | PluginNotInstalled | ServerPending | TrustPolicy
)


class Report(msgspec.Struct, frozen=True, gc=False):
    """Inputs of the plugin after the run."""

    version: str
    plugin: str
    cached: str
    flag: tuple[str, ...]
    marketplace: str
    servers: dict[str, int]
    checks: tuple[str, ...]


class _Servers(msgspec.Struct, frozen=True, gc=False):
    """`mcpServers` table of .mcp.json and of ~/.claude.json, each server definition undecoded."""

    servers: dict[str, msgspec.Raw] = msgspec.field(name="mcpServers", default={})


class _Settings(msgspec.Struct, frozen=True, gc=False):
    """Fields of a settings.json the harness reads, the flag, the marketplaces, and the enabled plugins."""

    env: dict[str, str] = {}
    marketplaces: dict[str, dict[str, dict[str, str]]] = msgspec.field(name="extraKnownMarketplaces", default={})
    plugins: dict[str, bool] = msgspec.field(name="enabledPlugins", default={})


class _Installed(msgspec.Struct, frozen=True, gc=False):
    """Row of `claude plugin list --json`."""

    id: str
    version: str
    scope: str


class _ServerStatus(msgspec.Struct, frozen=True, gc=False):
    """Row of `mcp_servers` in the init event."""

    name: str
    status: str


class _Event(msgspec.Struct, frozen=True, gc=False):
    """Fields of a stream-json event line the harness reads, the init event carries the server statuses and the others carry null."""

    type: str
    subtype: str = ""
    servers: list[_ServerStatus] | None = msgspec.field(name="mcp_servers", default=None)


class _Trust(msgspec.Struct, frozen=True, gc=False):
    """Field of the Roslyn CodeLens trust file the harness reads."""

    analyzer_policy: str = msgspec.field(name="analyzerPolicy", default="")


# --- [CONSTANTS] ------------------------------------------------------------------------

_PLUGIN = "function-hooks"
_MARKETPLACE = "rasm"
_PLUGIN_ID = f"{_PLUGIN}@{_MARKETPLACE}"
_EVENT_BYTES = 1 << 20  # Longest stream-json line read before the init event, the init line itself measures about 34 KB
_TOOL = re.compile(r"mcp__([\w-]+?)__([\w-]+)")
_WRITTEN_BY = re.compile(r"// Written by Claude Code (\S+)\.")

_log = structlog.get_logger(__name__)
_app = cyclopts.App(name="harness")

# --- [OPERATIONS] -----------------------------------------------------------------------


def _configured(root: Path) -> Result[frozenset[str], PinMismatch]:
    """Return the MCP servers .mcp.json configures, the repository's own set; a user-level server in ~/.claude.json is the person's."""
    return read_manifest(root / ".mcp.json", _Servers).map(lambda project: frozenset(project.servers))


async def _init(stdout: BufferedByteReceiveStream, argv: tuple[str, ...], required: frozenset[str]) -> Result[None, CommandFailed | ServerPending]:
    """Read stream-json events up to the init event and check it reports every required server connected."""
    try:
        while True:
            if (
                event := msgspec.json.decode(await stdout.receive_until(b"\n", _EVENT_BYTES), type=_Event)
            ).type == "system" and event.subtype == "init":
                break
    except (anyio.IncompleteRead, anyio.DelimiterNotFound, msgspec.DecodeError) as error:
        return Error(CommandFailed(argv, f"sent no init event, {error!r}"))
    match sorted(required.difference(server.name for server in event.servers or () if server.status == "connected")):
        case []:
            return Ok(None)
        case pending:
            return Error(ServerPending(tuple(pending)))


async def _session(root: Path, types: Path, required: frozenset[str]) -> Result[None, CommandFailed | ServerPending]:
    """Run the -p session that regenerates the declarations under the blocking connect and fail on a required server the init event reports pending."""
    # The session loads .mcp.json alone (--strict-mcp-config), a user-level server in ~/.claude.json is the person's and can never connect
    argv = (
        "claude",
        "-p",
        "--strict-mcp-config",
        "--mcp-config",
        str(root / ".mcp.json"),
        "--input-format",
        "stream-json",
        "--output-format",
        "stream-json",
        "--verbose",
    )
    # MCP_CONNECTION_NONBLOCKING=0 holds startup on the whole server batch before the init event (Agent SDK mcp#connection-timing),
    # and MCP_CONNECT_TIMEOUT_MS bounds that hold at the startup timeout MCP_TIMEOUT documents (30 s), the batch measured at 8.5 s
    env = {**os.environ, "MCP_CONNECTION_NONBLOCKING": "0", "MCP_CONNECT_TIMEOUT_MS": "30000"}
    try:
        process = await anyio.open_process(argv, cwd=root, env=env, stderr=None)
    except OSError as error:
        return Error(CommandFailed(argv, str(error)))
    async with process:
        match process.stdin, process.stdout:
            case (None, _) | (_, None):
                return Error(CommandFailed(argv, "started without a stdin and a stdout pipe"))
            case (stdin, stdout):
                pass
        events = BufferedByteReceiveStream(stdout)
        # The init event follows the first input under --input-format stream-json, so the command goes first and the blocking connect
        # (MCP_CONNECTION_NONBLOCKING=0) still holds the session until every server settled before init reports their statuses
        await stdin.send(msgspec.json.encode({"type": "user", "message": {"role": "user", "content": f"/plugin-types {types}"}}) + b"\n")
        await stdin.aclose()
        match await _init(events, argv, required):
            case Result(tag="error", error=failure):
                return Error(failure)
            case Result():
                pass
        async for _ in events:  # Drained to EOF so the child never blocks on a full pipe
            pass
        status = await process.wait()
    return Ok(None) if status == 0 else Error(CommandFailed(argv, f"exit status {status}"))


async def _declare(root: Path, types: Path, configured: frozenset[str]) -> Result[dict[str, int], Failure]:
    """Regenerate the declarations and return the tool count per server after checking every configured server is declared."""
    started = time.time()
    match await _session(root, types, configured):
        case Result(tag="error", error=failure):
            return Error(failure)
        case Result():
            pass
    mcp = types / "claude-code-mcp.d.ts"
    match [path for path in (types / "claude-code.d.ts", mcp) if not path.is_file() or path.stat().st_mtime < started]:
        case [stale, *_]:
            return Error(DeclarationsStale(stale))
        case _:
            pass
    counts = Counter(server for server, _ in set(_TOOL.findall(mcp.read_text())))
    match sorted(configured - counts.keys()):
        case [missing, *_]:
            return Error(ServerMissing(missing))
        case _:
            return Ok(dict(sorted(counts.items())))


async def _version(root: Path, types: Path) -> Result[str, Failure]:
    """Return the version claude --version reports after checking the declarations were written by it."""
    header = (types / "claude-code.d.ts").read_text().partition("\n")[0]
    found = _WRITTEN_BY.match(header)
    declared = header if found is None else found[1]
    match await run(["claude", "--version"], root, capture=True):
        case Result(tag="error", error=failure):
            return Error(failure)
        case Result(ok=text) if text.partition(" ")[0] != declared:
            return Error(VersionMismatch(declared, text.strip()))
        case Result(ok=text):
            return Ok(text.partition(" ")[0])


async def _loaded(root: Path) -> Result[None, Failure]:
    """Run one -p session against the installed copy and check its debug file says the hooks module loaded."""
    debug = root / ".artifacts" / "harness" / "debug.txt"
    debug.parent.mkdir(parents=True, exist_ok=True)
    debug.unlink(missing_ok=True)
    match await run(["claude", "--debug-file", str(debug), "-p", "Reply with the single word ok."], root, capture=True):
        case Result(tag="error", error=failure):
            return Error(failure)
        case Result() if debug.is_file() and f"hooks module {_PLUGIN} loaded" in debug.read_text():
            return Ok(None)
        case Result():
            return Error(HookNotLoaded(debug))


async def _cached(root: Path) -> Result[str, Failure]:
    """Return the version of the project-scope installed copy of the plugin."""
    match await run(["claude", "plugin", "list", "--json"], root, capture=True):
        case Result(tag="error", error=failure):
            return Error(failure)
        case Result(ok=text):
            pass
    try:
        rows = msgspec.json.decode(text, type=list[_Installed])
    except msgspec.DecodeError as error:
        return Error(PinMismatch("Output of claude plugin list --json", f"does not decode, {error}"))
    match [row.version for row in rows if row.id == _PLUGIN_ID and row.scope == "project"]:
        case [version, *_]:
            return Ok(version)
        case _:
            return Error(PluginNotInstalled(_PLUGIN_ID))


def _settings(root: Path) -> Result[tuple[tuple[str, ...], str], Failure]:
    """Return the settings files that set the flag and the marketplace path, after checking the project enables the plugin."""
    project, user = root / ".claude" / "settings.json", Path.home() / ".claude" / "settings.json"
    user_read: Result[_Settings, PinMismatch] = read_manifest(user, _Settings) if user.is_file() else Ok(_Settings())
    match read_manifest(project, _Settings).map2(user_read, lambda a, b: (a, b)):
        case Result(tag="error", error=failure):
            return Error(failure)
        case Result(ok=(settings, user_settings)):
            pass
    flag = tuple(
        str(path) for path, values in ((project, settings), (user, user_settings)) if values.env.get("CLAUDE_CODE_ENABLE_FUNCTION_HOOKS") == "1"
    )
    match settings.marketplaces.get(_MARKETPLACE, {}).get("source", {}).get("path"), settings.plugins.get(_PLUGIN_ID):
        case (None, _):
            return Error(PinMismatch(f"Settings {project}", f"name no {_MARKETPLACE} marketplace with a source path under extraKnownMarketplaces"))
        case (_, None | False):
            return Error(PinMismatch(f"Settings {project}", f"do not enable {_PLUGIN_ID} under enabledPlugins"))
        case (marketplace, True):
            return Ok((flag, marketplace))


def _policy(path: Path) -> Result[None, Failure]:
    """Check the Roslyn CodeLens trust file sets analyzerPolicy all, the policy that loads the package analyzers the plugin's diagnostics read."""
    match read_manifest(path, _Trust):
        case Result(tag="error"):
            return Error(TrustPolicy(path, None))
        case Result(ok=_Trust(analyzer_policy="all")):
            return Ok(None)
        case Result(ok=trust):
            return Error(TrustPolicy(path, trust.analyzer_policy))


async def _harness(start: Path) -> Result[Report, Failure]:
    """Run each step in order from the repository root and return the report of the plugin's inputs."""
    match repository_root(start):
        case Result(tag="error", error=root_error):
            return Error(root_error)
        case Result(ok=root):
            types, plugin = root / ".claude" / "types", Path(".claude") / "plugins" / _PLUGIN
    match _configured(root):
        case Result(tag="error", error=config_error):
            return Error(config_error)
        case Result(ok=configured):
            pass
    match _policy(Path.home() / "Library" / "Application Support" / "roslyn-codelens" / "trust.json"):
        case Result(tag="error", error=policy_error):
            return Error(policy_error)
        case Result():
            pass
    match await _declare(root, types, configured):
        case Result(tag="error", error=declare_error):
            return Error(declare_error)
        case Result(ok=servers):
            pass
    match await _version(root, types):
        case Result(tag="error", error=version_error):
            return Error(version_error)
        case Result(ok=version):
            pass
    checks = (
        ("pnpm", "exec", "nx", "run", f"{_PLUGIN}:typecheck"),
        ("claude", "plugin", "validate", str(plugin)),
        # An installed plugin keeps its cached copy under the same version key, the uninstall makes the install copy the tree again
        ("claude", "plugin", "uninstall", _PLUGIN_ID, "--scope", "project"),
        ("claude", "plugin", "install", _PLUGIN_ID, "--scope", "project"),
    )
    match await run_each(checks, root):
        case Result(tag="error", error=check_error):
            return Error(check_error)
        case Result():
            pass
    match await _loaded(root):
        case Result(tag="error", error=load_error):
            return Error(load_error)
        case Result():
            pass
    return (await _cached(root)).map2(
        _settings(root),
        lambda cached, inputs: Report(version, _PLUGIN_ID, cached, inputs[0], inputs[1], servers, tuple(" ".join(check) for check in checks)),
    )


# --- [CLI] ------------------------------------------------------------------------------


def _message(failure: Failure) -> str:
    """Render a failure as one sentence naming what happened, the cause, and the action."""
    match failure:
        case ServerMissing(server=server):
            return (
                f"Server {server} is configured and absent from claude-code-mcp.d.ts, "
                "run /mcp in an interactive session until it shows connected, then run nx run rasm:harness again"
            )
        case DeclarationsStale(path=path):
            return f"{path} is older than the -p session that was to regenerate it, run claude -p '/plugin-types .claude/types' by hand and read its output"
        case VersionMismatch(declared=declared, installed=installed):
            return (
                f"claude-code.d.ts was written by Claude Code {declared} and claude --version reports {installed}, "
                "keep one claude binary on PATH and run nx run rasm:harness again"
            )
        case HookNotLoaded(path=path):
            return (
                f"The installed plugin did not load under -p, {path} holds no line saying the hooks module loaded, read it for the loader's refusal"
            )
        case PluginNotInstalled(plugin=plugin):
            return f"claude plugin list names no project-scope {plugin}, run claude plugin install {plugin} --scope project and read its output"
        case ServerPending(servers=servers):
            return (
                f"The init event of the -p session reports {', '.join(servers)} not connected, "
                "run /mcp in an interactive session until each shows connected, then run nx run rasm:harness again"
            )
        case TrustPolicy(path=path, found=found):
            entry = '{ "version": 1, "trustedRoots": [], "trustedSolutions": [], "analyzerPolicy": "all" }'
            state = "does not read" if found is None else f"holds analyzerPolicy {found!r}"
            return f"{path} {state} and the plugin's roslyn diagnostics need the package analyzers only analyzerPolicy all loads, write {entry} to it"
        case _:
            return message(failure)


def _report(report: Report) -> None:
    _log.info("harness", **msgspec.structs.asdict(report))


_app.result_action = (exit_code(_report, _message), "sys_exit")


@_app.default
def main() -> Result[Report, Failure]:
    """Bring the plugin inputs up to date, the first step that does not hold exits 1 with a message naming the fix.

    The steps: read the configured MCP servers, regenerate .claude/types with every server connected, check the Claude Code
    version that wrote them, typecheck and validate the plugin, install it at project scope and prove its load under -p, and
    report the inputs in one row.

    Returns:
        The report of the inputs, or the failure of the first step that did not hold.
    """
    return anyio.run(_harness, Path(__file__).resolve())


if __name__ == "__main__":
    _app()

# --- [EXPORTS] --------------------------------------------------------------------------

__all__ = [
    "Failure",
    "ServerMissing",
    "DeclarationsStale",
    "VersionMismatch",
    "HookNotLoaded",
    "PluginNotInstalled",
    "ServerPending",
    "TrustPolicy",
    "Report",
    "main",
]
