<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Z3 .NET bindings compiled AnyCPU from the pinned z3 source archive</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageId>Rasm.Z3</PackageId>
        <AssemblyName>Microsoft.Z3</AssemblyName>
        <IncludeBuildOutput>true</IncludeBuildOutput>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>8.0</LangVersion>
    </PropertyGroup>
</Project>
