<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <ItemGroup Label="Test Runtime">
        <PackageReference Include="coverlet.MTP" />
        <PackageReference Include="CsCheck" />
        <PackageReference Include="LanguageExt.Core" />
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
        <PackageReference Include="Microsoft.Testing.Extensions.CrashDump" />
        <PackageReference Include="Microsoft.Testing.Extensions.HangDump" />
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup Label="Project References">
        <PackageReference Include="Thinktecture.Runtime.Extensions" />
        <ProjectReference Include="../../../../../tools/rhino-bridge/Contract/Contract.csproj" />
        <ProjectReference Include="../../../../../tools/rhino-bridge/Supervisor/Supervisor.csproj" />
        <ProjectReference Include="../../../testkit/Rasm.TestKit.csproj" />
    </ItemGroup>
</Project>
