using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Foundation.CSharp.Analyzers.Generators;

// --- [GENERATOR] --------------------------------------------------------------

[Generator]
public sealed class UnionOpsGenerator : IIncrementalGenerator {
    private const string GenerateUnionOpsMetadataName = "Rasm.Domain.GenerateUnionOpsAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValuesProvider<(INamedTypeSymbol? Union, Compilation Compilation)> targets =
            context.SyntaxProvider.ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: GenerateUnionOpsMetadataName,
                predicate: static (syntax, _) => syntax is TypeDeclarationSyntax,
                transform: static (ctx, _) => ((INamedTypeSymbol?)ctx.TargetSymbol, ctx.SemanticModel.Compilation));

        context.RegisterSourceOutput(
            source: targets.Where(static pair => pair.Union is not null),
            action: static (ctx, pair) => Emit(ctx: ctx, unionType: pair.Union!, compilation: pair.Compilation));
    }

    private static void Emit(SourceProductionContext ctx, INamedTypeSymbol unionType, Compilation compilation) {
        ImmutableArray<INamedTypeSymbol> cases = UnionCases(compilation: compilation, unionType: unionType);
        if (cases.IsEmpty) {
            return;
        }

        List<string> lines =
        [
            "// <auto-generated />",
            $"namespace {unionType.ContainingNamespace.ToDisplayString()};",
            string.Empty,
            $"{DeclarationKeyword(type: unionType)} {unionType.Name}",
            "{",
        ];
        foreach (INamedTypeSymbol caseType in cases) {
            lines.Add($"    {DeclarationKeyword(type: caseType)} {caseType.Name}");
            lines.Add("    {");
            lines.Add($"        internal static readonly global::Rasm.Domain.Op SelfOp = global::Rasm.Domain.Op.Of(name: nameof({caseType.Name}));");
            lines.Add("    }");
            lines.Add(string.Empty);
        }
        lines.Add("}");

        ctx.AddSource(
            hintName: $"{unionType.Name}.UnionOps.g.cs",
            sourceText: SourceText.From(string.Join(separator: "\n", values: lines), Encoding.UTF8));
    }

    private static ImmutableArray<INamedTypeSymbol> UnionCases(Compilation compilation, INamedTypeSymbol unionType) =>
        [
            .. unionType.GetTypeMembers()
                .Where(caseType => SymbolEqualityComparer.Default.Equals(caseType.BaseType, unionType) && caseType.IsRecord && caseType.IsSealed)
                .Concat(compilation.GlobalNamespace.GetNamespaceMembers().SelectMany(namespaceSymbol => NamespaceUnionCases(namespaceSymbol: namespaceSymbol, unionType: unionType))),
        ];

    private static IEnumerable<INamedTypeSymbol> NamespaceUnionCases(INamespaceSymbol namespaceSymbol, INamedTypeSymbol unionType) =>
        namespaceSymbol.GetTypeMembers()
            .Where(caseType => SymbolEqualityComparer.Default.Equals(caseType.BaseType, unionType) && caseType.IsRecord && caseType.IsSealed)
            .Concat(namespaceSymbol.GetNamespaceMembers().SelectMany(child => NamespaceUnionCases(namespaceSymbol: child, unionType: unionType)));

    private static string DeclarationKeyword(INamedTypeSymbol type) =>
        (type.IsRecord, type.TypeKind, type.IsAbstract, type.IsSealed, type.IsReadOnly) switch {
            (true, _, true, _, _) => "abstract partial record",
            (true, _, _, _, _) => "partial record",
            (_, TypeKind.Struct, _, _, true) => "readonly partial struct",
            (_, TypeKind.Struct, _, _, _) => "partial struct",
            (_, _, true, true, _) => "abstract sealed partial class",
            (_, _, true, _, _) => "abstract partial class",
            (_, _, _, true, _) => "sealed partial class",
            _ => "partial class",
        };
}
