using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Rasm.Csp.Generators;

// --- [TYPES] ---------------------------------------------------------------------------

internal readonly record struct UnionCase(string Keyword, string Name);

internal readonly record struct EquatableArray<T>(ImmutableArray<T> Values) where T : IEquatable<T> {
    public bool IsEmpty => Values.IsDefaultOrEmpty;

    public bool Equals(EquatableArray<T> other) => Values.AsSpan().SequenceEqual(other.Values.AsSpan());

    public override int GetHashCode() =>
        Values.IsDefaultOrEmpty ? 0 : Values.Aggregate(seed: 17, static (acc, value) => unchecked((acc * 31) + value.GetHashCode()));
}

internal sealed record UnionOpsModel(string Namespace, string Keyword, string Name, EquatableArray<UnionCase> Cases);

// --- [SERVICES] ------------------------------------------------------------------------

/// <summary>
/// Emits a nested <c>SelfOp</c> provenance anchor (<c>global::Rasm.Domain.Op</c>) for every sealed
/// record case of a type carrying <c>Rasm.Domain.GenerateUnionOpsAttribute</c>. Caseless targets emit nothing.
/// </summary>
[Generator]
public sealed class UnionOpsGenerator : IIncrementalGenerator {
    private const string GenerateUnionOpsMetadataName = "Rasm.Domain.GenerateUnionOpsAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValuesProvider<UnionOpsModel> models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: GenerateUnionOpsMetadataName,
                predicate: static (syntax, _) => syntax is TypeDeclarationSyntax,
                transform: static (ctx, _) => ctx.TargetSymbol is INamedTypeSymbol union ? Capture(union: union) : null)
            .Where(static model => model is not null)
            .Select(static (model, _) => model!);

        context.RegisterSourceOutput(
            source: models,
            action: static (ctx, model) => ctx.AddSource(hintName: model.Name + ".UnionOps.g.cs", sourceText: Render(model: model)));
    }

    private static UnionOpsModel? Capture(INamedTypeSymbol union) {
        ImmutableArray<UnionCase> cases =
        [
            .. union.GetTypeMembers()
                .Where(candidate => candidate.IsRecord && candidate.IsSealed && SymbolEqualityComparer.Default.Equals(candidate.BaseType, union))
                .Select(candidate => new UnionCase(Keyword: DeclarationKeyword(type: candidate), Name: candidate.Name)),
        ];
        return cases.IsEmpty
            ? null
            : new UnionOpsModel(
                Namespace: union.ContainingNamespace.ToDisplayString(),
                Keyword: DeclarationKeyword(type: union),
                Name: union.Name,
                Cases: new EquatableArray<UnionCase>(Values: cases));
    }

    private static string DeclarationKeyword(INamedTypeSymbol type) =>
        (type.IsRecord, type.TypeKind, type.IsAbstract, type.IsSealed, type.IsReadOnly) switch {
            (true, _, true, _, _) => "abstract partial record",
            (true, _, _, _, _) => "partial record",
            (_, TypeKind.Struct, _, _, true) => "readonly partial struct",
            (_, TypeKind.Struct, _, _, _) => "partial struct",
            (_, _, true, true, _) => "abstract sealed partial class",
            (_, _, true, _, _) => "abstract partial class",
            (_, _, _, true, _) => "sealed partial class",
            _ => "partial class",
        };

    // Rendering is the documented Roslyn-component boundary: IndentedTextWriter is stateful by
    // design, and a statement loop is the honest emission form here.
    private static SourceText Render(UnionOpsModel model) {
        using StringWriter buffer = new(CultureInfo.InvariantCulture) { NewLine = "\n" };
        using IndentedTextWriter writer = new(buffer, tabString: "    ") { NewLine = "\n" };
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("namespace " + model.Namespace + ";");
        writer.WriteLine();
        writer.WriteLine(model.Keyword + " " + model.Name);
        writer.WriteLine("{");
        writer.Indent++;
        for (int index = 0; index < model.Cases.Values.Length; index++) {
            UnionCase unionCase = model.Cases.Values[index];
            if (index > 0) {
                writer.WriteLineNoTabs(string.Empty);
            }

            writer.WriteLine(unionCase.Keyword + " " + unionCase.Name);
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("internal static readonly global::Rasm.Domain.Op SelfOp = global::Rasm.Domain.Op.Of(name: nameof(" + unionCase.Name + "));");
            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.Indent--;
        writer.WriteLine("}");
        writer.Flush();
        return SourceText.From(text: buffer.ToString(), encoding: Encoding.UTF8);
    }
}
