(function(){var o=[];
function names(obj,label){try{var pr=obj.reflect.properties;var m=[];for(var j=0;j<pr.length;j++){var pn=pr[j].name;if(pn!="__proto__")m.push(pn);}m.sort();o.push(label+"("+m.length+")="+m.join(","));}catch(ex){o.push(label+"=ERR "+ex.message);}}
function methods(obj,label){try{var pr=obj.reflect.methods;var m=[];for(var j=0;j<pr.length;j++){var pn=pr[j].name;if(pn!="__proto__")m.push(pn);}m.sort();o.push(label+"M("+m.length+")="+m.join(","));}catch(ex){o.push(label+"M=ERR "+ex.message);}}
var ps=app.paragraphStyles.item(0);names(ps,"ParagraphStyle");names(app.characterStyles.item(0),"CharacterStyle");
var os=app.objectStyles.item(0);names(os,"ObjectStyle");
try{names(os.textFramePreferences,"OS.textFramePreferences");}catch(e){o.push("OS.tfp ERR "+e.message);}
try{names(os.anchoredObjectSettings,"OS.anchoredObjectSettings");}catch(e){o.push("OS.aos ERR "+e.message);}
try{names(os.frameFittingOptions,"OS.frameFittingOptions");}catch(e){o.push("OS.ffo ERR "+e.message);}
try{names(os.textWrapPreferences,"OS.textWrapPreferences");}catch(e){o.push("OS.twp ERR "+e.message);}
try{names(os.storyPreferences,"OS.storyPreferences");}catch(e){o.push("OS.sp ERR "+e.message);}
try{names(os.baselineFrameGridOptions,"OS.baselineFrameGridOptions");}catch(e){o.push("OS.bfg ERR "+e.message);}
names(app.cellStyles.item(0),"CellStyle");names(app.tableStyles.item(0),"TableStyle");
names(app.textDefaults,"TextDefault");names(app.textPreferences,"TextPreference");names(app.textFramePreferences,"TextFramePreference");
names(app.gridPreferences,"GridPreference");names(app.marginPreferences,"MarginPreference");names(app.documentPreferences,"DocumentPreference");names(app.viewPreferences,"ViewPreference");
names(app.clipboardPreferences,"ClipboardPreference");names(app.pasteboardPreferences,"PasteboardPreference");names(app.smartGuidePreferences,"SmartGuidePreference");names(app.guidePreferences,"GuidePreference");
names(app.gpuPerformancePreferences,"GpuPerformancePreference");names(app.linkingPreferences,"LinkingPreference");names(app.storyPreferences,"StoryPreference");names(app.transformPreferences,"TransformPreference");
names(app.footnoteOptions,"FootnoteOption");try{names(app.endnoteOptions,"EndnoteOption");}catch(e){o.push("EndnoteOption ERR "+e.message);}
names(app.pdfExportPresets.item(0),"PDFExportPreset");names(app.preflightOptions,"PreflightOption");
names(app.textVariables.item(0),"TextVariable");try{names(app.textVariables.itemByName("Running Header").variableOptions,"MatchParagraphStylePreference");}catch(e){o.push("MPSP ERR "+e.message);}
try{names(app.textVariables.itemByName("Last Page Number").variableOptions,"PageNumberVariablePreference");}catch(e){o.push("PNVP ERR "+e.message);}
try{names(app.textVariables.itemByName("File Name").variableOptions,"FileNameVariablePreference");}catch(e){o.push("FNVP ERR "+e.message);}
try{names(app.textVariables.itemByName("Output Date").variableOptions,"DateVariablePreference");}catch(e){o.push("DVP ERR "+e.message);}
names(app.colorSettings,"ColorSettings");names(app.displayPerformancePreferences,"DisplayPerformancePreference");
try{names(app.displaySettings.item(0),"DisplaySetting");o.push("displaySettingsCount="+app.displaySettings.length);}catch(e){o.push("DisplaySetting ERR "+e.message);}
names(app.dictionaryPreferences,"DictionaryPreference");names(app.spellPreferences,"SpellPreference");names(app.autoCorrectPreferences,"AutoCorrectPreference");names(app.galleyPreferences,"GalleyPreference");names(app.notePreferences,"NotePreference");names(app.trackChangesPreferences,"TrackChangesPreference");names(app.textEditingPreferences,"TextEditingPreference");
try{names(app.crossReferenceFormats.item(0),"CrossReferenceFormat");o.push("xrefCount="+app.crossReferenceFormats.length);}catch(e){o.push("XREF ERR "+e.message);}
try{names(app.languagesWithVendors.item("English: USA"),"LanguageWithVendors");}catch(e){o.push("LWV ERR "+e.message);}
try{names(app.preflightProfiles.item(0),"PreflightProfile");names(app.preflightProfiles.item(0).preflightProfileRules.item(0),"PreflightProfileRule");}catch(e){o.push("PP ERR "+e.message);}
try{names(app.swatches.item(0),"Swatch");}catch(e){}
methods(app,"Application");methods(app.preflightProfiles.item(0),"PreflightProfile");methods(ps,"ParagraphStyle");
var tries=["TocNumberedParagraphs","TOCNumberedParagraphs","TocStyleNumberedParagraphs","PreflightProfilePolicy","PreflightProfileOptions","PreflightProfilePolicyOptions","PreflightPolicyOptions","HyperlinkAppearanceHighlight","GridAlignment","LeadingModel","Locale","FeatureSetOptions","ObjectStyleContentEffectsCategorySettings","TocNumberedParagraphsOptions"];
for(var i=0;i<tries.length;i++){try{var e=eval(tries[i]);var pr=e.reflect.properties;var m=[];for(var j=0;j<pr.length;j++){if(pr[j].name!="__proto__")m.push(pr[j].name);}o.push("ENUM "+tries[i]+"="+m.join(","));}catch(ex){o.push("ENUM "+tries[i]+"=MISSING");}}
o.push("whenScaling="+String(app.transformPreferences.whenScaling));o.push("textDefaults.diacriticPosition="+String(app.textDefaults.diacriticPosition)+" kashidas="+String(app.textDefaults.kashidas)+" kashidaWidth="+app.textDefaults.paragraphKashidaWidth+" digits="+String(app.textDefaults.digitsType)+" pj="+String(app.textDefaults.paragraphJustification)+" hyphenWeight="+app.textDefaults.hyphenWeight+" hz="+app.textDefaults.hyphenationZone+" composer="+app.textDefaults.composer+" singleWord="+String(app.textDefaults.singleWordJustification)+" ligatures="+app.textDefaults.ligatures+" calt="+app.textDefaults.otfContextualAlternate+" fig="+String(app.textDefaults.otfFigureStyle)+" keep="+app.textDefaults.keepLinesTogether+"/"+app.textDefaults.keepFirstLines+"/"+app.textDefaults.keepLastLines+"/"+app.textDefaults.keepWithNext+" ws="+app.textDefaults.minimumWordSpacing+"/"+app.textDefaults.desiredWordSpacing+"/"+app.textDefaults.maximumWordSpacing+" ls="+app.textDefaults.minimumLetterSpacing+"/"+app.textDefaults.desiredLetterSpacing+"/"+app.textDefaults.maximumLetterSpacing+" gs="+app.textDefaults.minimumGlyphScaling+"/"+app.textDefaults.desiredGlyphScaling+"/"+app.textDefaults.maximumGlyphScaling+" hyph="+app.textDefaults.hyphenation+"/"+app.textDefaults.hyphenateWordsLongerThan+"/"+app.textDefaults.hyphenateAfterFirst+"/"+app.textDefaults.hyphenateBeforeLast+"/"+app.textDefaults.hyphenateLadderLimit+"/"+app.textDefaults.hyphenateCapitalizedWords+"/"+app.textDefaults.hyphenateLastWord+"/"+app.textDefaults.hyphenateAcrossColumns);
o.push("textPrefs: leadInc="+app.textPreferences.leadingKeyIncrement+" bsInc="+app.textPreferences.baselineShiftKeyIncrement+" kernInc="+app.textPreferences.kerningKeyIncrement+" quotes="+app.textPreferences.typographersQuotes+" opt="+app.textPreferences.useOpticalSize+" paraLead="+app.textPreferences.useParagraphLeading+" harf="+app.textPreferences.shapeIndicAndLatinWithHarbuzz+" stylePrev="+app.textPreferences.enableStylePreviewMode+" hk="+app.textPreferences.highlightKeeps+" hj="+app.textPreferences.highlightHjViolations+" hcs="+app.textPreferences.highlightCustomSpacing+" hsf="+app.textPreferences.highlightSubstitutedFonts+" hsg="+app.textPreferences.highlightSubstitutedGlyphs+" jtw="+app.textPreferences.justifyTextWraps+" abut="+app.textPreferences.abutTextToTextWrap+" z="+app.textPreferences.zOrderTextWrap+" str="+app.textPreferences.smartTextReflow+" addPages="+String(app.textPreferences.addPages)+" limit="+app.textPreferences.limitToMasterTextFrames+" pfs="+app.textPreferences.preserveFacingPageSpreads+" del="+app.textPreferences.deleteEmptyPages+" link="+app.textPreferences.linkTextFilesWhenImporting+" sup="+app.textPreferences.superscriptSize+"/"+app.textPreferences.superscriptPosition+" sub="+app.textPreferences.subscriptSize+"/"+app.textPreferences.subscriptPosition+" sc="+app.textPreferences.smallCap);
o.push("view: h="+String(app.viewPreferences.horizontalMeasurementUnits)+" v="+String(app.viewPreferences.verticalMeasurementUnits)+" origin="+String(app.viewPreferences.rulerOrigin)+" stroke="+String(app.viewPreferences.strokeMeasurementUnits)+" typo="+String(app.viewPreferences.typographicMeasurementUnits)+" ts="+String(app.viewPreferences.textSizeMeasurementUnits)+" print="+String(app.viewPreferences.printDialogMeasurementUnits)+" ppi="+app.viewPreferences.pointsPerInch+" cursor="+app.viewPreferences.cursorKeyIncrement+" snap="+app.viewPreferences.guideSnaptoZone+" rulers="+app.viewPreferences.showRulers);
o.push("grid: start="+app.gridPreferences.baselineStart+" div="+app.gridPreferences.baselineDivision+" rel="+String(app.gridPreferences.baselineGridRelativeOption)+" shown="+app.gridPreferences.baselineGridShown+" thr="+app.gridPreferences.baselineViewThreshold+" color="+String(app.gridPreferences.baselineColor)+" hgd="+app.gridPreferences.horizontalGridlineDivision+"/"+app.gridPreferences.horizontalGridSubdivision+" vgd="+app.gridPreferences.verticalGridlineDivision+"/"+app.gridPreferences.verticalGridSubdivision+" dgs="+app.gridPreferences.documentGridShown+" snap="+app.gridPreferences.documentGridSnapto+" back="+app.gridPreferences.gridsInBack);
o.push("margins: "+app.marginPreferences.top+"/"+app.marginPreferences.bottom+"/"+app.marginPreferences.left+"/"+app.marginPreferences.right+" cols="+app.marginPreferences.columnCount+" gutter="+app.marginPreferences.columnGutter);
o.push("docprefs: w="+app.documentPreferences.pageWidth+" h="+app.documentPreferences.pageHeight+" facing="+app.documentPreferences.facingPages+" intent="+String(app.documentPreferences.intent)+" bleedU="+app.documentPreferences.documentBleedUniformSize+" bleedT="+app.documentPreferences.documentBleedTopOffset+" slugT="+app.documentPreferences.slugTopOffset+" ptf="+app.documentPreferences.createPrimaryTextFrame+" bind="+String(app.documentPreferences.pageBinding)+" opBlack="+app.documentPreferences.overprintBlack);
o.push("tfp: fbo="+String(app.textFramePreferences.firstBaselineOffset)+" inset="+app.textFramePreferences.insetSpacing+" cols="+app.textFramePreferences.textColumnCount+" gutter="+app.textFramePreferences.textColumnGutter+" auto="+String(app.textFramePreferences.autoSizingType));
o.push("story: oma="+app.storyPreferences.opticalMarginAlignment+" size="+app.storyPreferences.opticalMarginSize+" dir="+String(app.storyPreferences.storyDirection));
o.push("guides: inBack="+app.guidePreferences.guidesInBack+" thr="+app.guidePreferences.rulerGuidesViewThreshold+" color="+String(app.guidePreferences.rulerGuidesColor));
o.push("smart: "+app.smartGuidePreferences.enabled+"/"+app.smartGuidePreferences.alignToObjectEdges+"/"+app.smartGuidePreferences.alignToObjectCenter+"/"+app.smartGuidePreferences.smartDimensions+"/"+app.smartGuidePreferences.smartSpacing);
o.push("pb: prev="+String(app.pasteboardPreferences.previewBackgroundColor)+" bleed="+String(app.pasteboardPreferences.bleedGuideColor)+" slug="+String(app.pasteboardPreferences.slugGuideColor)+" margins="+app.pasteboardPreferences.pasteboardMargins+" match="+app.pasteboardPreferences.matchPreviewBackgroundToThemeColor);
o.push("clip: pdfPaste="+app.clipboardPreferences.preferPDFWhenPasting+" copyPDF="+app.clipboardPreferences.copyPDFToClipboard+" preserve="+app.clipboardPreferences.preservePdfClipboardAtQuit+" styled="+app.clipboardPreferences.preferStyledTextWhenPasting+" layers="+app.clipboardPreferences.pasteRemembersLayers+" showPaste="+app.clipboardPreferences.showPasteOptions+" autoStyle="+app.clipboardPreferences.showAutoStyleOption);
o.push("gpu: "+app.gpuPerformancePreferences.enableGpuPerformance+"/"+app.gpuPerformancePreferences.enableAnimatedZoom);
o.push("link: "+app.linkingPreferences.checkLinksAtOpen+"/"+app.linkingPreferences.findMissingLinksAtOpen);
o.push("cs: "+app.colorSettings.cmsSettings+" | "+app.colorSettings.workingSpaceRGB+" | "+app.colorSettings.workingSpaceCMYK+" | "+String(app.colorSettings.rgbPolicy)+" | "+String(app.colorSettings.cmykPolicy)+" | "+app.colorSettings.engine+" | "+String(app.colorSettings.intent)+" | bpc="+app.colorSettings.useBPC+" | ask="+app.colorSettings.mismatchAskWhenOpening+"/"+app.colorSettings.mismatchAskWhenPasting+"/"+app.colorSettings.missingAskWhenOpening+" | idealB="+app.colorSettings.idealizedBlackToScreen+"/"+app.colorSettings.idealizedBlackToExport);
o.push("blend="+String(app.transparencyPreferences.blendingSpace));
o.push("disp: "+String(app.displayPerformancePreferences.defaultDisplaySettings)+"/"+app.displayPerformancePreferences.persistLocalSettings+"/"+app.displayPerformancePreferences.ignoreLocalSettings);
try{var ds=app.displaySettings.everyItem().getElements();var dd=[];for(var k=0;k<ds.length;k++)dd.push(ds[k].name+":greek="+ds[k].greekBelow);o.push("displaySettings: "+dd.join(" | "));}catch(e){o.push("displaySettings ERR "+e.message);}
o.push("dict: "+String(app.dictionaryPreferences.composition)+"/"+app.dictionaryPreferences.mergeUserDictionary+"/"+app.dictionaryPreferences.recomposeWhenChanged+" enUSvendors="+app.languagesWithVendors.item("English: USA").hyphenationVendor+"/"+app.languagesWithVendors.item("English: USA").spellingVendor);
o.push("spell: "+app.spellPreferences.dynamicSpellCheck+"/"+app.spellPreferences.checkMisspelledWords+"/"+app.spellPreferences.checkRepeatedWords+"/"+app.spellPreferences.checkCapitalizedWords+"/"+app.spellPreferences.checkCapitalizedSentences);
o.push("autocorrect: "+app.autoCorrectPreferences.autoCorrect+"/"+app.autoCorrectPreferences.autoCorrectCapitalizationErrors);
o.push("galley: "+app.galleyPreferences.displayFont+"/"+app.galleyPreferences.displayFontSize+"/"+String(app.galleyPreferences.textColor)+"/"+String(app.galleyPreferences.backgroundColor)+"/"+String(app.galleyPreferences.antiAliasType));
o.push("tep: "+app.textEditingPreferences.tripleClickSelectsLine+"/"+app.textEditingPreferences.smartCutAndPaste+"/"+app.textEditingPreferences.dragAndDropTextInLayout+"/"+app.textEditingPreferences.allowDragAndDropTextInStory);
o.push("transform: adjE="+app.transformPreferences.adjustEffectsWhenScaling+" adjS="+app.transformPreferences.adjustStrokeWeightWhenScaling+" dims="+app.transformPreferences.dimensionsIncludeStrokeWeight);
o.push("swatches="+app.swatches.everyItem().name.join("|"));
o.push("pdfPresets="+app.pdfExportPresets.everyItem().name.join("|"));o.push("docPresets="+app.documentPresets.everyItem().name.join("|"));o.push("preflight="+app.preflightProfiles.everyItem().name.join("|"));
o.push("xrefs="+app.crossReferenceFormats.everyItem().name.join("|"));o.push("textVars="+app.textVariables.everyItem().name.join("|"));o.push("numLists="+app.numberingLists.everyItem().name.join("|"));
try{o.push("conditions="+app.conditions.length+" sets="+app.conditionSets.length);}catch(e){o.push("cond ERR "+e.message);}
o.push("basicPara: "+app.paragraphStyles.itemByName("[Basic Paragraph]").appliedFont.name+" "+app.paragraphStyles.itemByName("[Basic Paragraph]").pointSize+"/"+String(app.paragraphStyles.itemByName("[Basic Paragraph]").leading));
return o.join("\n");})()
