import re
p="../gui-indesign.md"; doc=open(p,encoding="utf-8").read()
def rep(old,new,count=1):
    global doc
    assert doc.count(old)==count,(old[:90],doc.count(old)); doc=doc.replace(old,new)
rep("| `build_template` readback equals `styles-graph.json`; the proof steps of [09] rows 12–13 and [10] U1, U2, U5, U6 pass                                                                                                       |",
    "| `build_template` readback equals `styles-graph.json`; the [09] rows 12–13 readbacks equal the live probe results of [10] rows 15–24                                                                                          |")
rep("the non-ME build's application of the value is [10] row U2 |","the non-ME build applies it: a frame with the style reads `storyDirection RIGHT_TO_LEFT_DIRECTION`, a later direct write on the story wins and is not flagged as an override, `applyObjectStyle(style, true)` restores it (live scratch document, [10] row 18) |")
rep("| `app.exportPresets(ExportPresetFormat.PDF_EXPORT_PRESETS_FORMAT, File)`; whether it yields a `.joboptions` the Distiller reads is [10] row U10 |",
    "| Define dialog Save As… per preset for the `.joboptions` Distiller and Illustrator read; `app.exportPresets(ExportPresetFormat.PDF_EXPORT_PRESETS_FORMAT, File)` writes the InDesign container of every preset ([07] PDF presets row 03) |")
rep("| I4 RTL round trip on a scratch document: `find_key_strings(\"Adobe World-Ready Paragraph Composer\")` = `[\"$ID/HL Composer Optyca\"]`; `apply_rtl_defaults{scope: 'document'}`; read every property; `apply_rtl_styles` for `Body Fa`, `Body Ar` readback; `doc.changeComposer()` presence and effect; `digitsType FARSI_DIGITS` vs `FULL_FARSI_DIGITS` on `۰۱۲۳ 0123` captured; seven `paragraphJustification` and six `diacriticPosition` members captured; `RIGHT_TO_LEFT_DIRECTION` and `rightToLeftDirection` spellings; `objectStyle.storyPreferences.storyDirection` applied; ZWNJ kept through `changeText`; refused properties marked in `roles.json` and `styles-graph.json` before I2 |",
    "| I4 RTL round trip through the bridge on a scratch document (the ExtendScript results of [10] rows 15–24 are the expected values): `find_key_strings(\"Adobe World-Ready Paragraph Composer\")` = `[\"$ID/HL Composer Optyca\"]`; `apply_rtl_defaults{scope: 'document'}`; read every property; `apply_rtl_styles` for `Body Fa`, `Body Ar` readback with `appliedLanguage` assigned as strings; UXP spellings of the enumerators; ZWNJ kept through `changeText`; the seven `paragraphJustification` members rendered once; refused properties marked in `roles.json` and `styles-graph.json` before I2 |")
# [10] rewrite
a=doc.index("## [10]-[VERIFIED_VERSUS_UNVERIFIED]"); b=doc.index("## [11]-[SOURCES]",a)
new10='''## [10]-[VERIFIED_VERSUS_UNVERIFIED]

Live probes of 2026-09-11 ran read-only `do script … language javascript` on a hidden scratch document (`app.documents.add(false)`, closed with `SaveOptions.NO`, `app.documents.length` 0 after each), with JPEG and preset exports into `probe-gui/live/` only (`pA.out`, `pB.out`, `pC.out`, `pB.jpg`, `digits-crop.png`, `presets-test.joboptions`, `usersettings-test`, `sr23-1.pdf`).

| [INDEX] | [CLAIM]                                                                                                              | [STATUS]                 | [EVIDENCE]                                                                                                                                     |
| :-----: | :------------------------------------------------------------------------------------------------------------------- | :----------------------- | :--------------------------------------------------------------------------------------------------------------------------------------------- |
|  [01]   | 21.6.0.58 has no toolbar editor; layout is `toolsPanel` only                                                         | verified                 | Adobe toolbox pages (2026-06-02, 2024-09-08); `app.menuActions` (4,843) read live, no `Toolbar` action, the composer actions present; `ToolsPanelOptions` three members read live |
|  [02]   | `contextBarVisible`, `applicationBarShown`, `toolsPanel`, `panelTabHeightPreference`, `uiBrightnessPreference` exist on `generalPreferences`; `applicationBarShown` is read-only | verified   | `reflect.properties` read live (probe-gui/r2.out); assignment raises error 30474                                                              |
|  [03]   | `Adobe World-Ready Paragraph Composer` and `Adobe World-Ready Single-line Composer` are menu actions on this build; the key string is `$ID/HL Composer Optyca`; the composer string assigns and reads back on a style | verified | `app.menuActions`, `app.findKeyStrings` (r1.out); `pfa.composer` readback (pB.out)                                                          |
|  [04]   | `app.languagesWithVendors` has 61 entries, `[No Language]`, `Arabic`, `Hebrew`, `English: USA` among them, no Persian; `[No Language]` assigns only as a string or `item(0)` | verified | `everyItem().name` (r1.out); `item`/`itemByName` invalid, string assignment reads back (pB.out)                                                |
|  [05]   | Window, File, Edit, Type, Object, View, Help, Plug-Ins menus and the Window submenus of 21.6.0.58; every command in the `Default Menu Set` list exists | verified | System Events reads (probe-gui/win.out)                                                                                                        |
|  [06]   | current values of every DOM preference row in [05] and the text-default table                                        | verified                 | live reads (r2.out, props.out); `whenScaling` already `APPLY_TO_CONTENT`; `otfFigureStyle` default `DEFAULT_VALUE`                             |
|  [07]   | every property name in [06] and [07] exists on its live class; every enumerator is a member of the live enumeration  | verified                 | `reflect.properties` dump and enumeration dump (props.out, enums.out) checked mechanically; the mismatches are corrected in place (traps row 24) |
|  [08]   | `[Basic]` preflight rule ids (38), flags, and data field names; three-rule `Default Preflight` (Codex)               | verified                 | `app-preferences.json` dump; the Drive `Default Preflight.idpp` snippet                                                                        |
|  [09]   | AI plug-ins live inside the sealed bundle; removal breaks the signature                                               | verified                 | `fd`, `codesign -dvv`, `CodeResources`; Apple Code Signing Guide                                                                               |
|  [10]   | Kelman geometry: top margin = baseline − f, gutters `2L − f`, 0.749 f-ratio for NHG Text Pro 55                      | verified                 | seven IDML reads (kelman-idml.txt) and fontTools on the CoreSync `NHaasGroteskTXPro-55Rg` (font-metrics.txt)                                   |
|  [11]   | every catalogue row closes under the [07] formulas                                                                   | verified                 | recomputed (splice07.py and the B-series run); the `typographic-grid` `grid` target reproduces them within 0.001 pt before I3                   |
|  [12]   | panel leaf names and ids of [03]; the control bar closed today; the toolbar leaf `size-variant="vertical-narrow"`   | verified                 | `Essentials_CurrentWorkspace.xml`, `Start_CurrentWorkspace.xml`, the eleven preset workspace files                                            |
|  [13]   | `app.loadSwatches(File)`, `app.loadPreflightProfile(File)`, `app.exportPresets(format, File)`, `app.importFile(format, File)`, `app.applyMenuCustomization(name)`, `app.saveFindChangeQuery(name, mode)` | verified | UXP `a/application` page fetched 2026-09-11; present in `app.reflect.methods`                                                                 |
|  [14]   | `DisplaySetting.greekBelow` exists; `app.displaySettings` order is Fast, Typical, High Quality                        | verified                 | `raster` read live: `GRAY_OUT`, `PROXY`, `HIGH_RESOLUTION` (r5.out)                                                                            |
|  [15]   | a nested style beats a GREP style on the same attribute; the earlier GREP row beats a later one                      | verified                 | pA.out `U1_*`: nested Italic over GREP Bold → `Italic`; Italic-then-Bold → `Italic`; Bold-then-Italic → `Bold`                                  |
|  [16]   | `tabList = []` is accepted; object arrays with `CHARACTER_ALIGN` and `alignmentCharacter` read back                  | verified                 | pA.out `U9_emptyArray`, pB.out `U9_objects`, `U9_charAlign`                                                                                     |
|  [17]   | `hyphenWeight` is a short integer 0–10; 11 is rejected                                                               | verified                 | pA.out `U8`                                                                                                                                    |
|  [18]   | the object style applies `storyDirection`; a direct story write wins afterwards; `applyObjectStyle(style, true)` restores | verified             | pA.out `U2_*`, `U21_*`                                                                                                                         |
|  [19]   | auto row height is 15n + 1 with 15 pt leading, `LEADING_OFFSET`, zero vertical insets; `autoGrow=false; height` fixes it | verified            | pA.out `U5_*` (16, 31; fixed 15; a two-line row forced to 15 oversets)                                                                          |
|  [20]   | `RIGHT_JUSTIFIED` ends an RTL paragraph flush right; Arabic with `DEFAULT_KASHIDAS` width 2 likewise                 | verified                 | pB.out `U6`: the last line's `horizontalOffset` equals the frame's right edge (360)                                                            |
|  [21]   | `FARSI_DIGITS` and `FULL_FARSI_DIGITS` render identically; `digitsType` converts Western digits only                | verified                 | pB.jpg, digits-crop.png (Adobe Arabic)                                                                                                         |
|  [22]   | `doc.changeComposer()` exists on a document and converts existing text to the World-Ready composer, not styles or text defaults | verified          | pB.out `U19_effect`                                                                                                                            |
|  [23]   | `ParagraphDirectionOptions.rightToLeftDirection` and `RIGHT_TO_LEFT_DIRECTION` both resolve in ExtendScript; this file writes UPPER_SNAKE | verified    | pA.out `U20_camel`                                                                                                                             |
|  [24]   | `createGuides(…, fitMargins=true)` places row guides at margin top + k × (row + gutter); f-guides come from `guides.add`; a `CAP_HEIGHT` first baseline at the f-guide reads 44.936 unsnapped and 45.000 snapped | verified | pA.out `U22`, `U28_*`                                                                                                                          |
|  [25]   | `exportPresets(PDF_EXPORT_PRESETS_FORMAT)` writes one InDesign container (`InDnPdfS`) embedding every preset's joboptions text; the Define dialog writes per-preset `.joboptions` | verified | pC.out, `file` and `strings` on presets-test.joboptions                                                                                      |
|  [26]   | `app.exportSettings(File)` writes the user-settings bundle headlessly as a SQLite 3 database (`Metadata`, `FileStore`); the dialog's default name is `IDSettings_…` | verified | pC.out, `sqlite3` on usersettings-test; Adobe export-and-import-user-settings (2026-06-02)                                                     |
|  [27]   | a saved workspace writes `<name>.xml` and `<name>_CurrentWorkspace.xml` in `en_US/Workspaces/`; a saved menu set writes into `en_US/Menu Sets/` | verified | LinkedIn Learning InDesign Secrets 203, CreativePro 2010-01-14, Adobe community 2025-08-08; Adobe preferences and support file locations (2026-06-02); the plug-in string table |
|  [28]   | ERDC/ITL SR-23-1: margin ≥ 3/16 in, 1½ in modules, vertical title block in the right margin, production data area outside the drawing border upper right, text heights 3/32, 1/8, 3/16 in, line spacing ½ text height | verified | the PDF read on 2026-09-11 (probe-gui/live/sr23-1.pdf, §2.1.1–2.1.6, Figures 2-1, 2-6, §5)                                                     |
|  [29]   | the Generative AI preference pane holds the two alt-text switches                                                   | verified (Adobe); Beta pane recorded at [09] row 04 | Adobe, generate alt text for images (2026-02-03); both are `generalPreferences` properties                                            |
|  [30]   | typefool templates on Drive                                                                                          | absent                   | `fd -i typefool` over the whole Drive returned nothing on 2026-09-11; re-download is a cloud-library job (owned purchase, account access granted) |
|  [31]   | `app.importSettings(File)` argument form                                                                            | not run                  | it replaces the settings and restarts InDesign; the export side is [26]                                                                        |
|  [32]   | exact toolbox slot order in the double column; the Beta's Generative AI pane beyond the two switches; the title-block strip width on the Center's border file | recorded at the pass | screenshots at [09] rows 04 and 06 (the main window is off-screen today, `kCGWindowIsOnscreen false`, so `screencapture -l` cannot image it without fronting); the Center's border sheet at cadbimcenter.erdc.dren.mil |

'''
doc=doc[:a]+new10+doc[b:]
# [11] sources add
m=re.search(r"^\|  \[53\]   \| UXP DOM pages.*$",doc,re.M); assert m
add='''
|  [54]   | Live probes 2026-09-11 on hidden scratch documents (`probe-gui/pA.js`, `pB.js`, `pC.js` → `live/pA.out`, `pB.out`, `pC.out`, `pB.jpg`, `digits-crop.png`, `presets-test.joboptions`, `docpresets-test`, `usersettings-test`); the app-bar AX dump (`live/ax-before.txt`); window list through `CGWindowListCopyWindowInfo` (`scratchpad/wl.swift`)                                                        | 2026-09-11                      |
|  [55]   | https://www.wbdg.org/FFC/AECCAD/ERDC_ITL_SR_23_1_2023.pdf (ERDC/ITL SR-23-1, A/E/C Graphics Standard Release 2.2, August 2023; `probe-gui/live/sr23-1.pdf`)                                                                                                                                                                                                                                      | 2023-08; read 2026-09-11        |
|  [56]   | https://helpx.adobe.com/sg/indesign/using/alt-text-generation.html (Preferences > Generative AI: the two alt-text switches)                                                                                                                                                                                                                                                                         | 2026-02-03                      |
|  [57]   | https://helpx.adobe.com/indesign/desktop/troubleshoot/settings-interface-and-feature-issues/preferences-support-file-locations.html (Roaming Data folder: Workspaces, Menu Sets, Find-Change Queries, InDesign Defaults)                                                                                                                                                                             | 2026-06-02                      |
|  [58]   | https://www.linkedin.com/learning/indesign-secrets/203-sharing-custom-workspaces (`EPUB.xml` and `EPUB_CurrentWorkspace.xml`); https://creativepro.com/clean-up-in-aisle-cs4-resetting-workspaces/; https://community.adobe.com/questions-671/workspaces-aren-t-synced-so-where-are-they-stored-under-windows-and-mac-os-897127; https://graphicdesign.stackexchange.com/questions/31235 (`Workspaces/GLS.xml`) | 2011-08-25; 2010-01-14; 2025-08-08; undated |
|  [59]   | https://helpx.adobe.com/indesign/desktop/generative-ai-features/generative-ai-faq.html; https://helpx.adobe.com/indesign/desktop/generative-ai-features/gen-ai-features-overview.html                                                                                                                                                                                                              | 2026-06-18; 2026-06-09          |'''
doc=doc[:m.end()]+add+doc[m.end():]
# [12] rows
rep("the I4 readback table (U1, U2, U5, U6, U18–U21) attached to roles.json before I2`","the I4 readback table (gui-indesign.md [10] rows 15–24 as expected values) attached to roles.json before I2`")
rep("diacriticPosition OPENTYPE_POSITION_FROM_BASELINE (the host default; not OPENTYPE_POSITION); FARSI_DIGITS vs FULL_FARSI_DIGITS compared in I4` |",
    "diacriticPosition OPENTYPE_POSITION_FROM_BASELINE (the host default; not OPENTYPE_POSITION); appliedLanguage assigned as the string \"[No Language]\" (item(\"[No Language]\") resolves to nothing on 21.6.0.58); FARSI_DIGITS and FULL_FARSI_DIGITS render identically and digitsType converts Western digits only (read live 2026-09-11)` |")
# [13]
rep("| 25 rows, each `pref`, `panel`, `menu`, `bundle` (untouched, signed), or `bar` (recorded)                                                                                 | [05] AI table              | menus read; panels absent; Generative AI pane screenshot                                            |",
    "| 25 rows, each `pref`, `panel`, `menu`, `bundle` (untouched, signed), or `bar` (`applicationBarShown` read-only, AX-listed, recorded)                                     | [05] AI table              | menus read; panels absent; the two Generative AI preferences read back; pane screenshot             |")
open(p,"w",encoding="utf-8").write(doc)
bad=0
for block in re.split(r"\n\s*\n",doc):
    lines=[l for l in block.split("\n") if l.startswith("|")]
    if len(lines)<3: continue
    n=lines[0].count("|")
    for l in lines[2:]:
        if l.replace("\\|","").count("|")!=n: bad+=1; print("PIPE MISMATCH:",l[:100])
print("mismatches",bad)
