import re
p="../gui-indesign.md"
doc=open(p,encoding="utf-8").read()
def splice(doc,a_marker,b_marker,new):
    a=doc.index(a_marker); b=doc.index(b_marker,a); return doc[:a]+new+doc[b:]
def rep(old,new,count=1):
    global doc
    assert doc.count(old)==count, (old[:80], doc.count(old))
    doc=doc.replace(old,new)

# intro ratios
rep("ratios as data: H1 = 25.5/30, H2 = 19.125/22.5, H3 = 12.75/15, Title = 38.25/45, Display = 51/60. Every value is a DOM property name from the UXP reference (`p/paragraph-style`, `c/character-style`, `o/object-style`, `a/anchored-object-setting`, `t/table-style`, `c/cell-style`, `n/nested-style`, `n/nested-grep-style`, `t/text-variable`, `t/toc-style`, `f/footnote-option`, `e/endnote-option`, `c/condition`, `c/condition-set`, `s/section`) or the live `ParagraphStyle.reflect.properties` read on 21.6.0.58. Measurements are unit strings.",
"ratios as data: H1 = 25.5/30, H2 = 19.125/22.5, Heading (the third level) = 12.75/15, Title = 38.25/45, Display = 51/60. Every property name below was checked on 2026-09-11 against the live `reflect.properties` of `ParagraphStyle`, `CharacterStyle`, `ObjectStyle` (and its `textFramePreferences`, `anchoredObjectSettings`, `frameFittingOptions`, `textWrapPreferences`, `storyPreferences`, `baselineFrameGridOptions`), `CellStyle`, `TableStyle`, `FootnoteOption`, `EndnoteOption`, `TextVariable` option objects, and `PDFExportPreset` on 21.6.0.58 (probe-gui/props.out), every enumerator against the live enumeration dump (probe-gui/enums.out), and the UXP reference pages `t/table-style`, `r/row`, `h/hyperlink`, `p/preflight-option`, `t/toc-style`, `a/application` fetched the same day. Measurements are unit strings.")

# object styles table
a=doc.index("Object styles:\n"); b=doc.index("Table and cell styles.",a)
new_obj='''Object styles (9 named; every category name is a live `ObjectStyle.enable*` property):

| [INDEX] | [NAME]               | [BASED ON]           | [ENABLED CATEGORIES] | [PROPERTIES] |
| :-----: | :------------------- | :------------------- | :------------------- | :----------- |
|  [01]   | Text Frame           | `[None]`             | `enableFill` `enableStroke` `enableTextFrameGeneralOptions` `enableTextFrameBaselineOptions` `enableStoryOptions` `enableParagraphStyle` `enableTextFrameAutoSizingOptions` `enableTextWrapAndOthers` | `fillColor="None"` `strokeColor="None"` `textFramePreferences.insetSpacing=["0pt","0pt","0pt","0pt"]` `textFramePreferences.firstBaselineOffset=FirstBaseline.CAP_HEIGHT` `textFramePreferences.minimumFirstBaselineOffset="0pt"` `textFramePreferences.verticalJustification=VerticalJustification.TOP_ALIGN` `textFramePreferences.textColumnCount=1` `textFramePreferences.textColumnGutter="15pt"` `textFramePreferences.autoSizingType=AutoSizingTypeEnum.OFF` `textFramePreferences.ignoreWrap=false` `baselineFrameGridOptions.useCustomBaselineFrameGrid=false` `storyPreferences.opticalMarginAlignment=true` `storyPreferences.opticalMarginSize="12.75pt"` `storyPreferences.storyDirection=StoryDirectionOptions.LEFT_TO_RIGHT_DIRECTION` `appliedParagraphStyle="Body"` `applyNextParagraphStyle=false` `textWrapPreferences.textWrapMode=TextWrapModes.NONE` |
|  [02]   | Text Frame Fa        | Text Frame           | + `enableStoryOptions` | `storyPreferences.storyDirection=StoryDirectionOptions.RIGHT_TO_LEFT_DIRECTION` `storyPreferences.opticalMarginAlignment=false` `appliedParagraphStyle="Body Fa"`; the object style carries story direction (`ObjectStyle.storyPreferences`), not table direction, page binding, paragraph direction, or digits (those live on Table, Document, paragraph style); the non-ME build's application of the value is [10] row U2 |
|  [03]   | Figure               | `[None]`             | `enableFill` `enableStroke` `enableFrameFittingOptions` `enableStrokeAndCornerOptions` `enableTextWrapAndOthers` | `fillColor="None"` `strokeColor="None"` `frameFittingOptions.fittingOnEmptyFrame=EmptyFrameFittingOptions.PROPORTIONALLY` `frameFittingOptions.autoFit=false` `topLeftCornerOption=CornerOptions.NONE` (all four) `textWrapPreferences.textWrapMode=TextWrapModes.BOUNDING_BOX_TEXT_WRAP` `textWrapPreferences.textWrapOffset=["0pt","15pt","15pt","15pt"]` |
|  [04]   | Caption              | Text Frame           | + `enableTextFrameAutoSizingOptions` `enableParagraphStyle` `enableAnchoredObjectOptions` | `appliedParagraphStyle="Caption"` `textFramePreferences.firstBaselineOffset=FirstBaseline.LEADING_OFFSET` `textFramePreferences.autoSizingType=AutoSizingTypeEnum.HEIGHT_ONLY` `textFramePreferences.autoSizingReferencePoint=AutoSizingReferenceEnum.TOP_LEFT_POINT` `textFramePreferences.useNoLineBreaksForAutoSizing=false` `baselineFrameGridOptions.useCustomBaselineFrameGrid=true` `baselineFrameGridOptions.baselineFrameGridRelativeOption=BaselineFrameGridRelativeOption.TOP_OF_FRAME` `baselineFrameGridOptions.startingOffsetForBaselineFrameGrid="11.25pt"` `baselineFrameGridOptions.baselineFrameGridIncrement="11.25pt"` `anchoredObjectSettings.anchoredPosition=AnchorPosition.ABOVE_LINE` `anchorPoint=AnchorPoint.TOP_LEFT_ANCHOR` `horizontalAlignment=HorizontalAlignment.TEXT_ALIGN` `verticalAlignment=VerticalAlignment.TOP_ALIGN` `spineRelative=false` `anchorSpaceAbove="0pt"` `anchorYoffset="0pt"` `lockPosition=true`; the anchored category acts only on an anchored frame, so the same style serves the deck's free-standing caption frames; the body line after an anchored caption snaps back to the grid through `alignToBaseline` |
|  [05]   | Sidebar              | Text Frame           | + `enableAnchoredObjectOptions` `enableTextWrapAndOthers` `enableParagraphStyle` | `appliedParagraphStyle="Body Small"` `fillColor="Black"` `fillTint=6` `textFramePreferences.insetSpacing=["15pt","15pt","15pt","15pt"]` `textFramePreferences.firstBaselineOffset=FirstBaseline.LEADING_OFFSET` `baselineFrameGridOptions.useCustomBaselineFrameGrid=true` `baselineFrameGridRelativeOption=BaselineFrameGridRelativeOption.TOP_OF_FRAME` `startingOffsetForBaselineFrameGrid="15pt"` `baselineFrameGridIncrement="11.25pt"` `textWrapPreferences.textWrapMode=TextWrapModes.BOUNDING_BOX_TEXT_WRAP` `textWrapOffset=["15pt","15pt","15pt","15pt"]` `anchoredObjectSettings.anchoredPosition=AnchorPosition.ANCHORED` `spineRelative=true` `anchorPoint=AnchorPoint.TOP_RIGHT_ANCHOR` `horizontalReferencePoint=AnchoredRelativeTo.PAGE_MARGINS` `horizontalAlignment=HorizontalAlignment.RIGHT_ALIGN` `verticalReferencePoint=VerticallyRelativeTo.LINE_BASELINE` `verticalAlignment=VerticalAlignment.TOP_ALIGN` `anchorXoffset="0pt"` `anchorYoffset="0pt"` `pinPosition=true` |
|  [06]   | Table Frame          | Text Frame           | same                 | `textFramePreferences.firstBaselineOffset=FirstBaseline.LEADING_OFFSET` `textFramePreferences.autoSizingType=AutoSizingTypeEnum.HEIGHT_ONLY` `textFramePreferences.autoSizingReferencePoint=AutoSizingReferenceEnum.TOP_LEFT_POINT` `storyPreferences.opticalMarginAlignment=false` `appliedParagraphStyle="Table Body"` |
|  [07]   | Form Field           | `[None]`             | `enableFill` `enableStroke` `enableStrokeAndCornerOptions` `enableTextFrameGeneralOptions` | `fillColor="Paper"` `strokeColor="Black"` `strokeWeight="0.5pt"` `strokeAlignment=StrokeAlignment.INSIDE_ALIGNMENT` `topLeftCornerOption=CornerOptions.NONE` (all four) `textFramePreferences.insetSpacing=["3pt","5pt","3pt","5pt"]` `textFramePreferences.verticalJustification=VerticalJustification.CENTER_ALIGN` |
|  [08]   | Button               | Form Field           | + `enableParagraphStyle` | `fillColor="Accent"` `strokeColor="None"` `topLeftCornerOption=CornerOptions.ROUNDED_CORNER` `topLeftCornerRadius="3pt"` (all four) `appliedParagraphStyle="Form Label"` |
|  [09]   | Field                | `[None]`             | `enableFill` `enableStroke` | `fillColor="Field"` `strokeColor="None"`, no corner effect; the color blocks on the `Fields` layer (Kelman's full-page and band rectangles), filled `Ink` for the deck's dark variants |
|  [10]   | `[Basic Text Frame]`, `[Basic Graphics Frame]` | —          | —                    | untouched; Object Styles panel menu `Default Text Frame Style` → `Text Frame`, `Default Graphics Frame Style` → `Figure` (Adobe object-styles page, 2025-10-27) |

'''
doc=doc[:a]+new_obj+doc[b:]

# table and cell block
a=doc.index("Table and cell styles."); b=doc.index("Keep, H&J, and OpenType per role:",a)
new_tbl='''Table and cell styles. Rows sit on the module when a one-line row measures one module: table paragraph styles at 15 pt leading, cell `firstBaselineOffset=LEADING_OFFSET`, vertical insets 0, horizontal insets 5, table text `alignToBaseline=false`, the `Table Frame` starting on a grid line; whether InDesign's auto row height adds the last line's descent is [10] row U5, and when it does the table build fixes each row with `row.autoGrow=false; row.height="<lines × 15>pt"` (Row properties `autoGrow`, `height`, `minimumHeight`, `maximumHeight` on the UXP `r/row` page); 3 pt vertical insets (the Codex value) would put a one-line row at 21 pt, so they are gone. Row strokes separate rows; no alternating fill (one mechanism per job).

| [INDEX] | [STYLE]         | [BASED ON]         | [PROPERTIES] |
| :-----: | :-------------- | :----------------- | :----------- |
|  [01]   | Table (table)   | `[No Table Style]` | `headerRegionCellStyle="Header"` `bodyRegionCellStyle="Body"` `footerRegionCellStyle="Total"` `leftColumnRegionCellStyle="Body"` `rightColumnRegionCellStyle="Body"` `topBorderStrokeWeight="0.5pt"` `topBorderStrokeColor="Black"` `bottomBorderStrokeWeight="0.5pt"` `bottomBorderStrokeColor="Black"` `leftBorderStrokeWeight="0pt"` `rightBorderStrokeWeight="0pt"` `startRowStrokeCount=1` `startRowStrokeWeight="0.25pt"` `startRowStrokeColor="Black"` `startRowStrokeTint=40` `endRowStrokeCount=1` `endRowStrokeWeight="0.25pt"` `endRowStrokeColor="Black"` `endRowStrokeTint=40` `startColumnStrokeCount=0` `endColumnStrokeCount=0` `startRowFillCount=0` `endRowFillCount=0` `spaceBefore="0pt"` `spaceAfter="15pt"` `strokeOrder=StrokeOrderTypes.ROW_ON_TOP` `textTopInset="0pt"` `textBottomInset="0pt"` `textLeftInset="5pt"` `textRightInset="5pt"` |
|  [02]   | Body (cell)     | `[None]`           | `appliedParagraphStyle="Table Body"` `textTopInset="0pt"` `textBottomInset="0pt"` `textLeftInset="5pt"` `textRightInset="5pt"` `verticalJustification=VerticalJustification.TOP_ALIGN` `firstBaselineOffset=FirstBaseline.LEADING_OFFSET` `minimumFirstBaselineOffset="0pt"` `fillColor="None"` `topEdgeStrokeWeight="0pt"` `bottomEdgeStrokeWeight="0pt"` `leftEdgeStrokeWeight="0pt"` `rightEdgeStrokeWeight="0pt"` `clipContentToTextCell=false` |
|  [03]   | Header (cell)   | Body               | `appliedParagraphStyle="Table Header"` `bottomEdgeStrokeWeight="0.5pt"` `bottomEdgeStrokeColor="Black"` `verticalJustification=VerticalJustification.BOTTOM_ALIGN` |
|  [04]   | Numeric (cell)  | Body               | `appliedParagraphStyle="Table Numeric"` |
|  [05]   | Total (cell)    | Numeric            | `appliedParagraphStyle="Table Total"` `topEdgeStrokeWeight="0.5pt"` `topEdgeStrokeColor="Black"` |
|  [06]   | per table       | —                  | `table.headerRowCount=1` `table.breakHeaders=HeaderFooterBreakTypes.ONCE_PER_TEXT_FRAME` `table.skipFirstHeader=false` (Table properties, not style properties); RTL tables `table.tableDirection=TableDirectionOptions.RIGHT_TO_LEFT_DIRECTION` |

'''
doc=doc[:a]+new_tbl+doc[b:]

# keep table
a=doc.index("Keep, H&J, and OpenType per role:"); b=doc.index("Persian and Arabic roles in full:",a)
new_keep='''Keep, H&J, and OpenType per role:

| [INDEX] | [ROLE]                                                   | [KEEP WITH NEXT] | [KEEP LINES / FIRST / LAST] | [KEEP ALL] | [START]   | [HYPHENATION]                                        | [JUSTIFICATION]                 | [FIGURES]                              | [LIG / DLIG / CALT] | [CAPS]           |
| :-----: | :------------------------------------------------------- | :--------------- | :-------------------------- | :--------- | :-------- | :--------------------------------------------------- | :------------------------------ | :------------------------------------- | :------------------ | :--------------- |
|  [01]   | Base                                                     | 0                | true / 2 / 2                | false      | ANYWHERE  | false                                                | LEFT_ALIGN                      | PROPORTIONAL_LINING                    | t / f / t           | NORMAL           |
|  [02]   | Body, Body First, Body Listed, Body Small, Note          | 0                | true / 2 / 2                | false      | ANYWHERE  | true: 6/3/3, ladder 2, no caps, no last word, no across columns | LEFT_ALIGN           | PROPORTIONAL_LINING                    | t / f / t           | NORMAL           |
|  [03]   | Heading, H1, H2, Contents Title, Subtitle                | 2                | true                        | true       | ANYWHERE  | false                                                | LEFT_ALIGN                      | PROPORTIONAL_LINING                    | t / f / t           | NORMAL           |
|  [04]   | Display, Title, White/Title                              | 2                | true                        | true       | ANYWHERE  | false                                                | LEFT_ALIGN, `ignoreEdgeAlignment` | PROPORTIONAL_LINING                  | t / f / t           | NORMAL           |
|  [05]   | Caption, Table Caption (keepWithNext 1)                  | 0 / 1            | true / 2 / 2                | true       | ANYWHERE  | false                                                | LEFT_ALIGN                      | PROPORTIONAL_LINING                    | t / f / t           | NORMAL           |
|  [06]   | Running Header, Section Indicator, White/Running Header, White/Section Indicator | 0 | false                  | false      | ANYWHERE  | false                                                | LEFT / RIGHT                    | TABULAR_LINING                         | t / f / t           | NORMAL           |
|  [07]   | Table Body, Header, Numeric, Total                       | 0                | false                       | false      | ANYWHERE  | false                                                | LEFT / RIGHT                    | TABULAR_LINING                         | t / f / t           | NORMAL           |
|  [08]   | Contents L1–L3, White/Contents L1                        | 1 / 0 / 0        | true / 2 / 2                | false      | ANYWHERE  | false                                                | LEFT_ALIGN                      | TABULAR_LINING                         | t / f / t           | NORMAL           |
|  [09]   | List Bullet, List Numbered, List Numbered First          | 0                | true / 2 / 2                | false      | ANYWHERE  | true                                                 | LEFT_ALIGN                      | PROPORTIONAL_LINING, marker TABULAR    | t / f / t           | NORMAL           |
|  [10]   | Pull Quote                                               | 0                | true                        | true       | ANYWHERE  | false                                                | LEFT_ALIGN, `ignoreEdgeAlignment` | PROPORTIONAL_OLDSTYLE                | t / t / t           | NORMAL           |
|  [11]   | Code                                                     | 0                | true / 3 / 3                | false      | ANYWHERE  | false                                                | LEFT_ALIGN                      | TABULAR_LINING                         | f / f / f           | NORMAL           |
|  [12]   | Form Label                                               | 0                | false                       | false      | ANYWHERE  | false                                                | LEFT_ALIGN                      | TABULAR_LINING                         | t / f / t           | CAP_TO_SMALL_CAP |
|  [13]   | Body Fa, Body Ar                                         | 0                | true / 2 / 2                | false      | ANYWHERE  | false                                                | RIGHT_JUSTIFIED                 | by `digitsType`                        | t / f / t           | NORMAL           |
|  [14]   | Heading Fa, Heading Ar, Caption Fa, Caption Ar           | 2 / 0            | true                        | true       | ANYWHERE  | false                                                | RIGHT_ALIGN                     | by `digitsType`                        | t / f / t           | NORMAL           |

'''
doc=doc[:a]+new_keep+doc[b:]
rep("|  [03]   | pointSize / leading                          | 12.75/15                              | H1–H3 by ratio          | 9.5625/11.25      | 12.75/15                    | by ratio       | 9.5625/11.25   |",
    "|  [03]   | pointSize / leading                          | 12.75/15                              | H1, H2, Heading by ratio | 9.5625/11.25     | 12.75/15                    | by ratio       | 9.5625/11.25   |")

# surfaces rows
rep("|  [01]   | text variables       | built-in `Running Header` re-pointed: `variableOptions.appliedParagraphStyle=H1`, `searchStrategy=SearchStrategies.FIRST_ON_PAGE`, `deleteEndPunctuation=true`, `changeCase=ChangeCaseOptions.NONE`; new `Section Title` (H1), `Subsection Title` (MATCH_PARAGRAPH_STYLE_TYPE, H2, `LAST_ON_PAGE`), `Last Page` (LAST_PAGE_NUMBER_TYPE, DOCUMENT_SCOPE, ARABIC), `Chapter` (CHAPTER_NUMBER_TYPE); `File Name` (`includeExtension=true`, `includePath=false`) and `Output Date` (`format=\"yyyy-MM-dd\"`) placed in the slug frame of `B-Running` |",
    "|  [01]   | text variables       | the built-ins alone, re-pointed (eight exist at app level, read live; no variable is added): `Running Header` `variableOptions.appliedParagraphStyle=H1`, `searchStrategy=SearchStrategies.FIRST_ON_PAGE`, `deleteEndPunctuation=true`, `changeCase=ChangeCaseOptions.NONE`; `Last Page Number` `variableOptions.scope=VariableScopes.DOCUMENT_SCOPE`, `format=VariableNumberingStyles.ARABIC`; `Chapter Number` as is; `File Name` (`includeExtension=true`, `includePath=false`) and `Output Date` (`format=\"yyyy-MM-dd\"`) placed in the slug frame of `B-Text` (property names read live on each `variableOptions` object) |")
rep("`appliedCharacterStyle=\"Strong\"`; Hyperlinks panel appearance `hyperlinkAppearance=HyperlinkAppearanceStyle.INVISIBLE_RECTANGLE` in the template's default hyperlink",
    "`appliedCharacterStyle=\"Strong\"`; hyperlink appearance on every hyperlink the template creates `visible=false` (the UXP `h/hyperlink` page: `visible`, `highlight: HyperlinkAppearanceHighlight`, `borderStyle: HyperlinkAppearanceStyle` = `SOLID | DASHED` only, read live)")
rep("numberedParagraphs:TocNumberedParagraphs.EXCLUDE_NUMBERS})`; entries `tocStyleEntries.add({formatStyle:\"Contents L1\", level:1, pageNumberPosition:PageNumberPosition.AFTER_ENTRY, separator:\"^y\", pageNumberStyle:\"Tabular Figures\", separatorStyle:\"[None]\"})` for H1 → L1, H2 → L2, H3 → L3;",
    "numberedParagraphs:NumberedParagraphsOptions.EXCLUDE_NUMBERS})` (the enumeration name on the UXP `t/toc-style` page and live; `TocNumberedParagraphs` is undefined on 21.6.0.58); entries `tocStyleEntries.add({formatStyle:\"Contents L1\", level:1, pageNumberPosition:PageNumberPosition.AFTER_ENTRY, separator:\"^y\", pageNumberStyle:\"Tabular Figures\", separatorStyle:\"[None]\"})` for H1 → L1, H2 → L2, Heading → L3;")
rep("`footnoteMarkerStyle=\"Note Reference\"`, `footnoteTextStyle=\"Footnote\"`,","`footnoteMarkerStyle=\"Note Reference\"`, `footnoteTextStyle=\"Note\"`,")
rep("`endnoteOptions`: `endnoteTitle=\"Notes\"`, `endnoteTitleStyle=\"Endnote Title\"`, `endnoteNumberingStyle=FootnoteNumberingStyle.ARABIC`, `startEndnoteNumberAt=1`, `restartEndnoteNumbering=EndnoteRestarting.DONT_RESTART`, `endnoteMarkerPositioning=FootnoteMarkerPositioning.SUPERSCRIPT_MARKER`, `endnoteMarkerStyle=\"Note Reference\"`, `endnoteTextStyle=\"Endnote\"`, `endnoteSeparatorText=\"\\t\"`, `scopeValue=EndnoteScope.DOCUMENT`, `frameCreateOption=EndnoteFrameCreate.NEW_PAGE`",
    "`endnoteOptions`: `endnoteTitle=\"Notes\"`, `endnoteTitleStyle=\"H1\"`, `endnoteNumberingStyle=FootnoteNumberingStyle.ARABIC`, `startEndnoteNumberAt=1`, `restartEndnoteNumbering=EndnoteRestarting.CONTINUOUS` (members read live: `CONTINUOUS`, `STORY_RESTART`), `endnoteMarkerPositioning=FootnoteMarkerPositioning.SUPERSCRIPT_MARKER`, `endnoteMarkerStyle=\"Note Reference\"`, `endnoteTextStyle=\"Note\"`, `endnoteSeparatorText=\"\\t\"`, `scopeValue=EndnoteScope.ENDNOTE_DOCUMENT_SCOPE` (members: `STORY_SCOPE`, `ENDNOTE_DOCUMENT_SCOPE`), `frameCreateOption=EndnoteFrameCreate.NEW_PAGE`")
rep("a sample frame on parent `D-Merge` holds","a sample frame on parent `E-Merge` holds")
rep("|  [09]   | forms                | parent `E-Form`:","|  [09]   | forms                | parent `F-Form`:")
rep("|  [10]   | baseline grid        | document: `gridPreferences.baselineStart=0`, `baselineDivision=15pt`, `baselineGridRelativeOption=TOP_OF_MARGIN`, `baselineGridShown=true`, `baselineViewThreshold=50`; frame grids only on `Figure Caption Frame` and `Sidebar` (11.25 pt); document grid 60 pt / 4 hidden",
    "|  [10]   | baseline grid        | document: `gridPreferences.baselineStart=\"9.550pt\"` (f, [07] row 06), `baselineDivision=\"15pt\"`, `baselineGridRelativeOption=BaselineGridRelativeOption.TOP_OF_MARGIN_OF_BASELINE_GRID_RELATIVE_OPTION`, `baselineGridShown=true`, `baselineViewThreshold=25`; frame grids only on `Caption` and `Sidebar` (11.25 pt); document grid 15 pt / 1 hidden, snap off ([05] rows 59–62)")
rep("`B-Text` (based on A; running header frame `Running Header` style with `Section Title` variable at baseline 22.5, folio frame `Section Indicator` style at baseline 735, slug frame with `File Name` and `Output Date`, primary text frame `Text Frame` style over the 12 columns from f-guide 35.451 to baseline 690; `masterSpread.primaryTextFrame`)",
    "`B-Text` (based on A; running header frame `Running Header` style with the `Running Header` variable at baseline 22.5, folio frame `Section Indicator` style at baseline 735, slug frame with `File Name` and `Output Date`, primary text frame `Text Frame` style over the 12 columns from f-guide 35.450 to baseline 690; `masterSpread.primaryTextFrame`)")

# traps
rep("|  [01]   | creation order                                             | swatches (`Accent`) → character styles → `numberingLists.add({name:\"Body List\"})` → paragraph styles parent-before-child → object styles → cell styles → table style → text variables → TOC style → conditions and sets → masters, layers, guides → footnote and endnote options → preflight |",
    "|  [01]   | creation order                                             | swatches (`Accent`, `Ink`, `Field`) → character styles → `numberingLists.add({name:\"Body List\"})` → `paragraphStyleGroups.add({name:\"White\"})` → paragraph styles parent-before-child → object styles → cell styles → table style → text variables → TOC style → conditions and sets → masters, layers, guides → footnote and endnote options → preflight |")
rep("|  [05]   | `appliedLanguage`                                          | `app.languagesWithVendors.item(name)` object, never a string in UXP; `[No Language]` name is [10] row U3                                                                                                                                                                  |",
    "|  [05]   | `appliedLanguage`                                          | `app.languagesWithVendors.item(name)` object, never a string in UXP; `[No Language]`, `Arabic`, `Hebrew`, `English: USA` are names in the 61-entry list read live                                                                                                         |")
rep("|  [23]   | mixed-direction digits                                     | `Latin in RTL` and `Digits Fa` GREP rows; `Force Neutral Character Direction` is an ME-edition preference absent here                                                                                                                                                     |",
    "|  [23]   | mixed-direction digits                                     | `Latin in RTL` and `Digits Fa` GREP rows; `Force Neutral Character Direction` is an ME-edition preference absent here                                                                                                                                                     |\n|  [24]   | enumerator spellings on 21.6.0.58                          | `EndnoteRestarting.CONTINUOUS` (no `DONT_RESTART`), `EndnoteScope.ENDNOTE_DOCUMENT_SCOPE`, `NumberedParagraphsOptions` (no `TocNumberedParagraphs`), `PreflightProfileOptions.USE_EMBEDDED_PROFILE` (no `PreflightProfilePolicy`), `PreflightLayerOptions.PREFLIGHT_VISIBLE_LAYERS`, `BaselineGridRelativeOption.TOP_OF_MARGIN_OF_BASELINE_GRID_RELATIVE_OPTION`, `Hyperlink.visible=false` for an invisible hyperlink (`HyperlinkAppearanceStyle` is `SOLID | DASHED`); every other enumerator in this file is a member of the live dump |")

# deck paragraph
rep("Image-caption grid (Kelman p1, p8–p10): the image bottom sits on a baseline and the caption frame occupies the next line (`Caption`, 1 L, `Figure Caption Frame` style with its 11.25 pt frame grid), so `Caption` anchored `ABOVE_LINE` in [06] is the document form and the deck form is the same frame pair on the parent. Black variants: a full-page `Field` rectangle filled `Ink` plus the white text roles as a `White` paragraph-style group whose members are based on their black parents with `fillColor=\"Paper\"` (the only differing property).",
    "Image-caption grid (Kelman p1, p8–p10): the image bottom sits on a baseline and the caption frame occupies the next line (`Caption` object style, 1 L, its 11.25 pt frame grid), anchored `ABOVE_LINE` in the document form and free-standing on the deck parents. Black variants: a full-page `Field` rectangle filled `Ink` plus the four `White` group styles of [06] (`White/Title`, `White/Contents L1`, `White/Running Header`, `White/Section Indicator`, each `fillColor=\"Paper\"` on its black parent), the only roles the parents above place on `Ink` or on an image.")
open(p,"w",encoding="utf-8").write(doc)
print("ok")
