import re
p="../gui-indesign.md"
doc=open(p,encoding="utf-8").read()
def rep(old,new,count=1):
    global doc
    assert doc.count(old)==count, (old[:90], doc.count(old))
    doc=doc.replace(old,new)
def r3(x): return f"{x:.3f}".rstrip("0").rstrip(".") if abs(x-round(x))>1e-9 else f"{int(round(x))}"
def fam(name,W,H,L,ratio,sides,rows,lines,gut,folio_L=3,first_L=3,px=False):
    body=0.85*L; f=0.749*body; sides_v=sides*L; col=(W-2*sides_v-11*L)/12
    first=first_L*L; top=first-f; n=rows*lines+(rows-1)*gut; last=first+(n-1)*L; bottom=H-last; folio=last+folio_L*L
    return dict(name=name,W=W,H=H,L=L,body=body,f=f,sides=sides_v,col=col,top=top,n=n,last=last,bottom=bottom,folio=folio,rows=rows,lines=lines,gut=gut)
MM=72/25.4
sizes={
 "Letter":fam("Letter 8.5x11",612,792,15,0.85,3,5,8,1),
 "Legal":fam("Legal 8.5x14",612,1008,15,0.85,3,6,9,1),
 "Tabloid":fam("Tabloid 11x17",792,1224,12,0.85,3,6,14,1),
 "A4":fam("A4 210x297",210*MM,297*MM,15,0.85,3,5,9,1),
 "A5":fam("A5 148x210",148*MM,210*MM,8.5,0.85,3,5,12,1),
 "A3":fam("A3 297x420",297*MM,420*MM,12,0.85,3,6,13,2),
 "A2":fam("A2 420x594",420*MM,594*MM,11.5,0.85,3,6,22,1),
 "A1":fam("A1 594x841",594*MM,841*MM,11.5,0.85,3,6,32,1),
 "A0":fam("A0 841x1189",841*MM,1189*MM,36,0.85,3,6,12,2),
 "D169":fam("Digital 3840x2160",3840,2160,45,0.85,3,6,5,2,folio_L=4),
 "D1610":fam("Digital 4000x2500",4000,2500,50,0.85,3,6,5,2,folio_L=4),
 "Board":fam("Board 24x48",3456,1728,12,0.85,3,3,44,2),
}
for k,s in sizes.items():
    print(k, {kk:(r3(v) if isinstance(v,float) else v) for kk,v in s.items() if kk in("W","H","body","f","col","top","n","last","bottom","folio")})
S=sizes
# ---- [07] row 01
rep("`app.swatches` = reserved four + the 92 `Default Palette` swatches in groups `Base` and `Expanded` as integer CMYK process swatches from cloud-library's canonical `palette.json` (the Codex float RGB swatches are gone) + `Accent`;",
    "`app.swatches` = reserved four (`None`, `Registration`, `Paper`, `Black`) + the 92 `Default Palette` swatches in groups `Base` and `Expanded` as integer CMYK process swatches from cloud-library's canonical `palette.json` (the Codex float RGB swatches are gone) + `Accent`, `Ink`, `Field`, with the six factory `C=…` process swatches read live removed;")
rep("`app.preflightProfiles` `Default Preflight`; `app.pdfExportPresets` `Default Print`, `Default Digital`; `app.documentPresets` `Default Template`; workspace, shortcut set, menu set names |",
    "`app.textVariables` built-ins re-pointed as [06]; `app.preflightProfiles` `Default Preflight` (the live three-rule Codex profile and `kDigPubProfileName` read today; ours replaces the first in place); `app.pdfExportPresets` `Default Print`, `Default Digital`; `app.documentPresets` `Default Template`; workspace, shortcut set, menu set names |")
# ---- conventions paragraph
rep("Conventions taken from the Drive bundles (26 Kelman files read as IDML or byte-scanned, the School template, Verlag, the Baltus guidebook; the typefool set is absent from Drive, [10] row U12): size = 0.85 × leading on every Kelman deck and the School file (adopt); the type-area top sits at the f-height of the first line, so Kelman's odd top margins are `k·L − f` with `f = 0.749 × body size` for Neue Haas Grotesk Text Pro 55 (`f` glyph yMax 749/1000 em, measured with fontTools) and the School template's `Hanglines` layer is the same offset (adopt); column gutters in Kelman are `2L − f` or 0, 12 pt appears only where the InDesign dialog default was left (reject 12; adopt 1 module = 15 pt so 12 columns and 11 gutters stay on the document grid and row and column gutters are equal, with `2L − f` recorded as the optical alternative);",
    "Conventions taken from the Drive bundles (26 Kelman files read as IDML or byte-scanned, the School template, Verlag, the Baltus guidebook; the typefool set is absent from Drive, [10] row U12; the seven Kelman and Verlag IDML files under `98.Templates/02.Documentation Templates/00.General/` re-read on 2026-09-11 for margins, guides, and text defaults, probe-gui/kelman-idml.txt): size = 0.85 × leading on every Kelman deck and the School file (adopt; Kelman's A4 1-column report runs 11.25/15); the type-area top sits at the f-height of the first line, so Kelman's odd top margins are `baseline − f` with `f = 0.749 × body size` for Neue Haas Grotesk Text Pro 55 (`f` glyph yMax 749/1000 em, `sCapHeight` 744, measured with fontTools on the CoreSync file `NHaasGroteskTXPro-55Rg`; the 1280 × 720 deck's `Top=\"35.451\"` = 45 − 9.549, the A4 2-column report's `Top=\"37.944\"` = 44.947 − 7.003 at 9.35, the Letter landscape deck's `Top=\"32.818\"` = 39.183 − 6.365 at 8.5) and the School template's `Hanglines` layer is the same offset (adopt); column gutters in every Kelman file are `2L − f` (20.451, 21.574, 14.997, 13.634 read) or 0, 12 pt appears only where the InDesign dialog default was left (Verlag; reject 12; adopt 1 module = 15 pt so 12 columns and 11 gutters stay on the document grid and row and column gutters are equal, with `2L − f` recorded as the optical alternative);")
rep("The `f` value is recomputed per body face by `get_font_metrics` from the `f` glyph bounding box (`glyphForCodePoint(0x66).bbox.maxY / unitsPerEm`), never the 0.749 constant; the numbers below are the reference face's.",
    "The `f` value is recomputed per body face by `get_font_metrics` from the `f` glyph bounding box (`glyphForCodePoint(0x66).bbox.maxY / unitsPerEm`, a required addition to the tool's output in architecture.md [06.3] row 05, which today returns `capHeight`, `xHeight`, `ascent`, `descent` only), never the 0.749 constant; the numbers below are the reference face's: f = 0.749 × 12.75 = 9.54975 pt, written 9.550 at InDesign's 0.001 precision (Kelman's files carry the truncated 9.549 and 35.451; the data files carry the exact value).")
# ---- Letter geometry table rows
rep("|  [02]   | module `L`                  | 15 pt; body 12.75/15; `f` = 9.549 pt                                                                     | Kelman Letter and School files; `f = 0.749 × 12.75`                          |",
    "|  [02]   | module `L`                  | 15 pt; body 12.75/15; `f` = 9.550 pt (9.54975)                                                          | the School file (12.75/15 on a 15 pt grid) and Kelman's 15 px decks; `f = 0.749 × 12.75` |")
rep("|  [05]   | top margin                  | 35.451 pt                                                                                                | 3 L − f                                                                      |",
    "|  [05]   | top margin                  | 35.450 pt (35.45025)                                                                                     | 3 L − f = 45 − 9.54975                                                       |")
rep("|  [06]   | baseline grid               | `baselineStart = 9.549` relative to `TOP_OF_MARGIN`, `baselineDivision = 15`, threshold 25 %, shown      | first baseline 35.451 + 9.549 = 45 = 3 L                                     |",
    "|  [06]   | baseline grid               | `baselineStart = 9.550` relative to `TOP_OF_MARGIN_OF_BASELINE_GRID_RELATIVE_OPTION`, `baselineDivision = 15`, threshold 25 %, shown | first baseline 35.450 + 9.550 = 45.000 = 3 L                          |")
rep("|  [10]   | row tops (f-guides)         | 35.451, 170.451, 305.451, 440.451, 575.451                                                               | baseline − f                                                                 |",
    "|  [10]   | row tops (f-guides)         | 35.450, 170.450, 305.450, 440.450, 575.450                                                               | row baseline − f                                                             |")
rep("|  [14]   | type area                   | 522 × 654.549 pt (35.451 → 690)                                                                          | —                                                                            |",
    "|  [14]   | type area                   | 522 × 654.550 pt (35.450 → 690)                                                                          | 43 L + f = 645 + 9.550                                                       |")
rep("|  [15]   | fields                      | 4 × 5 = 20, each 119.25 × 114.549 (3 columns + 2 gutters wide, 7 L + f tall); pitch 134.25 × 135         | major column = 3c + 2g                                                       |",
    "|  [15]   | fields                      | 4 × 5 = 20, each 119.25 × 114.550 (3 columns + 2 gutters wide, 7 L + f tall); pitch 134.25 × 135         | major column = 3c + 2g = 89.25 + 30; field height 105 + 9.550                |")
rep("|  [24]   | extra object style          | `Field`: `[None]` base, `enableFill`, `enableStroke`, `fillColor=\"Field\"`, `strokeColor=\"None\"`, no corner effect; color blocks on `Fields` layer | Kelman full-page and band rectangles                                         |",
    "|  [24]   | first-baseline check        | cap height 744/1000 × 12.75 = 9.486 pt; a `Text Frame` (`CAP_HEIGHT`) placed at the f-guide puts its unsnapped first baseline at 35.450 + 9.486 = 44.936; `alignToBaseline` snaps it to 45.000 (0.064 pt)  | `sCapHeight/upm`, the first-baseline check of the typography plan §05        |")
# ---- size rules paragraph
rep("Rule: 12 columns, gutter 1 L, sides 3 L, top 3 L − f, first baseline 3 L, rows in whole lines, row gutter 1 L for documents and 2 L for presentations, bottom = remainder ≥ 4 L, folio = last baseline + 3 L, `L` per family from the Kelman ladder (8.5 A5 and 6×9, 10 Letter landscape decks, 11 A4 and Letter reports, 11.5 A1 and A2, 12 A3 and Tabloid, 15 Letter documents and 16:9 decks, 36 A0), body = 0.85 L; digital canvases at 72 ppi with `WEB_INTENT`, pixel units, bleed 0; print `PRINT_INTENT`, bleed 9 pt on inch sheets and 3 mm on ISO sheets, GRACoL2013_CRPC6 for every print family (the shared CSF; Kelman's FOGRA39 is not adopted).",
    "Rule: 12 columns, gutter 1 L, sides 3 L, top 3 L − f, first baseline 3 L, rows in whole lines, row gutter 1 L for documents and 2 L for presentations, the row count per family fixed below and the lines per row the largest whole number that leaves bottom ≥ 4 L, bottom = sheet height − last baseline, folio = last baseline + 3 L on print sheets and the footer line 46 = last baseline + 4 L on the digital canvases; `L` per family: 7.5 A6, 8.5 A5 and Half Letter, 11.5 A1 and A2, 12 A3, Tabloid, boards, and technical sheets, 15 Letter, Legal, and A4 documents, 36 A0, 45 px 3840 × 2160, 50 px 4000 × 2500 (the Kelman ladder holds 10 and 11 as well; no catalogue file uses them); body = 0.85 L; digital canvases at 72 ppi with `WEB_INTENT`, pixel units, bleed 0; print `PRINT_INTENT`, bleed 9 pt on inch sheets and 3 mm on ISO sheets, GRACoL2013_CRPC6 for every print family (the shared CSF; Kelman's FOGRA39 is not adopted). Every row below is closed by the formulas above (probe-gui/splice07.py recomputed them on 2026-09-11); the `typographic-grid` `grid` target reproduces each within 0.001 pt before I3.")
# ---- size table
a=doc.index("| [INDEX] | [FAMILY]              | [SHEET (pt)]"); b=doc.index("ERDC sheet parent `B-Sheet`",a)
L=S["Letter"];Lg=S["Legal"];T=S["Tabloid"];A4=S["A4"];A5=S["A5"];A3=S["A3"];A2=S["A2"];A1=S["A1"];A0=S["A0"];D9=S["D169"];D10=S["D1610"];B=S["Board"]
rows=[
("US loose",f"`Letter 8.5x11` 612 × 792","15","12.75/15","45","29.75",f"{r3(L['top'])}","4 × 5, 8 L, gutter 1 L (44 lines)",f"{r3(L['last'])}",f"{r3(L['bottom'])}",f"{r3(L['folio'])}"),
("US loose",f"`Legal 8.5x14` 612 × 1008","15","12.75/15","45","29.75",f"{r3(Lg['top'])}","4 × 6, 9 L, gutter 1 L (59 lines)",f"{r3(Lg['last'])}",f"{r3(Lg['bottom'])}",f"{r3(Lg['folio'])}"),
("US loose, ANSI B",f"`Tabloid 11x17` 792 × 1224","12","10.2/12","36","49",f"{r3(T['top'])}","4 × 6, 14 L, gutter 1 L (89 lines)",f"{r3(T['last'])}",f"{r3(T['bottom'])}",f"{r3(T['folio'])}"),
("US loose","`Half Letter 5.5x8.5` 396 × 612","8.5","7.225/8.5","25.5","20.958","20.089","4 × 5 by rule","by rule","≥ 34","+25.5"),
("ANSI C–F, ARCH A–E3 (landscape)","e.g. `ARCH D 24x36` 2592 × 1728","12","notes 10.2/12, subtitles 15.3/18, titles 20.4/24","border 24 (2 L, ≥ 3/16 in = 13.5)","none; ERDC 108 pt modules (9 L)","—","ARCH D: (2592 − 48) ÷ 108 = 23 modules + 60 pt, (1728 − 48) ÷ 108 = 15 modules + 60 pt; the two 60 pt (5 L) remainders go to the title-block column and the production-data strip","—","—","—"),
("ISO A document",f"`A4 210x297` {r3(A4['W'])} × {r3(A4['H'])}","15","12.75/15","45",f"{r3(A4['col'])}",f"{r3(A4['top'])}","4 × 5, 9 L, gutter 1 L (49 lines)",f"{r3(A4['last'])}",f"{r3(A4['bottom'])}",f"{r3(A4['folio'])}"),
("ISO A small",f"`A5 148x210` {r3(A5['W'])} × {r3(A5['H'])}","8.5","7.225/8.5","25.5",f"{r3(A5['col'])}",f"{r3(A5['top'])}","4 × 5, 12 L, gutter 1 L (64 lines)",f"{r3(A5['last'])}",f"{r3(A5['bottom'])}",f"{r3(A5['folio'])}"),
("ISO A small","`A6 105x148` 297.638 × 419.528","7.5","6.375/7.5","22.5","14.178","17.725","4 × 5 by rule","by rule","≥ 30","+22.5"),
("ISO A presentation",f"`A3 297x420` {r3(A3['W'])} × {r3(A3['H'])}","12","10.2/12","36",f"{r3(A3['col'])}",f"{r3(A3['top'])}","4 × 6, 13 L, gutter 2 L (88 lines)",f"{r3(A3['last'])}",f"{r3(A3['bottom'])}",f"{r3(A3['folio'])}"),
("ISO A boards",f"`A2 420x594` {r3(A2['W'])} × {r3(A2['H'])}","11.5","9.775/11.5","34.5",f"{r3(A2['col'])}",f"{r3(A2['top'])}","4 × 6, 22 L, gutter 1 L (137 lines)",f"{r3(A2['last'])}",f"{r3(A2['bottom'])}",f"{r3(A2['folio'])}"),
("ISO A boards",f"`A1 594x841` {r3(A1['W'])} × {r3(A1['H'])}","11.5","9.775/11.5","34.5",f"{r3(A1['col'])}",f"{r3(A1['top'])}","4 × 6, 32 L, gutter 1 L (197 lines)",f"{r3(A1['last'])}",f"{r3(A1['bottom'])}",f"{r3(A1['folio'])}"),
("ISO A poster",f"`A0 841x1189` {r3(A0['W'])} × {r3(A0['H'])}","36","30.6/36","108",f"{r3(A0['col'])}",f"{r3(A0['top'])}","4 × 6, 12 L, gutter 2 L (82 lines)",f"{r3(A0['last'])}",f"{r3(A0['bottom'])}",f"{r3(A0['folio'])}"),
("ISO B","`B0 1000x1414` … `B6 125x176`","L of the A size the sheet encloses (Bn encloses An)","0.85 L","3 L","by rule","3 L − f","rows of the enclosed A size by rule","by rule","≥ 4 L","+3 L"),
("ISO technical","`A0 Sheet 1189x841`, `A1 Sheet 841x594`, `A2 Sheet 594x420` landscape; ISO 5457 border left 20 mm, others 10 mm (A1 drawing space 811 × 574 mm)","12","10.2/12","the border","ERDC-style 108 pt modules inside the drawing space","—","labels as ERDC","—","—","—"),
("digital 16:9","`Digital 3840x2160` px: 2160 ÷ 45 = 48 whole lines, 3840 ÷ 45 = 85.33 (sides 135 and gutters 45 whole, columns 256.25)","45","38.25/45","135",f"{r3(D9['col'])}",f"{r3(D9['top'])}","4 × 6, 5 L, gutter 2 L (40 lines)",f"{r3(D9['last'])}",f"{r3(D9['bottom'])} (6 L)",f"{r3(D9['folio'])} (line 46 of 48)"),
("digital 16:10","`Digital 4000x2500` px: 4000 ÷ 50 = 80 and 2500 ÷ 50 = 50 whole (45 px fails: 2500 ÷ 45 = 55.56)","50","42.5/50","150",f"{r3(D10['col'])}",f"{r3(D10['top'])}","4 × 6, 5 L, gutter 2 L (40 lines)",f"{r3(D10['last'])}",f"{r3(D10['bottom'])} (8 L)",f"{r3(D10['folio'])} (line 46 of 50)"),
("competition board",f"`Board 24x48` 3456 × 1728 landscape","12","10.2/12","36","271",f"{r3(B['top'])}","6 × 3, 44 L, gutter 2 L (136 lines)",f"{r3(B['last'])}",f"{r3(B['bottom'])}",f"{r3(B['folio'])}"),
("competition A1","`Board A1 594x841` portrait","11.5","9.775/11.5","34.5",f"{r3(A1['col'])}",f"{r3(A1['top'])}","as A1 + anonymity block 60 × 40 mm top-left on `B-Sheet`, panel number top-right",f"{r3(A1['last'])}",f"{r3(A1['bottom'])}",f"{r3(A1['folio'])}"),
]
hdr="| [INDEX] | [FAMILY]              | [SHEET (pt)]                                   | [L]  | [BODY]     | [SIDES] | [COLUMN]  | [TOP] | [ROWS]                              | [LAST BASELINE] | [BOTTOM] | [FOLIO] |\n| :-----: | :-------------------- | :--------------------------------------------- | :--- | :--------- | :------ | :-------- | :---- | :---------------------------------- | :-------------- | :------- | :------ |\n"
tbl=hdr+"".join(f"|  [{i:02d}]   | {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} | {r[6]} | {r[7]} | {r[8]} | {r[9]} | {r[10]} |\n" for i,r in enumerate(rows,1))
tbl+="\nCatalogue (`page-sizes.json`, one `.indt` per row, 37 files, names by dimension): US loose `Letter 8.5x11`, `Legal 8.5x14`, `Tabloid 11x17`, `Half Letter 5.5x8.5`; ANSI landscape `ANSI C 17x22`, `ANSI D 22x34`, `ANSI E 34x44`, `ANSI F 28x40` (ANSI A and B are Letter and Tabloid); ARCH landscape `ARCH A 9x12`, `ARCH B 12x18`, `ARCH C 18x24`, `ARCH D 24x36`, `ARCH E 36x48`, `ARCH E1 30x42`, `ARCH E2 26x38`, `ARCH E3 27x39`; ISO A portrait `A0 841x1189` … `A6 105x148` (7); ISO B portrait `B0 1000x1414` … `B6 125x176` (7); technical sheets `A0 Sheet 1189x841`, `A1 Sheet 841x594`, `A2 Sheet 594x420`; `Digital 4000x2500`, `Digital 3840x2160`; `Board 24x48`, `Board A1 594x841`. The set is the gui-stream plan's §08 I3 list and indesign-acrobat-depth.md §02.10 (thirty-one presets with orientations toggled at creation) with the four undecided digital sizes left out and one file per orientation the family needs.\n\n"
doc=doc[:a]+tbl+doc[b:]
# remove the stray heading line for the old table if left
rep("Size catalog derivation per family (`page-sizes.json`; per-size rebuild for every family,","Size catalog derivation per family (`page-sizes.json`; per-size rebuild for every family through `apply_grid`,")
# ---- preflight options, presets, swatches, shortcut, menu, user settings
rep("`document.preflightOptions.preflightWorkingProfile=\"Default Preflight\"`, `preflightEmbedWorkingProfile=true`, `preflightProfilePolicy=PreflightProfilePolicy.USE_EMBEDDED`, `preflightWhichLayers=PreflightLayerOptions.VISIBLE_LAYERS`, `preflightOff=false`; the profile file through `export_preflight_profile{name, output}` → `profile.save(File)` (`.idpp`)",
    "`document.preflightOptions.preflightWorkingProfile=\"Default Preflight\"`, `preflightEmbedWorkingProfile=true`, `preflightProfilePolicy=PreflightProfileOptions.USE_EMBEDDED_PROFILE` (members read live: `USE_EMBEDDED_PROFILE`, `USE_WORKING_PROFILE`; the UXP `p/preflight-option` page types the property `PreflightProfileOptions`), `preflightWhichLayers=PreflightLayerOptions.PREFLIGHT_VISIBLE_LAYERS`, `preflightOff=false`; the profile file through `export_preflight_profile{name, output}` → `profile.save(File)` (`.idpp`, an XML snippet: the Codex `Default Preflight.idpp` on Drive, 1,072 bytes, `<?aid SnippetType=\"PreflightProfile\"?>` with three `PreflightRuleInstance` rows, read 2026-09-11); reload through `app.loadPreflightProfile(File)` (UXP `a/application`)")
rep("Preflight profile `Default Preflight` (`app.preflightProfiles.add({name})` at app level, then `document.preflightProfiles` embedded through `document.embed(profile)`; the live `Default Preflight` in the Codex template has three rules; `[Basic]` holds 38 ids, every `flag` and `ruleDataObjects` value below read from the live `[Basic]` dump):",
    "Preflight profile `Default Preflight` (`app.preflightProfiles.add({name})` at app level, then `document.preflightProfiles` embedded through `document.embed(profile)`; the live app-level `Default Preflight` (Codex) holds the three rules `ADBE_MissingFonts`, `ADBE_MissingModifiedGraphics`, `ADBE_OversetText`, read from the Drive `.idpp`; `[Basic]` holds 38 rule ids, every `flag` and data field name below exists in the live `[Basic]` dump, the values that differ from `[Basic]` are ours: `minSize` 6 (4), `min_width` 0.25 (0.125), `no_Type1` true (false), `color_min_res`/`gray_min_res` 250 and `bw_min_res` 800 as `[Basic]`):")
rep("Swatches: `Default Palette.ase` (cloud-library, 92 corrected integer values) imported through the Swatches panel menu `Load Swatches…` with no document open (app default) and again in the template build through `import_swatches`-equivalent `execute` body (`document.colors.add({name, model: ColorModel.PROCESS, space: ColorSpace.CMYK, colorValue})`, `colorGroups.add({name})`, `colorGroup.colorGroupSwatches.add(swatch)`); the three factory `C=100 M=0…` process swatches removed (`swatch.remove()`); reserved four stay; readback `app.swatches.everyItem().name`.",
    "Swatches: `Default Palette.ase` (cloud-library, 92 corrected integer values) loaded with no document open through `app.loadSwatches(File)` (UXP `a/application`: \"Load swatches from the specified file\", the `.ase` or an InDesign document; in `app.reflect.methods` on 21.6.0.58), the same call replacing the panel menu `Load Swatches…`, and again in the template build through an `execute` body (`document.colors.add({name, model: ColorModel.PROCESS, space: ColorSpace.CMYK, colorValue})`, `colorGroups.add({name})`, `colorGroup.colorGroupSwatches.add(swatch)`); the six factory process swatches read live (`C=100 M=0 Y=0 K=0`, `C=0 M=100 Y=0 K=0`, `C=0 M=0 Y=100 K=0`, `C=15 M=100 Y=100 K=0`, `C=75 M=5 Y=100 K=0`, `C=100 M=90 Y=10 K=0`) removed (`swatch.remove()`); reserved four stay; `Accent`, `Ink`, `Field` added from `palette.json`; readback `app.swatches.everyItem().name`.")
rep("file `en_US/InDesign Shortcut Sets/Default Shortcut Set.indk` (`<shortcut-set platform=\"mac\" …>` XML, format read from the bundle's `Default.indk`); apply `app.applyShortcutSet(\"Default Shortcut Set\")`; readback `generalPreferences.keyboardShortcutSet`.",
    "file `en_US/InDesign Shortcut Sets/Default Shortcut Set.indk` (the folder exists and is empty today; `<shortcut-set platform=\"mac\" file-version=\"4\" application-version=\"4.0\" build-number=\"50\">` with `<shortcut><action-id value name/><context/><string/>` rows, format read from the bundle's `Presets/InDesign Shortcut Sets/en_US/Default.indk`); apply `app.applyShortcutSet(\"Default Shortcut Set\")` (UXP `a/application`: no string applies the default set); readback `generalPreferences.keyboardShortcutSet` and `difft` of the saved file against `Default.indk` (header attributes and nothing else).")
rep("Menu set `Default Menu Set`: Edit > Menus… → Save As → hide the commands listed at the end of [05] → Save; saved into the workspace on the next workspace save (XML `<menu-set name=\"Default Menu Set\" is-preset=\"false\">`); apply `app.applyMenuCustomization(\"Default Menu Set\")`; readback the workspace XML and `Window > Workspace > Show Full Menus` reveals the hidden commands once.",
    "Menu set `Default Menu Set`: Edit > Menus… → Save As → hide the 34 commands listed at the end of [05] (every one present in the live menus read 2026-09-11) → Save; the set is written into `en_US/Menu Sets/` (the folder exists and is empty today; the Application UI plug-in's string table names it: \"Failed to write menu set. The Menu Sets folder may be locked.\"; file name and extension recorded at save, [10] row U15) and referenced by the workspace on the next workspace save (XML `<menu-set platform=\"mac\" file-version=\"1\" application-version=\"21.6\" build-number=\"58\" name=\"Default Menu Set\" is-preset=\"false\">`); apply `app.applyMenuCustomization(\"Default Menu Set\")` (UXP `a/application`: an empty string is Show Full Menus, no string the default set); readback the workspace XML and the System Events menu read.")
rep("User settings: `File > User Settings > Export User Settings…` → `Default User Settings` (Adobe bundles Preferences, Workspaces, Menu sets, Keyboard shortcuts, Glyph sets; the file extension the dialog writes is recorded at export, [10] row U11);",
    "User settings: `File > User Settings > Export User Settings…` (present in the live File menu) → `Default User Settings` (Adobe bundles Preferences, Workspaces, Menu sets, Keyboard shortcuts, Glyph sets; the dialog's default name pattern is `^1Settings_^2` in the Application UI string table; the extension it writes is recorded at export, [10] row U11; `app.exportSettings` and `app.importSettings` exist in `app.reflect.methods` on 21.6.0.58 with no argument metadata and no UXP page, [10] row U27);")
open(p,"w",encoding="utf-8").write(doc)
print("done")
