import re
p="../gui-indesign.md"
doc=open(p,encoding="utf-8").read()
def rep(old,new,count=1):
    global doc
    assert doc.count(old)==count, (old[:90], doc.count(old))
    doc=doc.replace(old,new)
# formatting in the size table
for old,new in [("| 35.45 |","| 35.450 |"),("| 28.36 |","| 28.360 |"),("| 7.64 |","| 7.640 |"),("| 20.089 |","| 20.088 |"),("| 27.179 |","| 27.179 |")]:
    doc=doc.replace(old,new)
# ---- [08]
rep("| `en_US/Workspaces/Default Workspace_CurrentWorkspace.xml` (and the preset-style file the dialog writes, [10] row U14)   | `Default Workspace.xml`                          |",
    "| `en_US/Workspaces/Default Workspace_CurrentWorkspace.xml` (`_CurrentWorkspace` is the `PW_CurrentWorkspaceSuffix` string of the Application UI plug-in; the saved-set file beside it is [10] row U14) | `Default Workspace.xml`                          |")
rep("| `.artifacts/creative-cloud/indesign/Sizes/*.indt`                                                                      | `Sizes/<name>.indt` (19 files, [07] size table)  |",
    "| `.artifacts/creative-cloud/indesign/Sizes/*.indt`                                                                      | `Sizes/<name>.indt` (37 files, the [07] catalogue) |")
rep("| `generalPreferences.keyboardShortcutSet === \"Default Shortcut Set\"`; file XML diff against the bundle `Default.indk` shows only the header name                                  |",
    "| `generalPreferences.keyboardShortcutSet === \"Default Shortcut Set\"`; `difft` against the bundle `Default.indk` shows header attributes only                                        |")
rep("| workspace XML `<menu-set>`; `en_US/Menu Sets/` ([10] row U15)                                                          | (inside `Default Workspace.xml`)                 |",
    "| `en_US/Menu Sets/<file>` (folder proven by the plug-in string table; file name [10] row U15); workspace XML `<menu-set name>` | `Menu Sets/<file>` and the name inside `Default Workspace.xml` |")
rep("| `~/Library/Application Support/Adobe/Adobe PDF/Settings/Default Print.joboptions`, `Default Digital.joboptions`         | `Default Print.joboptions`, `Default Digital.joboptions` | `app.pdfExportPresets.everyItem().name` includes both; `File > Adobe PDF Presets` lists both; Acrobat Distiller lists both ([10] row U10)                                  |",
    "| `~/Library/Application Support/Adobe/Adobe PDF/Settings/Default Print.joboptions`, `Default Digital.joboptions` (the user folder is empty today; ten stock files in `/Library/…`) | `Default Print.joboptions`, `Default Digital.joboptions` | `app.pdfExportPresets.everyItem().name` includes both (six stock names today); `File > Adobe PDF Presets` lists both; Acrobat Distiller lists both ([10] row U10)     |")
rep("| `.artifacts/creative-cloud/indesign/Default Preflight.idpp`                                                            | `Default Preflight.idpp`                         | `app.preflightProfiles.everyItem().name` includes it; rule flags readback equals [07]                                                                                            |",
    "| `.artifacts/creative-cloud/indesign/Default Preflight.idpp` (XML snippet, the extension proven by the Codex file on Drive) | `Default Preflight.idpp`                     | `app.preflightProfiles.everyItem().name` includes it; rule flags readback equals [07]; `app.loadPreflightProfile(File)` round trip                                              |")
rep("| cloud-library `Default Palette.ase` copied                                                                          | `en_US/Swatch Libraries/Default Palette.ase`                                                                           | `Default Palette.ase` (cloud-library's)          | `app.swatches.everyItem().name` (no document) = reserved four + 92 + Accent, Ink, Field                                                                                          |",
    "| cloud-library `Default Palette.ase` loaded through `app.loadSwatches(File)` and copied                                | `en_US/Swatch Libraries/Default Palette.ase` (the folder does not exist today; created by the copy)                    | `Default Palette.ase` (cloud-library's)          | `app.swatches.everyItem().name` (no document) = reserved four + 92 + Accent, Ink, Field                                                                                          |")
# ---- [09]
rep("| write every [05] DOM row with no document open; read back; `set_text_defaults{scope: 'application'}` with the text-default table; write `[Basic Paragraph]`           |",
    "| write every [05] DOM row with no document open (including `displaySettings.item(i).greekBelow`); read back; `set_text_defaults{scope: 'application'}` with the text-default table; write `[Basic Paragraph]` |")
rep("| dialog-only rows [05] 30, 31, 35–37, 44, 47, 48, 73, 80, 84:","| dialog-only rows [05] 30, 31, 35–37, 44, 47, 48, 80, 84:")
rep("`RIGHT_TO_LEFT_DIRECTION` and `rightToLeftDirection` spellings; `[No Language]` name; `objectStyle.storyPreferences.storyDirection` applied;",
    "`RIGHT_TO_LEFT_DIRECTION` and `rightToLeftDirection` spellings; `objectStyle.storyPreferences.storyDirection` applied;")
rep("| defaults from the template: with no document open, load swatches (`Load Swatches…` from the `.ase`), set `documentPresets.item(\"Default Template\")`, `preflightProfiles` `Default Preflight` at app level, `pdfExportPresets` `Default Print`, `Default Digital`, `saveFindChangeQuery` × 5 | DOM, AX                                    |",
    "| defaults from the template: with no document open, `app.loadSwatches(File(\".ase\"))`, set `documentPresets.item(\"Default Template\")`, `preflightProfiles` `Default Preflight` at app level (rewriting the live three-rule profile), `pdfExportPresets` `Default Print`, `Default Digital`, `saveFindChangeQuery` × 5, re-point the five built-in text variables | DOM                                        |")
rep("| I3: `build_size_catalog{master, sizes, outputDir}` for the 19 rows; reopen each","| I3: `build_size_catalog{master, sizes, outputDir}` for the 37 catalogue files; reopen each")
rep("RTL proof steps in [12] map to `indesign-uxp.md` [12] rows 09, 10, 15, 16 and this file's [10] rows U1–U6.",
    "RTL proof steps in [12] map to `indesign-uxp.md` [12] rows 09, 10, 15, 16 and this file's [10] rows U1, U2, U6. Required additions to architecture.md [06.3] before I2: `get_font_metrics` returns `fTop = glyphForCodePoint(0x66).bbox.maxY / unitsPerEm` beside `capHeight` (fontkit `Glyph.bbox`); every other tool or `execute` body this file names exists in [06.3] rows 02–16.")
# ---- [10] table
a=doc.index("## [10]-[VERIFIED_VERSUS_UNVERIFIED]"); b=doc.index("## [11]-[SOURCES]",a)
new10='''## [10]-[VERIFIED_VERSUS_UNVERIFIED]

| [INDEX] | [CLAIM]                                                                                                              | [STATUS]                 | [EVIDENCE OR PROOF STEP]                                                                                                                       |
| :-----: | :------------------------------------------------------------------------------------------------------------------- | :----------------------- | :--------------------------------------------------------------------------------------------------------------------------------------------- |
|  [01]   | 21.6.0.58 has no toolbar editor; layout is `toolsPanel` only                                                         | verified                 | Adobe toolbox pages (2026-06-02, 2024-09-08); `app.menuActions` (4,843) read live, no `Toolbar` action, the composer actions present; `ToolsPanelOptions` three members read live |
|  [02]   | `contextBarVisible`, `applicationBarShown`, `toolsPanel`, `panelTabHeightPreference`, `uiBrightnessPreference` exist on `generalPreferences` | verified   | `reflect.properties` read live (probe-gui/r2.out)                                                                                              |
|  [03]   | `Adobe World-Ready Paragraph Composer` and `Adobe World-Ready Single-line Composer` are menu actions on this build; the key string is `$ID/HL Composer Optyca` | verified | `app.menuActions` and `app.findKeyStrings` read live 2026-09-11 (probe-gui/r1.out)                                                          |
|  [04]   | `app.languagesWithVendors` has 61 entries, `[No Language]`, `Arabic`, `Hebrew`, `English: USA` among them, no Persian | verified                 | `everyItem().name` read live (probe-gui/r1.out)                                                                                                |
|  [05]   | Window, File, Edit, Type, Object, View, Help, Plug-Ins menus and the Window submenus of 21.6.0.58; every command in the `Default Menu Set` list exists | verified | System Events reads (probe-gui/win.out)                                                                                                        |
|  [06]   | current values of every DOM preference row in [05] and the text-default table                                        | verified                 | live reads (probe-gui/r2.out, props.out); `whenScaling` already `APPLY_TO_CONTENT`; `otfFigureStyle` default `DEFAULT_VALUE`                    |
|  [07]   | every property name in [06] and [07] exists on its live class; every enumerator is a member of the live enumeration  | verified                 | `reflect.properties` dump and enumeration dump (probe-gui/props.out, enums.out) checked mechanically; the mismatches are corrected in place (traps row 24) |
|  [08]   | `[Basic]` preflight rule ids (38), flags, and data field names; three-rule `Default Preflight` (Codex)               | verified                 | `app-preferences.json` dump; the Drive `Default Preflight.idpp` snippet                                                                        |
|  [09]   | AI plug-ins live inside the sealed bundle; removal breaks the signature                                               | verified                 | `fd`, `codesign -dvv`, `CodeResources`; Apple Code Signing Guide                                                                               |
|  [10]   | Kelman geometry: top margin = baseline − f, gutters `2L − f`, 0.749 f-ratio for NHG Text Pro 55                      | verified                 | seven IDML reads (probe-gui/kelman-idml.txt) and fontTools on the CoreSync `NHaasGroteskTXPro-55Rg` (probe-gui/font-metrics.txt)               |
|  [11]   | the Letter, Legal, Tabloid, A4, A5, A3, A2, A1, A0, board, and digital rows close under the [07] formulas            | verified                 | recomputed (probe-gui/splice07.py); the `typographic-grid` `grid` target reproduces them within 0.001 pt before I3                             |
|  [12]   | panel leaf names and ids of [03]; the control bar closed today; the toolbar leaf `size-variant="vertical-narrow"`   | verified                 | `Essentials_CurrentWorkspace.xml`, `Start_CurrentWorkspace.xml`, the eleven preset workspace files                                            |
|  [13]   | `app.loadSwatches(File)`, `app.loadPreflightProfile(File)`, `app.exportPresets(format, File)`, `app.importFile(format, File)`, `app.applyMenuCustomization(name)`, `app.saveFindChangeQuery(name, mode)` | verified | UXP `a/application` page fetched 2026-09-11; present in `app.reflect.methods`                                                                 |
|  [14]   | `DisplaySetting.greekBelow` exists; `app.displaySettings` order is Fast, Typical, High Quality                        | verified                 | `raster` read live: `GRAY_OUT`, `PROXY`, `HIGH_RESOLUTION`                                                                                    |
|  U1     | GREP style beats a nested style on the same attribute; later GREP row wins (general case; the indicator's two rows are disjoint) | unverified       | one paragraph with nested `Emphasis` on the first word and GREP `^\\w+` → `Strong`; read `characters[0].fontStyle`; Adobe's GREP-styles page rendered only navigation through every allowed channel |
|  U2     | the non-ME build applies `objectStyle.storyPreferences.storyDirection` to a frame                                     | unverified               | apply `Text Frame Fa`; read `frame.parentStory.storyPreferences.storyDirection`                                                                |
|  U5     | a row of n lines measures 15n with leading 15, `LEADING_OFFSET`, vertical insets 0                                    | unverified               | build one- and two-line rows, read `row.height`; on a miss set `row.autoGrow=false; row.height`                                                |
|  U6     | `RIGHT_JUSTIFIED` ends an RTL paragraph flush right                                                                  | unverified               | Body Fa sample, read the last line's horizontal offset                                                                                         |
|  U8     | `hyphenWeight` DOM range vs the 0–10 slider                                                                          | unverified               | set 5, read back (live default 5)                                                                                                              |
|  U9     | `tabList = []` rejected (gui-stream report)                                                                          | unverified               | on the scratch document assign `[]`, then the [06] arrays; read `tabList.length`                                                                |
|  U10    | `exportPresets(PDF_EXPORT_PRESETS_FORMAT)` writes a `.joboptions` Distiller and Acrobat read                          | unverified               | export, `file`, load in Acrobat Distiller                                                                                                      |
|  U11    | the user-settings export file extension                                                                              | unverified               | export once, `ls`; the dialog's default name pattern is `^1Settings_^2` (Application UI string table)                                          |
|  U12    | typefool templates on Drive                                                                                          | absent                   | `fd -i typefool` over the whole Drive returned nothing on 2026-09-11; re-download is a cloud-library job (owned purchase, account access granted) |
|  U13    | ERDC title-block width, Production Data Area size, the 108 pt module                                                 | unverified               | read ERDC/ITL SR-23-1 §2.1 figures; the ARCH D module count above assumes 108 pt                                                              |
|  U14    | the file a user-saved workspace writes beside `<name>_CurrentWorkspace.xml`                                          | unverified               | save `Default Workspace`, `ls en_US/Workspaces/`                                                                                               |
|  U15    | the file name and extension a saved menu set writes into `en_US/Menu Sets/`                                          | unverified (folder proven) | save, `ls`                                                                                                                                   |
|  U16    | `applicationBarShown = false` hides the app-bar buttons with the Application Frame on                                 | unverified               | [09] row 09                                                                                                                                    |
|  U17    | Generative AI pane contents on 21.6.0.58                                                                             | unverified               | window-id screenshot of the pane ([09] row 04); Adobe's FAQ page names two alt-text switches for shipping 21.4                                  |
|  U18    | `digitsType FARSI_DIGITS` vs `FULL_FARSI_DIGITS` rendering                                                            | unverified               | [09] row 12 captures                                                                                                                           |
|  U19    | `doc.changeComposer()` exists on a document instance and converts existing text                                      | unverified               | [09] row 12                                                                                                                                    |
|  U20    | camelCase enum spellings (`rightToLeftDirection`) in UXP                                                              | unverified               | [09] row 12                                                                                                                                    |
|  U21    | `Text Frame Fa` object style versus per-story `storyDirection` precedence when both set                               | unverified               | [09] row 12                                                                                                                                    |
|  U22    | `createGuides` with `fitMargins=true` places row guides at the margin, so f-guides are `guides.add`                  | decided, verify          | read `guides.everyItem().location` after the call                                                                                              |
|  U23    | Persian Hunspell dictionary availability through Preferences > Dictionary                                             | unverified, not needed   | Persian styles carry `[No Language]`; a dictionary is a later task                                                                             |
|  U24    | exact toolbox slot order and the double-column `size-variant` value in 21.6                                          | fact, recorded at [09] row 06 | screenshot and workspace XML                                                                                                              |
|  U26    | Half Letter, A6, and the B-series rows                                                                               | derived                  | `typographic-grid` `grid` target closes each within 0.001 pt before I3                                                                        |
|  U27    | `app.exportSettings` and `app.importSettings` argument form (in `reflect.methods`, absent from the UXP `a/application` page) | unverified        | call `app.exportSettings(File)` on a scratch path, `ls`; on success the user-settings export becomes a DOM step                                 |
|  U28    | `alignToBaseline` snaps a `CAP_HEIGHT` first baseline from 44.936 to 45.000 inside a frame placed at the f-guide     | unverified               | place a `Text Frame` at 35.450, type one line of `Body`, read `lines[0].baseline`                                                              |

'''
doc=doc[:a]+new10+doc[b:]
# ---- [11] sources: add rows
m=re.search(r"^\|  \[50\]   \| https://helpx\.adobe\.com/indesign/using/anchored-objects\.html.*$",doc,re.M)
assert m, "row 50 not found"
doc=doc[:m.end()]+"\n"+'|  [51]   | Refinement reads 2026-09-11 (`scratchpad/design/probe-gui/`): `r1.out` (version, `languagesWithVendors`, composer menu actions, `findKeyStrings`), `r2.out` (`generalPreferences`, `ToolsPanelOptions`), `enums.out` (105 enumerations), `props.out` (`reflect.properties` of 52 classes, `reflect.methods` of Application, current preference values), `r5.out` (`displaySettings`, the stock `[PDF/X-4:2008]` preset), `win.out` (System Events menus with checkmarks), `font-metrics.txt` (fontTools on the CoreSync `NHaasGroteskTXPro-55Rg`), `kelman-idml.txt` (seven IDML files), `splice07.py` (the size arithmetic) | 2026-09-11                      |\n|  [52]   | `~/Library/Preferences/Adobe InDesign (Beta)/Version 21.0/en_US/` listing (`Menu Sets/`, `InDesign Shortcut Sets/`, `Scripts/Scripts Panel/` empty; no `Swatch Libraries/`); `Presets/InDesign_Workspaces/en_US/*.xml` (11 files) and `Presets/InDesign Shortcut Sets/en_US/Default.indk`; `Contents/Resources/UXP/*/manifest.json` (`com.adobe.ccx.timeline` = Version History, `com.adobe.ccx.comments-webview`, `com.adobe.ccx.sharesheet`, `com.adobe.indesign.imageToLayoutPanel`); `Application UI.InDesignPlugin` string table (`_CurrentWorkspace`, `Menu Sets`, `^1Settings_^2`); Drive `99.Default Profiles/InDesign/Default Preflight.idpp` | 2026-09-11                      |\n|  [53]   | UXP DOM pages https://developer.adobe.com/indesign/uxp/dom/api/a/application/, t/table-style/, r/row/, h/hyperlink/, p/preflight-option/, t/toc-style/                                                                                                                                                                                                                              | fetched 2026-09-11              |'+doc[m.end():]
# ---- [12] rows
rep("units points, ruler origin page, kerning increment 5, leading and baseline-shift increments 1; baseline grid 15 pt relative to top margin, start f (9.549 pt for the reference face), shown, threshold 25 %; document grid 15 pt / 1; optical margin alignment on at 12.75; first baseline Cap Height; document defaults 612 × 792 pt, facing off, bleed 9 pt, primary text frame on, margins 35.451 / 102 / 45 / 45, 12 columns, gutter 15; autoGenerateAltText and addAITagToAltText false;",
    "units points, ruler origin page, kerning increment 5, leading and baseline-shift increments 1; baseline grid 15 pt relative to top margin (BaselineGridRelativeOption.TOP_OF_MARGIN_OF_BASELINE_GRID_RELATIVE_OPTION), start f (9.550 pt for the reference face), shown, threshold 25 %; document grid 15 pt / 1; greek type below 0 on the three displaySettings; optical margin alignment on at 12.75; first baseline Cap Height; text defaults otfFigureStyle PROPORTIONAL_LINING (live default DEFAULT_VALUE); document defaults 612 × 792 pt, facing off, bleed 9 pt, primary text frame on, margins 35.450 / 102 / 45 / 45, 12 columns, gutter 15; autoGenerateAltText and addAITagToAltText false;")
rep("column C icon dock: Transform; Character→Paragraph→Glyphs; Paragraph Styles→Character Styles; Object Styles→Table Styles→Cell Styles→Table; Text Wrap; Preflight→Separations Preview; Cross-References→Hyperlinks→Bookmarks; Data Merge→Conditional Text→Story; Buttons and Forms; Flex Layout; Info; Rasm InDesign Bridge; Stroke and Effects closed; Control off; every other Window-menu panel closed (gui-indesign.md [03]).",
    "column C icon dock: Transform; Character→Paragraph→Glyphs; Paragraph Styles→Character Styles; Object Styles→Table Styles→Cell Styles→Table; Text Wrap; Preflight→Separations Preview; Cross-References→Hyperlinks→Bookmarks; Data Merge→Conditional Text→Story; Buttons and Forms; Flex Layout; Rasm InDesign Bridge; Stroke, Effects, Info closed; Control off (already unchecked today); group heights mirror Illustrator's targets (220/220/remainder, 194/500/remainder); every other Window-menu panel closed (gui-indesign.md [03]).")
rep("| `the style graph of gui-indesign.md [06] (43 paragraph styles on Base, 15 character styles, 10 object styles, 1 table and 4 cell styles, 8 GREP rows, the Section Indicator mechanism, text variables, sections, TOC style, condition sets, footnote and endnote options, data-merge and form parents); parents A-Grid, B-Text, C-Cover, D-Contents, E-Merge, F-Form, every one based on A-Grid, page 1 on B-Text; geometry of gui-indesign.md [07]: 15 pt module, 12 columns × 29.75 pt with 15 pt gutters, margins 35.451 / 102 / 45 / 45, baseline grid start f relative to the top margin, 44 baselines, 5 rows of 8 lines, f-height guide layer required` |",
    "| `the style graph of gui-indesign.md [06] (40 named paragraph styles on Base including the four-member White group, 13 character styles, 9 object styles, 1 table and 4 cell styles, 8 GREP rows, the Section Indicator mechanism on the built-in text variables re-pointed, sections, TOC style, condition sets, footnote and endnote options with Note as both text styles, data-merge and form parents); parents A-Grid, B-Text, C-Cover, D-Contents, E-Merge, F-Form, every one based on A-Grid, page 1 on B-Text; geometry of gui-indesign.md [07]: 15 pt module, 12 columns × 29.75 pt with 15 pt gutters, margins 35.450 / 102 / 45 / 45, baseline grid start f = 9.550 relative to the top margin, 44 baselines, 5 rows of 8 lines, f-height guide layer required` |")
rep("| `19 INDT files named by dimension per gui-indesign.md [07] size table (per-size rebuild through apply_grid, page.adjustLayout never on the master); module per family from the Kelman ladder (8.5, 10, 11, 11.5, 12, 15, 36 pt; 45 px on 3840x2160; 50 px on 4000x2500, confirmed by whole-line fit); the digital parents A-Grid, B-Title, C-Section, D-Image-Led, E-Text-Led, F-Comparison, G-Diagram, H-Grid inside both digital files; technical families carry the ERDC B-Sheet parent` |",
    "| `37 INDT files named by dimension per the gui-indesign.md [07] catalogue (per-size rebuild through apply_grid, page.adjustLayout never on the master); module per family (7.5 A6; 8.5 A5 and Half Letter; 11.5 A1 and A2; 12 A3, Tabloid, boards, technical sheets; 15 Letter, Legal, A4; 36 A0; 45 px on 3840x2160; 50 px on 4000x2500, confirmed by whole-line fit); the digital parents A-Grid, B-Title, C-Section, D-Image-Led, E-Text-Led, F-Comparison, G-Diagram, H-Grid inside both digital files; ANSI, ARCH, and ISO technical sheets carry the ERDC B-Sheet parent` |")
rep("Default Preflight (24 active rules, gui-indesign.md [07]) through export_preflight_profile; five GREP queries (Collapse Ordinary Spaces, Trim Trailing Spaces and Tabs, Persian Yeh, Persian Kaf, Multiple Returns) through app.saveFindChangeQuery` |",
    "Default Preflight (24 active rules of the 38 ids, gui-indesign.md [07]; the live three-rule Codex profile rewritten in place) through export_preflight_profile and app.loadPreflightProfile; five GREP queries (Collapse Ordinary Spaces, Trim Trailing Spaces and Tabs, Persian Yeh, Persian Kaf, Multiple Returns) through app.saveFindChangeQuery; swatches through app.loadSwatches(File) on the .ase` |")
rep("Find-Change Queries/GREP/ (5), Sizes/ (19), Default Palette.ase, data-merge-sample.csv; Shared/Default Color Settings.csf once`",
    "Find-Change Queries/GREP/ (5), Sizes/ (37), Default Palette.ase, data-merge-sample.csv; Shared/Default Color Settings.csf once`")
rep("the I4 readback table (U1–U6, U18–U21) attached to roles.json before I2`","the I4 readback table (U1, U2, U5, U6, U18–U21) attached to roles.json before I2`")
rep("| `the 43 paragraph roles, 15 character roles, 10 object, 1 table, 4 cell roles of gui-indesign.md [06], with the Section Indicator (GREP-split N / N), Body First, Table Total, Endnote Title, Endnote, Footnote, Figure Caption, Table Caption, Form Label, Indicator Left/Right, Digits Fa/Ar, Latin in RTL added`",
    "| `the 40 paragraph roles (Heading is the third level, Note is the footnote and endnote text, Section Indicator is the folio, the White group of four carries the deck's dark variants), 13 character roles (Accent, Muted, Digits Fa, Latin in RTL added; no Superscript beside Note Reference), 9 object, 1 table, 4 cell roles of gui-indesign.md [06], with the Section Indicator (GREP-split N / N on the built-in Last Page Number), Body First, Table Total, Table Caption, Form Label added`")
rep("for the top margin k·L − f and the f-height guides, and from sCapHeight/upm for the first-baseline check, never the 656/1000 constant; the Letter grid is 12 columns × 29.75 pt, gutter 15, margins 35.451 / 102 / 45 / 45, 44 baselines, 5 rows of 8 lines`",
    "for the top margin 3L − f and the f-height guides, and from sCapHeight/upm (744/1000, 9.486 pt) for the first-baseline check, never the 656/1000 constant; the Letter grid is 12 columns × 29.75 pt, gutter 15, margins 35.450 / 102 / 45 / 45 (f = 9.54975, written 9.550), 44 baselines, 5 rows of 8 lines`")
rep("| `the 19 rows of gui-indesign.md [07] with module, body, sides, column, rows, last baseline, bottom, folio per row; Digital 4000x2500 at 50 px module (confirmed) and Digital 3840x2160 at 45 px`",
    "| `the 37 files of the gui-indesign.md [07] catalogue with module, body, sides, column, top, rows, last baseline, bottom, folio per row (recomputed 2026-09-11: A5 column 22.919, A3 column 53.158, A2 82.921, A0 147.661); Digital 4000x2500 at 50 px module (80 × 50 whole) and Digital 3840x2160 at 45 px (48 lines whole, width 85.33 modules with whole sides and gutters)`")
rep("| `4000×2500 px is confirmed: module 50 px, body 42.5/50, 80 × 50 whole modules, 12 columns × 262.5 px with 50 px gutters, 6 rows of 5 lines with 2-line gutters, last baseline 2100, footer baseline 2300`",
    "| `4000×2500 px is confirmed: module 50 px, body 42.5/50, 80 × 50 whole modules, 12 columns × 262.5 px with 50 px gutters, sides 150, top 118.168 (3 L − f), 6 rows of 5 lines with 2-line gutters (40 lines), last baseline 2100, bottom 400 (8 L), footer line 46 at 2300 (last + 4 L)`")
rep("Kelman's flat styles and size-in-name convention are rejected, roles chain from Base; a White group of role styles based on their black parents carries the dark variants`",
    "Kelman's flat styles and size-in-name convention are rejected, roles chain from Base; the White group (White/Title, White/Contents L1, White/Running Header, White/Section Indicator, fillColor Paper on their black parents) carries the dark variants`")
# ---- [13]
rep("| 73 Window-menu rows with one verdict each; 34 docked in three columns; every other panel closed                                                                          | [03]                       | workspace CDATA diff; screenshot                                                                    |",
    "| 70 Window-menu rows and 3 Plug-Ins rows with one verdict each; 33 docked in three columns; every other panel closed                                                    | [03]                       | workspace CDATA diff; screenshot                                                                    |")
rep("| `Default Template.indt`, 43 + 15 + 10 + 1 + 4 styles, six parents, geometry closed to 0.001 pt                                                                          | [06], [07]                 | reopen Untitled; readback equals `styles-graph.json`                                                |",
    "| `Default Template.indt`, 40 + 13 + 9 + 1 + 4 styles, six parents, geometry closed to 0.001 pt                                                                           | [06], [07]                 | reopen Untitled; readback equals `styles-graph.json`                                                |")
rep("| 19 files, per-size rebuild, module per family, rows by rule                                                                                                             | [07] size table            | each reopens with its trim, leading, margins                                                        |",
    "| 37 files, per-size rebuild, module per family, rows by rule, every row recomputed                                                                                       | [07] size table            | each reopens with its trim, leading, margins                                                        |")
rep("| 24 rows, each `pref`, `panel`, `menu`, `bundle` (untouched, signed), or `bar` (recorded)                                                                                 | [05] AI table              | menus read; panels absent; Generative AI pane screenshot                                            |",
    "| 25 rows, each `pref`, `panel`, `menu`, `bundle` (untouched, signed), or `bar` (recorded)                                                                                 | [05] AI table              | menus read; panels absent; Generative AI pane screenshot                                            |")
rep("| 13 rows, body 12.75/15 on grid, `Base` chain for named styles                                                                                                           |","| 13 rows, body 12.75/15 on grid, figures PROPORTIONAL_LINING, `Base` chain for named styles                                                                              |")
# header channels: note the addition
rep("`FILE` = a file on disk; `SHOT` = `screencapture -l <windowId>` read with zoom.","`FILE` = a file on disk; `SHOT` = `screencapture -l <windowId>` read with zoom. Every server tool named here exists in architecture.md [06.3]; the one required addition is the `fTop` field of `get_font_metrics` ([09]).")
open(p,"w",encoding="utf-8").write(doc)
print("done")
