import re
p="../gui-indesign.md"; doc=open(p,encoding="utf-8").read()
def rep(old,new,count=1):
    global doc
    assert doc.count(old)==count,(old[:90],doc.count(old)); doc=doc.replace(old,new)
# A. language lookup
doc=doc.replace('`appliedLanguage=app.languagesWithVendors.item("[No Language]")`','`appliedLanguage="[No Language]"`')
doc=doc.replace('`appliedLanguage=item("[No Language]")`','`appliedLanguage="[No Language]"`')
rep("|  [05]   | `appliedLanguage`                                          | `app.languagesWithVendors.item(name)` object, never a string in UXP; `[No Language]`, `Arabic`, `Hebrew`, `English: USA` are names in the 61-entry list read live                                                                                                         |",
    "|  [05]   | `appliedLanguage`                                          | the bracketed `[No Language]` name is not resolvable by `languagesWithVendors.item(name)` or `itemByName` (both return an invalid object, read live on a scratch document); assign the string `\"[No Language]\"` (or `\"$ID/[No Language]\"`, or `item(0)`), the assignment reads back `[No Language]`; `item(\"Arabic\")`, `item(\"English: USA\")`, and the strings `\"Arabic\"`, `\"English: USA\"` all work; `app.languages` does not exist |")
rep("Language: Persian roles carry `[No Language]` because","Language: Persian roles carry `[No Language]` (assigned as the string, see traps row 05) because")
# B. tabList
rep("|  [07]   | `tabList`                                                  | array of `{alignment, position, leader}` (`alignmentCharacter` for CHARACTER_ALIGN); assignment replaces every tab; the gui-stream \"rejected\" report concerned `[]` and is [10] row U9                                                                                     |",
    "|  [07]   | `tabList`                                                  | array of `{alignment, position, leader}` (`alignmentCharacter` for CHARACTER_ALIGN); assignment replaces every tab; `tabList = []` is accepted on 21.6.0.58 and reads back `length 0` (live scratch document, so the gui-stream \"rejected\" report does not hold on this build); objects read back with `position` and `alignment` |")
rep("tabList takes an array of {alignment, position, leader} objects and never [] (proof U9 in gui-indesign.md)`","tabList takes an array of {alignment, position, leader} objects and accepts [] to clear (read live on 21.6.0.58, gui-indesign.md traps row 07)`")
# C. nested vs GREP
rep("GREP styles evaluate per paragraph; nested styles run in list order; a nested style beats a nested line style on the same attribute; GREP versus nested precedence in the general case is [10] row U1 (Adobe's GREP-styles page rendered only its navigation through every allowed channel on 2026-09-11); ZWNJ is stripped inside variables |",
    "GREP styles evaluate per paragraph; nested styles run in list order; a nested style beats a nested line style on the same attribute; a nested style beats a GREP style on the same attribute and the earlier GREP row beats a later one (live scratch document: nested Italic over GREP Bold reads `Italic`; GREP Italic then GREP Bold reads `Italic`; GREP Bold then GREP Italic reads `Bold`); ZWNJ is stripped inside variables |")
rep("Indicator mechanism (`N / N` with two colors from one paragraph style and the built-in text variables, no nested style; the two GREP expressions are disjoint, the left one excludes `/` and the right one starts after it, so no overlap or precedence question arises inside the indicator):",
    "Indicator mechanism (`N / N` with two colors from one paragraph style and the built-in text variables, no nested style; the two GREP expressions are disjoint, the left one excludes `/` and the right one starts after it, so the precedence rule below never applies inside the indicator):")
# D. table rows
rep("Table and cell styles. Rows sit on the module when a one-line row measures one module: table paragraph styles at 15 pt leading, cell `firstBaselineOffset=LEADING_OFFSET`, vertical insets 0, horizontal insets 5, table text `alignToBaseline=false`, the `Table Frame` starting on a grid line; whether InDesign's auto row height adds the last line's descent is [10] row U5, and when it does the table build fixes each row with `row.autoGrow=false; row.height=\"<lines × 15>pt\"` (Row properties `autoGrow`, `height`, `minimumHeight`, `maximumHeight` on the UXP `r/row` page); 3 pt vertical insets (the Codex value) would put a one-line row at 21 pt, so they are gone. Row strokes separate rows; no alternating fill (one mechanism per job).",
    "Table and cell styles. InDesign's auto row height does not land on the module: with table paragraph styles at 15 pt leading, cell `firstBaselineOffset=LEADING_OFFSET`, `minimumFirstBaselineOffset=0`, vertical insets 0, horizontal insets 5, and `alignToBaseline=false`, a one-line row measures 16 pt and a two-line row 31 pt (15n + 1, read live on a scratch document), so the table build fixes every row with `row.autoGrow=false; row.height=\"<lines × 15>pt\"` (Row properties `autoGrow`, `height`, `minimumHeight`, `maximumHeight`, UXP `r/row` page; a two-line row forced to 15 pt oversets, so the line count per row is read first) and the `Table Frame` starts on a grid line; 3 pt vertical insets (the Codex value) are gone. Row strokes separate rows; no alternating fill (one mechanism per job).")
# E. app bar read-only
rep("| no preference and no `Window > Application Bar` item in 21.6 (Window menu read live); Adobe (workspace basics, 2026-05-26): on macOS the bar is part of the frame; `applicationBarShown false` is tested once in [09] row 09 and the result recorded                                                                                            | `bar`, exception recorded      |",
    "| no preference and no `Window > Application Bar` item in 21.6 (Window menu read live); Adobe (workspace basics, 2026-05-26): on macOS the bar is part of the frame; `generalPreferences.applicationBarShown` is a read-only property (assignment raises error 30474, read live), and the AX tree of window 1 lists `Home`, `Share`, `AI Assistant (beta)`, `What's new in Beta`, `Provide feedback`, `UI_SearchBoxBase` | `bar`, exception proven        |")
rep("|  [34]   | Interface         | Application frame / bar                     | `useApplicationFrame`, `applicationBarShown`           | true / true                      | keep                              | DOM       |",
    "|  [34]   | Interface         | Application frame / bar                     | `useApplicationFrame`, `applicationBarShown` (read-only, error 30474 on write) | true / true          | keep                              | DOM       |")
rep("|  [09]   | app-bar test: `generalPreferences.applicationBarShown = false`, screenshot, then `true`; record whether Home, Share, AI Assistant, What's new, feedback, search survive | DOM, SHOT                                  | `08-appbar-off.png`, `08-appbar-on.png`, row in the consistency file                                        |",
    "|  [09]   | app-bar record: `applicationBarShown` is read-only (settled 2026-09-11); dump `{description, role} of every UI element of window 1` (System Events) and screenshot the bar; the six buttons go into the consistency file as the exception | AX read, SHOT                              | `08-appbar-ax.txt`, `08-appbar.png`, row in the consistency file                                            |")
rep("`Default Menu Set` hides the listed commands; the app-bar buttons that no preference removes are recorded as the one exception with their screenshot |",
    "`Default Menu Set` hides the listed commands; the app-bar buttons (`applicationBarShown` is read-only; AX lists Home, Share, AI Assistant (beta), What's new in Beta, Provide feedback, search) are the one exception, recorded with their screenshot |")
rep("are one recorded exception when the [09] row 09 test shows no preference removes them`","are the one recorded exception: generalPreferences.applicationBarShown is read-only on 21.6.0.58 (error 30474) and the AX tree lists the six controls`")
rep("| `showStartWorkspace false`, `showWhatsNewOnStartup false`; app-bar buttons recorded                                                                                     |","| `showStartWorkspace false`, `showWhatsNewOnStartup false`; app-bar buttons recorded (`applicationBarShown` read-only)                                                   |")
# F. Generative AI pane
rep("|  [84]   | Generative AI     | every toggle (generative features, credits, Text to Image entry points) | none                                | on (shipping default)            | every checkbox off                | SHOT      |",
    "|  [84]   | Generative AI     | `Auto-generate Alt Text when placing images`; `Add \"AI generated content\" tag for auto-generated Alt Text` (the pane's two switches on Adobe's alt-text page, 2026-02-03) | `generalPreferences.autoGenerateAltText`, `addAITagToAltText` (row 11) | false / true | false / false; a screenshot of the Beta pane records any switch beyond the two | DOM + SHOT |")
rep("| panel closed; the three menu items hidden (`menu`); Preferences > Generative AI every toggle off (`SHOT`); the CTB entry and app-bar button have no preference (`bar`, recorded)",
    "| panel closed; the three menu items hidden (`menu`); Preferences > Generative AI holds the two alt-text switches only (row 11, `pref`); the CTB entry and app-bar button have no preference (`bar`, recorded)")
rep("| panel closed; both menu items hidden; Preferences > Generative AI off; Quick Actions and CTB entries have no preference (recorded)",
    "| panel closed; both menu items hidden; the two Generative AI preferences off (row 11); Quick Actions and CTB entries have no preference (recorded)")
rep("| dialog-only rows [05] 30, 31, 35–37, 44, 47, 48, 80, 84:","| dialog-only rows [05] 30, 31, 35–37, 44, 47, 48, 80 (and the row 84 pane screenshot):")
rep("Generative AI pane every toggle off;","the two Generative AI preferences (autoGenerateAltText, addAITagToAltText) false;")
# G. size table B rows, Half Letter, A6
rep("|  [04]   | US loose | `Half Letter 5.5x8.5` 396 × 612 | 8.5 | 7.225/8.5 | 25.5 | 20.958 | 20.088 | 4 × 5 by rule | by rule | ≥ 34 | +25.5 |",
    "|  [04]   | US loose | `Half Letter 5.5x8.5` 396 × 612 | 8.5 | 7.225/8.5 | 25.5 | 20.958 | 20.088 | 4 × 5, 12 L, gutter 1 L (64 lines) | 561 | 51 | 586.5 |")
rep("|  [08]   | ISO A small | `A6 105x148` 297.638 × 419.528 | 7.5 | 6.375/7.5 | 22.5 | 14.178 | 17.725 | 4 × 5 by rule | by rule | ≥ 30 | +22.5 |",
    "|  [08]   | ISO A small | `A6 105x148` 297.638 × 419.528 | 7.5 | 6.375/7.5 | 22.5 | 14.178 | 17.725 | 4 × 5, 9 L, gutter 1 L (49 lines) | 382.5 | 37.028 | 405 |")
brow="|  [13]   | ISO B | `B0 1000x1414` … `B6 125x176` | L of the A size the sheet encloses (Bn encloses An) | 0.85 L | 3 L | by rule | 3 L − f | rows of the enclosed A size by rule | by rule | ≥ 4 L | +3 L |"
bnew="""|  [13]   | ISO B (L of the enclosed A size) | `B0 1000x1414` 2834.646 × 4008.189 | 36 | 30.6/36 | 108 | 185.22 | 85.081 | 4 × 6, 15 L, gutter 2 L (100 lines) | 3672 | 336.189 | 3780 |
|  [14]   | ISO B | `B1 707x1000` 2004.094 × 2834.646 | 11.5 | 9.775/11.5 | 34.5 | 150.716 | 27.179 | 4 × 6, 39 L, gutter 1 L (239 lines) | 2771.5 | 63.146 | 2806 |
|  [15]   | ISO B | `B2 500x707` 1417.323 × 2004.094 | 11.5 | 9.775/11.5 | 34.5 | 101.819 | 27.179 | 4 × 6, 27 L, gutter 1 L (167 lines) | 1943.5 | 60.594 | 1978 |
|  [16]   | ISO B | `B3 353x500` 1000.63 × 1417.323 | 12 | 10.2/12 | 36 | 66.386 | 28.360 | 4 × 6, 17 L, gutter 2 L (112 lines) | 1368 | 49.323 | 1404 |
|  [17]   | ISO B | `B4 250x353` 708.661 × 1000.63 | 15 | 12.75/15 | 45 | 37.805 | 35.450 | 4 × 5, 11 L, gutter 1 L (59 lines) | 915 | 85.63 | 960 |
|  [18]   | ISO B | `B5 176x250` 498.898 × 708.661 | 8.5 | 7.225/8.5 | 25.5 | 29.533 | 20.088 | 4 × 5, 14 L, gutter 1 L (74 lines) | 646 | 62.661 | 671.5 |
|  [19]   | ISO B | `B6 125x176` 354.331 × 498.898 | 7.5 | 6.375/7.5 | 22.5 | 18.903 | 17.725 | 4 × 5, 11 L, gutter 1 L (59 lines) | 457.5 | 41.398 | 480 |"""
rep(brow,bnew)
for old,new in [("|  [14]   | ISO technical","|  [20]   | ISO technical"),("|  [15]   | digital 16:9","|  [21]   | digital 16:9"),("|  [16]   | digital 16:10","|  [22]   | digital 16:10"),("|  [17]   | competition board","|  [23]   | competition board"),("|  [18]   | competition A1","|  [24]   | competition A1")]:
    rep(old,new)
rep("Every row below is closed by the formulas above (probe-gui/splice07.py recomputed them on 2026-09-11); the `typographic-grid` `grid` target reproduces each within 0.001 pt before I3.",
    "Every row below is closed by the formulas above (probe-gui/splice07.py and the B-series computation recomputed them on 2026-09-11; lines per row = the largest whole number leaving bottom ≥ 4 L); the `typographic-grid` `grid` target reproduces each within 0.001 pt before I3.")
# H. ERDC paragraph
a=doc.index("ERDC sheet parent `B-Sheet`"); b=doc.index("\n",a)
doc=doc[:a]+"ERDC sheet parent `B-Sheet` for the technical families (ERDC/ITL SR-23-1, A/E/C Graphics Standard Release 2.2, August 2023, read from the PDF on 2026-09-11): sheet margin ≥ 3/16 in (13.5 pt) from the paper edge, borders shifted right to keep a binding edge on the left (§2.1.2) → border 24 pt (2 L); three areas: Production Data Area (optional, outside the drawing-area border in the upper right corner, Figure 2-2), Drawing Area, Title Block Area (a vertical title block in the right-hand margin, Figure 2-6, holding Designer Identification, Revision, Management, Project Identification / Sheet Title, Sheet Identification blocks, not resizable) (§2.1.3–2.1.6); modules 1½ in × 1½ in = 108 pt (9 L), grid letters A, B, C … from lower left upward and numbers 1, 2, 3 … left to right, I and O skipped, a graphic fills whole drawing blocks (§2.1.5); text 3/32 in (6.75 pt) for notes, dimensions, callouts, and tables, titles 3/16 in (13.5 pt), subtitles 1/8 in (9 pt), line spacing one-half the text height (§5); ANSI D is the contract sheet, E and F for oversized, ISO A1 international, A0 oversized (§2.1.1). On the 12 pt module the ladder steps at or above those heights: notes 10.2/12 (cap 7.59), subtitles 15.3/18 (cap 11.4), titles 20.4/24 (cap 15.2), line pitch = 1.5 × text height as the standard's half-height spacing; the title block strip is one module (108 pt) wide plus the border, the width Figure 2-1 shows (the Center's border sheet files at cadbimcenter.erdc.dren.mil hold the exact value; the 0.75 L step disabled)."+doc[b:]
# I. PDF presets export format
rep("|  [03]   | on disk          | `app.exportPresets(ExportPresetFormat.PDF_EXPORT_PRESETS_FORMAT, File(\"<Drive>/…/InDesign/Default Print.joboptions\"))` and the same for Digital; copies into `~/Library/Application Support/Adobe/Adobe PDF/Settings/` for Acrobat and Illustrator; readback `app.pdfExportPresets.item(name).properties` and `effectivePDFDestinationProfile`, `effectiveOutputCondition` non-empty for `Default Print`",
    "|  [03]   | on disk          | `app.exportPresets(ExportPresetFormat.PDF_EXPORT_PRESETS_FORMAT, File)` writes one InDesign container for every PDF preset (binary, signature `InDnPdfS`, 548,864 bytes for the six stock presets, each preset's `.joboptions` dictionary embedded as text after `@[name]`; read live into the scratchpad), which `app.importFile(PDF_EXPORT_PRESETS_FORMAT, File)` reads back; the per-preset `.joboptions` Acrobat Distiller and Illustrator load comes from `File > Adobe PDF Presets > Define… > Save As…` (CU, one file per preset) into `~/Library/Application Support/Adobe/Adobe PDF/Settings/`; readback `app.pdfExportPresets.item(name).properties` and `effectivePDFDestinationProfile`, `effectiveOutputCondition` non-empty for `Default Print`")
rep("| `~/Library/Application Support/Adobe/Adobe PDF/Settings/Default Print.joboptions`, `Default Digital.joboptions` (the user folder is empty today; ten stock files in `/Library/…`) | `Default Print.joboptions`, `Default Digital.joboptions` | `app.pdfExportPresets.everyItem().name` includes both (six stock names today); `File > Adobe PDF Presets` lists both; Acrobat Distiller lists both ([10] row U10)     |",
    "| `~/Library/Application Support/Adobe/Adobe PDF/Settings/Default Print.joboptions`, `Default Digital.joboptions` from the Define dialog (the user folder is empty today; ten stock files in `/Library/…`); the `exportPresets` container beside them as `Default PDF Presets` | `Default Print.joboptions`, `Default Digital.joboptions`, `Default PDF Presets` | `app.pdfExportPresets.everyItem().name` includes both (six stock names today); `File > Adobe PDF Presets` lists both; the `.joboptions` text opens in Distiller |")
rep("|  [08]   | PDF presets                                  | `app.exportPresets(ExportPresetFormat.PDF_EXPORT_PRESETS_FORMAT, File)`                                            |","|  [08]   | PDF presets                                  | Define dialog Save As… per preset (CU); `app.exportPresets(PDF_EXPORT_PRESETS_FORMAT, File)` for the container |")
# J. user settings
rep("User settings: `File > User Settings > Export User Settings…` (present in the live File menu) → `Default User Settings` (Adobe bundles Preferences, Workspaces, Menu sets, Keyboard shortcuts, Glyph sets; the dialog's default name pattern is `^1Settings_^2` in the Application UI string table; the extension it writes is recorded at export, [10] row U11; `app.exportSettings` and `app.importSettings` exist in `app.reflect.methods` on 21.6.0.58 with no argument metadata and no UXP page, [10] row U27);",
    "User settings: `app.exportSettings(File(\"<path>/Default User Settings\"))` (undocumented on the UXP page, present in `app.reflect.methods`; run live on 2026-09-11 with no dialog and `modalState false`: it wrote a 6,844,416-byte SQLite 3 database with tables `Metadata` (`Locale en_US`, `MajorVersion 21`, `MinorVersion 6`, `Platform mac`, `ProductType Beta`) and `FileStore` (`FileType`, `Name`, `Data`: `Essentials_CurrentWorkspace.xml`, `Start_CurrentWorkspace.xml`, `InDesign Defaults.idms`, `InDesign Defaults`), so the export is a DOM step; the menu item `File > User Settings > Export User Settings…` writes the same bundle with the default name `IDSettings_…` (Adobe, export-and-import-user-settings, 2026-06-02) and no documented extension; `app.importSettings(File)` is not run (it replaces the settings and restarts InDesign); Adobe bundles Preferences, Workspaces, Menu sets, Keyboard shortcuts, Glyph sets;")
m=re.search(r"^\|  \[07\]   \| user settings bundle.*$",doc,re.M); assert m
doc=doc[:m.start()]+"|  [07]   | user settings bundle                         | `app.exportSettings(File)` (DOM; SQLite 3 bundle, proven live)                                                    | chosen path                                                                                                            | `Default User Settings` (no extension; SQLite)   | import is not run; `sqlite3 … \"select Name from FileStore\"` lists the workspace, menu-set, shortcut, and defaults files                                          |"+doc[m.end():]
rep("Default User Settings.<extension recorded at export>,","Default User Settings (a SQLite bundle written by app.exportSettings(File)),")
rep("File > User Settings > Export User Settings… as Default User Settings (Adobe resets","app.exportSettings(File) as Default User Settings (a SQLite 3 bundle; Adobe resets")
rep("| exports: `exportPresets` → `.joboptions`; `export_preflight_profile`; `File > User Settings > Export User Settings…`; copy the [08] set to Drive; hashes","| exports: Define dialog Save As… per PDF preset and `exportPresets` for the container; `export_preflight_profile`; `app.exportSettings(File)`; copy the [08] set to Drive; hashes")
# K. workspace and menu set file names
rep("| `en_US/Workspaces/Default Workspace_CurrentWorkspace.xml` (`_CurrentWorkspace` is the `PW_CurrentWorkspaceSuffix` string of the Application UI plug-in; the saved-set file beside it is [10] row U14) | `Default Workspace.xml`                          |",
    "| `en_US/Workspaces/Default Workspace.xml` (the saved set) and `Default Workspace_CurrentWorkspace.xml` (the live state InDesign keeps beside it; Reset restores the saved set): LinkedIn Learning InDesign Secrets 203 (`EPUB.xml` and `EPUB_CurrentWorkspace.xml`), CreativePro 2010-01-14, Adobe community 2025-08-08 (macOS `…/Version N/en_xx/Workspaces`), graphicdesign.stackexchange (`Workspaces/GLS.xml`) | `Default Workspace.xml`                          |")
rep("| `en_US/Menu Sets/<file>` (folder proven by the plug-in string table; file name [10] row U15); workspace XML `<menu-set name>` | `Menu Sets/<file>` and the name inside `Default Workspace.xml` |",
    "| `en_US/Menu Sets/<Default Menu Set file>` (Adobe, preferences and support file locations, 2026-06-02: the Roaming Data folder holds the `Menu Sets` folder; the plug-in string table writes into it; the file's extension is read at save); workspace XML `<menu-set name>` | `Menu Sets/<file>` and the name inside `Default Workspace.xml` |")
rep("the set is written into `en_US/Menu Sets/` (the folder exists and is empty today; the Application UI plug-in's string table names it: \"Failed to write menu set. The Menu Sets folder may be locked.\"; file name and extension recorded at save, [10] row U15)",
    "the set is written into `en_US/Menu Sets/` (Adobe's preferences-locations page, 2026-06-02; the folder exists and is empty today; the Application UI plug-in's string table: \"Failed to write menu set. The Menu Sets folder may be locked.\"; the file's extension is read at save)")
# T/U geometry rows
rep("| `createGuides(5, 4, \"15pt\", \"15pt\", UIColors.GREEN, true, false, Grid)` for rows and majors; `guides.add` per sub-column and f-guide |",
    "| `createGuides(5, 4, \"15pt\", \"15pt\", UIColors.GREEN, true, false, Grid)` for rows and majors (with `fitMargins=true` it places row guides at margin top + k × (row + gutter), read live: 36, 168, 183, 315 … on a 36 pt master margin), so the f-guides come from `guides.add` |")
rep("| cap height 744/1000 × 12.75 = 9.486 pt; a `Text Frame` (`CAP_HEIGHT`) placed at the f-guide puts its unsnapped first baseline at 35.450 + 9.486 = 44.936; `alignToBaseline` snaps it to 45.000 (0.064 pt)  | `sCapHeight/upm`, the first-baseline check of the typography plan §05        |",
    "| cap height 744/1000 × 12.75 = 9.486 pt; a `Text Frame` (`CAP_HEIGHT`) placed at the f-guide puts its unsnapped first baseline at 44.936 and `alignToBaseline` snaps it to 45.000, the second line at 60 (read live on a scratch document: `lines[0].baseline` 44.9362 unsnapped, 45 snapped) | `sCapHeight/upm`, the first-baseline check of the typography plan §05        |")
# digits sentence
rep("Digits: Arabic roles take `HINDI_DIGITS` (٠١٢٣): Adobe's Arabic default is Hindi digits (arabic-hebrew page, 2025-07-18) and `DigitsTypeOptions.ARABIC_DIGITS` means Western 0–9; Persian roles take `FARSI_DIGITS` (۰۱۲۳, U+06F0–06F9).",
    "Digits: Arabic roles take `HINDI_DIGITS` (٠١٢٣): Adobe's Arabic default is Hindi digits (arabic-hebrew page, 2025-07-18) and `DigitsTypeOptions.ARABIC_DIGITS` means Western 0–9; Persian roles take `FARSI_DIGITS` (۰۱۲۳, U+06F0–06F9). Rendering read live (Adobe Arabic, JPEG export of a scratch page, probe-gui/live/digits-crop.png): `digitsType` converts Western digits only and never touches digits typed as U+0660–0669 or U+06F0–06F9; `FARSI_DIGITS` and `FULL_FARSI_DIGITS` render identically; `HINDI_DIGITS` turns Western into Arabic-Indic; `DEFAULT_DIGITS` leaves Western digits Western.")
open(p,"w",encoding="utf-8").write(doc); print("part1 ok")
