<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup Label="Bridge Test Harness">
        <PackageReference Include="Nerdbank.Streams" PrivateAssets="all" />
        <PackageReference Include="StreamJsonRpc" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Label="Project References">
        <ProjectReference Include="../../../../../tools/rhino-bridge/Contract/Contract.csproj" />
    </ItemGroup>
</Project>
