<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Rhino render contents, texture mappings, and scene settings as IO effects over RhinoCommon</Description>
    </PropertyGroup>

    <ItemGroup Label="Rhino Dependencies">
        <PackageReference Include="System.Drawing.Common" />
    </ItemGroup>

    <ItemGroup Label="Core Dependencies">
        <PackageReference Include="LanguageExt.Core" />
        <PackageReference Include="Riok.Mapperly" PrivateAssets="all" />
        <PackageReference Include="Thinktecture.Runtime.Extensions" />
    </ItemGroup>

    <ItemGroup Label="Workspace Packages">
        <ProjectReference Include="../Rasm.Rhino.Document/Rasm.Rhino.Document.csproj" />
    </ItemGroup>
</Project>
