namespace Radyab.Components;

[IoId("B88A1248-28B8-4F87-A178-6BCBD2458B33")]
[Nomen(
    name: "Extract Curves",
    info: "All, boundary, mid-domain U/V iso, and index-clamped curves from Rhino curve, surface, Brep, SubD, and mesh topology values.",
    category: "Radyab",
    section: "Extraction")]
public sealed class ExtractCurves : Component<ExtractCurves> {
    [Input(order: 0)] private readonly Port<Shape> Geometry = Port.Required<Shape>(kind: PortKind.Generic, name: "Geometry", code: "G", info: "Geometry to analyse.");
    [Input(order: 1)] private readonly Port<int> Index = Port.Index(info: "Zero-based curve selector; missing Index defaults to curve 0 and supplied values clamp to [0, count-1].");
    [Input(order: 2)] private readonly Port<Vector3d> Direction = Port.Optional<Vector3d>(name: "Direction", code: "D", info: "Parallel projection or pull direction for silhouette and draft extraction. Missing Direction uses world Z.", policy: PortPolicy.Vector(unitise: true));
    [Input(order: 3)] private readonly Port<Angle> DraftAngle = Port.Optional<Angle>(kind: PortKind.Angle, name: "Draft Angle", code: "A", info: "Draft angle for draft-curve extraction. Missing Draft Angle uses 0 radians.", policy: PortPolicy.Angle(reduce: true));
    [Output(order: 0)] private IOutputGroup AllCurves => Output.CurveDetails(input: Geometry, curves: Port.List<Curve>(name: "All Curves", code: "AC", info: "All native curve pieces: structural curve segments, Brep/SubD edges, surface boundary iso curves, or mesh topology edge curves."), sources: Port.List<ComponentIndex>(kind: PortKind.Generic, name: "Curve Sources", code: "CS", info: "Component index aligned with All Curves."), features: Port.List<CurveFeature>(kind: PortKind.Enum(initial: CurveFeature.Input), name: "Curve Features", code: "CF", info: "Feature label aligned with All Curves."), aspect: static (_, _) => Curves.All, emptyUnsupported: true);
    [Output(order: 1)] private IOutputGroup Segments => CurvesOutput(port: Port.List<Curve>(name: "Segments", code: "S", info: "Structural segments from the curve data model, Brep/SubD edges, or mesh topology edge lines."), aspect: Rasm.Analysis.Curves.Segments);
    [Output(order: 2)] private IOutputGroup SubCurves => CurvesOutput(port: Port.List<Curve>(name: "Sub Curves", code: "SCV", info: "Geometry-based curve subcurves, matching Rhino explode-style curve decomposition."), aspect: Rasm.Analysis.Curves.SubCurves);
    [Output(order: 3)] private IOutputGroup Boundary => CurvesOutput(port: Port.List<Curve>(name: "Boundary Curves", code: "BC", info: "Boundary curves: naked Brep/mesh edges, surface/face boundary iso curves, or the input curve itself."), aspect: Rasm.Analysis.Curves.Boundary);
    [Output(order: 4)] private IOutputGroup NakedOuter => CurvesOutput(port: Port.List<Curve>(name: "Naked Outer", code: "NO", info: "Outer naked Brep edges; mesh naked boundary polylines where mesh topology has no inner/outer split."), aspect: Rasm.Analysis.Curves.NakedOuter);
    [Output(order: 5)] private IOutputGroup NakedInner => CurvesOutput(port: Port.List<Curve>(name: "Naked Inner", code: "NI", info: "Inner naked Brep loop edges."), aspect: Rasm.Analysis.Curves.NakedInner);
    [Output(order: 6)] private IOutputGroup Interior => CurvesOutput(port: Port.List<Curve>(name: "Interior Edges", code: "IE", info: "Brep interior edges and mesh topology edges with exactly two connected faces."), aspect: Rasm.Analysis.Curves.Interior);
    [Output(order: 7)] private IOutputGroup NonManifold => CurvesOutput(port: Port.List<Curve>(name: "Non-Manifold Edges", code: "NE", info: "Brep non-manifold edges and mesh topology edges with more than two connected faces."), aspect: Rasm.Analysis.Curves.NonManifold);
    [Output(order: 8)] private IOutputGroup OuterLoops => CurvesOutput(port: Port.List<Curve>(name: "Outer Loops", code: "OL", info: "Brep outer loop curves."), aspect: Rasm.Analysis.Curves.OuterLoop);
    [Output(order: 9)] private IOutputGroup InnerLoops => CurvesOutput(port: Port.List<Curve>(name: "Inner Loops", code: "IL", info: "Brep inner loop curves."), aspect: Rasm.Analysis.Curves.InnerLoop);
    [Output(order: 10)] private IOutputGroup IsoU => CurvesOutput(port: Port.List<Curve>(name: "U Iso Curves", code: "U", info: "Trim-aware mid-domain U-direction iso curves for Brep faces and surface values."), aspect: Rasm.Analysis.Curves.IsoU);
    [Output(order: 11)] private IOutputGroup IsoV => CurvesOutput(port: Port.List<Curve>(name: "V Iso Curves", code: "V", info: "Trim-aware mid-domain V-direction iso curves for Brep faces and surface values."), aspect: Rasm.Analysis.Curves.IsoV);
    [Output(order: 12)] private IOutputGroup Silhouette => Output.Query(input: Geometry, port: Port.List<Curve>(name: "Silhouette Curves", code: "SC", info: "Parallel-projection silhouette curves using Direction, defaulting to world Z."), operation: (access, runtime) => Query.Curves<object, Curve>(aspect: Rasm.Analysis.Curves.Silhouette(direction: runtime.Nullable(access: access, port: Direction))), emptyUnsupported: true);
    [Output(order: 13)] private IOutputGroup Draft => Output.Query(input: Geometry, port: Port.List<Curve>(name: "Draft Curves", code: "DC", info: "Draft transition curves using Direction as pull direction and Draft Angle, defaulting to 0 radians."), operation: (access, runtime) => Query.Curves<object, Curve>(aspect: Rasm.Analysis.Curves.Draft(direction: runtime.Nullable(access: access, port: Direction), angle: runtime.Nullable(access: access, port: DraftAngle)?.Radians)), emptyUnsupported: true);
    [Output(order: 14)] private IOutputGroup Indexed => Output.Query(input: Geometry, port: Port.List<Curve>(name: "Indexed Curve", code: "IC", info: "Curve at Index input; missing Index defaults to 0, supplied values clamp to [0, count-1]. Empty when zero curves."), operation: (access, runtime) => Query.Curves<object, Curve>(aspect: Rasm.Analysis.Curves.At(index: runtime.NullableIndex(access: access, port: Index))));
    private IOutputGroup CurvesOutput(Port<Curve> port, Curves aspect) =>
        Output.Query(input: Geometry, port: port, operation: (_, _) => Query.Curves<object, Curve>(aspect: aspect), emptyUnsupported: true);
}
