namespace Radyab.Components;

[IoId("F51A09A8-A5A5-467A-ADBA-C950511A0020")]
[Nomen(
    name: "Extract Surfaces",
    info: "Trimmed faces, direction-ranked top/bottom faces, indexed face details, and centroid UV frame for Brep, BrepFace, Surface, and SubD values.",
    category: "Radyab",
    section: "Extraction")]
public sealed class ExtractSurfaces : Component<ExtractSurfaces> {
    [Input(order: 0)] private readonly Port<Shape> Geometry = Port.Required<Shape>(kind: PortKind.Generic, name: "Geometry", code: "G", info: "Geometry to analyse.");
    [Input(order: 1)] private readonly Port<int> Index = Port.Index(info: "Zero-based face selector; missing Index defaults to face 0 and supplied values clamp to [0, count-1].");
    [Input(order: 2)] private readonly Port<Vector3d> Direction = Port.Optional<Vector3d>(kind: PortKind.Vector, name: "Direction", code: "D", info: "Ranking direction for Top/Bottom surfaces; missing Direction uses world Z.", policy: PortPolicy.Vector(unitise: true));
    [Output(order: 0)] private IOutputGroup AllSurfaces => Output.FaceDetails(input: Geometry, faces: Port.List<Brep>(name: "All Surfaces", code: "AS", info: "Every face as a trimmed single-face Brep. Mesh input is intentionally rejected."), indices: Port.List<int>(name: "Surface Indices", code: "SI", info: "Source Brep face index aligned with every extracted surface."), selector: static (_, _) => Rasm.Analysis.Faces.All);
    [Output(order: 1)] private IOutputGroup TopSurface => Output.Query(input: Geometry, port: Port.List<Brep>(name: "Top Surface", code: "TS", info: "Trimmed face(s) with maximum centroid projection along Direction; ties within tolerance."), operation: (access, runtime) => Query.Faces<object, Brep>(aspect: Rasm.Analysis.Faces.Top(axis: runtime.Value(access: access, port: Direction).IfNone(Vector3d.ZAxis))));
    [Output(order: 2)] private IOutputGroup BottomSurface => Output.Query(input: Geometry, port: Port.List<Brep>(name: "Bottom Surface", code: "BS", info: "Trimmed face(s) with minimum centroid projection along Direction; ties within tolerance."), operation: (access, runtime) => Query.Faces<object, Brep>(aspect: Rasm.Analysis.Faces.Bottom(axis: runtime.Value(access: access, port: Direction).IfNone(Vector3d.ZAxis))));
    [Output(order: 3)] private IOutputGroup IndexedFace => Output.IndexedFaceDetails(input: Geometry, index: Index, faces: Port.List<Brep>(name: "Indexed Surface", code: "IS", info: "Trimmed single-face Brep at Index input; missing Index defaults to 0, supplied values clamp to [0, count-1]. Empty when zero faces."), frames: Port.List<Plane>(name: "UV Frame", code: "UV", info: "Native U/V frame at the indexed face centroid. X=surface U direction, Z=orientation-corrected normal, Y completes the basis."), centers: Port.List<Point3d>(name: "Face Center", code: "FC", info: "Area centroid of the indexed trimmed face."), normals: Port.List<Vector3d>(name: "Face Normal", code: "FN", info: "Orientation-corrected indexed face normal at the face centroid."), indices: Port.List<int>(name: "Face Index", code: "FI", info: "Source Brep face index selected by the clamped Index input."), components: Port.List<ComponentIndex>(kind: PortKind.Generic, name: "Face Component", code: "CI", info: "Source Brep face component index selected by the clamped Index input."), domains: Port.List<Interval>(name: "UV Domains", code: "UD", info: "Indexed face domains as two intervals: U first, then V."));
}
