<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssayTestShell>true</AssayTestShell>
        <UseRidGraph>true</UseRidGraph>
    </PropertyGroup>
    <ItemGroup Label="Project References">
        <ProjectReference Include="../../../../libs/dotnet/Rasm.Compute/Rasm.Compute.csproj" />
    </ItemGroup>
    <ItemGroup Label="In-Process Wire Harness">
        <PackageReference Include="Microsoft.AspNetCore.TestHost" PrivateAssets="all" />
    </ItemGroup>
</Project>
